### ISSUE TITLE
Extreme lenteur d'affichage (Explorateur W10 - sous-dossiers d'enclave contenant très grand nombre de docs

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#1039]
Après plusieurs minutes, la barre verte de progression n'a toujours pas disparu, et la roue tourne toujours. Il d'agit d'un sous-dossier d'une enclave avec un très grand nombre de fichiers pdf.

En cours ::
![image](https://user-images.githubusercontent.com/13103240/76988850-b47d6c80-6945-11ea-8c19-8948c5cc67bb.png)

Après plusieurs minutes, pas de terminaison 
![image](https://user-images.githubusercontent.com/13103240/76989168-3a011c80-6946-11ea-85de-3f34de821e0b.png)

![image](https://user-images.githubusercontent.com/13103240/76989416-96fcd280-6946-11ea-8b6b-245d2c8e9d74.png)

**Comment by vxgmichel** [comment]
@PhClermontScille Merci pour le rapport. 

J'ai pu reproduire le probleme, je travaille dessus.

**Comment by vxgmichel** [comment]
@PhClermontScille Le problème était du à un bug spécifique dans la base de code et pas à un problème de performance. Ce sera réglé avec la version `1.10`, merci pour le rapport!
