### ISSUE TITLE
1.9.0 - disparition de la barre de recherche dans le client lourd PARSEC

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#1040]
Dans des versions antérieures, il existait une barre de recherche, pour rechercher par nom dans les fichiers d'un sous-dossier spécifique d'une enclave. Limité fonctionnellement, mais utile.
A disparu.

**Comment by Max-7** [comment]
On l'a volontairement retirée car la fonctionnalité n'était pas assez claire. Elle fera son retour quand on aura une vraie recherche de fichiers.

**Comment by PhClermontScille** [comment]
Je trouve que ça manque, même si limité.  La recherche windows ne marche
pas toujours.
