### ISSUE TITLE
Double clic & Simple clic sur "Répertoire parent"

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1042]
Dans le client lourd Parsec, un utilisateur nous signale :

> Titre : Problème utilisation
> Description : bonjour, Sur Parsec, je ne parviens pas à trouver comment retourner au dossier précédent celui dans lequel je suis, la touche retour de l'explorateur Windows. pourriez-vous m'envoyer une capture d'écran avec cette flèche ? A chaque fois je dois revenir au menu général de PARSEC et refaire le chemin pour aller dans un autre dossier. Merci Nicolas

Après instruction, il s'avère que le problème est ergononomique et vient du fait qu'il faut prévoir d'accepter soit un **simple-clic**, soit un **double-clic** sur : 
![image](https://user-images.githubusercontent.com/9845177/77060244-8eed7300-69d8-11ea-86ed-c1f07ba5da74.png)

**Comment by Max-7** [comment]
Will be fixed with #952

**Comment by Max-7** [comment]
Fixed
