### ISSUE TITLE
Close/minimize state machine logique is broken

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1045]
On Parsec 1.9

- start parsec
- close main window, parsec goes minimize
- right click on parsec tray icon, select close application
- on the confirmation screen, select no
==> the app still get closed

- start parsec
- right click on parsec tray icon, select close application
- on the confirmation screen, select no
- close the main window, the shutdown app confirmation screen appears
- selecting yes result in application shutdown

**Comment by Max-7** [comment]
Will be fixed with #952

**Comment by Max-7** [comment]
Fixed
