### ISSUE TITLE
Bug: pas d'actualisation de la liste des devices après rajout d'un nouveau (sur le device invitant)

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#1048]
Manip:
- PC DELL-PHIL W10 64b
2 devices visibles
- invitation à ajouter un troisième device Bureau-W10-32b     W10 32b
Tout se passe bien, mais : 
- la liste des 3 devices apparait bien sur le nouveau device
- sur le premier DELL-PHIL, à l'origine de l'invitation, le nouveau device n'apparait pas malgré
1/ deconnexion - reconnexion 2/ fermeture parsec - relance - reconnexion 3/ reboot pc

Sur le nouveau device : 
![image](https://user-images.githubusercontent.com/13103240/77345887-8b8a1c80-6d35-11ea-87f4-14641879a5a1.png)

**Comment by Max-7** [comment]
Lié à #952 

Pas testé sur l'ancien design, mais cela sera fixé sur le nouveau (prochaine version de Parsec).

**Comment by Max-7** [comment]
Fixed
