### ISSUE TITLE
Comportement différent: première installation de PARSEC sur W10 32bits

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#1050]
WinFSP propose une version beta. C'est la première install ou mise à jour de parsec où un tel écran s'affiche ::
![image](https://user-images.githubusercontent.com/13103240/77360532-cdbf5800-6d4d-11ea-8cef-e88bef05d8e3.png)
![image](https://user-images.githubusercontent.com/13103240/77360591-edef1700-6d4d-11ea-90ae-1623c5414e7b.png)

**Comment by PhClermontScille** [comment]
![image](https://user-images.githubusercontent.com/13103240/77360688-1aa32e80-6d4e-11ea-9ccc-64974e82a2ae.png)

**Comment by vxgmichel** [comment]
@PhClermontScille Lors d'une installation de parsec, l'installer de winfsp se lance si winfsp n'est pas déja installé. C'est le comportement normal mais cette fenetre est effectivement déroutante. L'installation de winfsp pourrait etre faite de maniere silencieuse, j'ai créé une issue sur le sujet: #1057.

Je ferme cette issue.

**Comment by PhClermontScille** [comment]
Oui, mais ces fenetres ne s'affichaient pas sur mes installs précédentes
(jsq 1.9, mais Win64).
Mes diffrents messages sont spécifiquement liés *à une première install de
Parsec Win32* : messages additionnels d'install WinFSp, warning NAV....*
Je n'ai pas cela en mettant à jour la version 1.9 Win64.



Le jeu. 26 mars 2020 à 14:00, Vincent Michel <notifications@github.com> a
écrit :
