### ISSUE TITLE
Premier lancement de PARSEC 1.9 : fausse erreur signalée

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#1051]
Sur W10 32b. Premier lancement avec message d'erreur. L'erreur n'existe pas : toutes les enclaves affichées sont bien accessibles.
A confirmer: je crois avoir constaté la même erreur au premier lancement hier sur un autre PC W10 *64b*
![image](https://user-images.githubusercontent.com/13103240/77360925-8a191e00-6d4e-11ea-8116-5d6eb933cb75.png)

**Comment by touilleMan** [comment]
Didn't happened since then, closing.
