### ISSUE TITLE
Workspace name translations

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1058]
The way workspace names are handled is currently inconsistent.

On one hand, the suffix `(shared by X)` is added directly to the workspace entry:

https://github.com/Scille/parsec-cloud/blob/3e1f1a0ebb1f21c42aa8e879737c037a62c7597d/parsec/core/fs/userfs/userfs.py#L795

It appears in both the GUI and the mountpoint directory name but it is not translated to French.

On the other hand, the suffix `(shared with others)` is defined in the Qt translations:

https://github.com/Scille/parsec-cloud/blob/dc5a0cd66339a3dc7e5f22140c302cb14533058b/parsec/core/gui/tr/parsec_en.po#L182

It only appears in the GUI but not in the mountpoint directory name and it is translated to French.

My opinion is that we should separate two distinct issue:

- the identification of the workspace in the GUI: the GUI has the tools to display extra information (the user who created the workspace, the user who shared it, the date of creation and so on).

- the identification of the workspace as a mountpoint directory: a string has to be crafted in a way to avoid confusion if two workspaces have the same name. If we choose to include information like `shared by`, it has to be translated too.

I suggest we stop adding extra information to the workspace name in the workspace entry as it is confusing and error prone. For instance, here's what happens if Bob shares a workspace with Alice and Alice shares it with Clara:

     /home/clara/Parsec/bob_workspace (shared by bob) (shared by alice)

One issue with changing this is that we have to deal with backward compatibility, and in particular workspaces that already contains `(shared with X)` information in their names.

**Comment by Max-7** [comment]
I would also add that when remounting a timestamped workspace (a workspace at a given time) in the GUI, the GUI creates its own name for it (something like workspace_name-temporary-date). On the file system, the workspace is simply named with its usual name (adding a counter eventually like "workspace (2)".

**Comment by touilleMan** [comment]
Partially implemented in #1159
