### ISSUE TITLE
Limite fonctionnelle : fichiers Office dans une enclave, accès par un utilisateur en lecture seule

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#1061]
Un fichier Office (Excel par exemple) ne peut pas s'ouvrir en double clic, car le fichier temporaire ~XXXX ne peut être créé. Il n'est pas évident de savoir comment forcer l'ouverture d'un, fichier en lecture seule.
Ceci conduit à un comportement pervers non souhaité mal sécurisé : l'extraction du fichier de l'enclave et le depot sur un dossier provisoire sur son disque dur, pour pouvoir l'ouvrir.

**Comment by touilleMan** [comment]
related to #990

**Comment by stefan-contiu** [comment]
Duplicate of #990
