### ISSUE TITLE
Error output when create organization

### ISSUE THREAD

**Issue by antonio-fr** [Scille/parsec-cloud#1068]
There's a missing leading "f" to signal this is a f-string, and instructing to interpret the curly brackets.
https://github.com/Scille/parsec-cloud/blob/afea11c6de2f517feba6a96bf8f81a3261abc1d9/parsec/core/cli/create_organization.py#L19

After identifying this issue, I checked for similar ones, but this is the only one like this (for RuntimeError).

**Comment by touilleMan** [comment]
Thx ;-)
