### ISSUE TITLE
Create multiple organizations with the same name.

### ISSUE THREAD

**Issue by antonio-fr** [Scille/parsec-cloud#1074]
On parsec backend v1.11+dev.
Replaying multiple times the query to create an organization, is creating the new organizations without any error. So an administrator can create as many organization with the same name he wants? The organizations are internally identified by an internal id? Would be better if a checking of the name already exists is done before creating a new organization. How is the users can pick the right organization ID with just seeing the list of multiple but identical names?

**Comment by touilleMan** [comment]
Hi @antonio-fr,

Organization creation is a two step process:
- first organization creation. Basically a server administrator tell the server to make room for a new organization. This end up with the server providing a bootstrap url link.
- then organization bootstrap. There the organization is configured by it first user (first user upload into the backend it user and device certificates and the organization root verify key)

Hence as long as the bootstrap phase hasn't been done, the organization is an empty shell that can be re-created. This is typically useful in case the bootstrap url link is lost ;-)

Once an organization is bootstrapped, it's no longer possible to create a new organization with similar organization_id.

**Comment by antonio-fr** [comment]
OK I get the inner working, seems good actually.
