### ISSUE TITLE
Acrobat Reader DC does not open a PDF file if another PDF from another workspace is already open

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1081]
Somehow, Acrobat Reader DC does not open a PDF file from a workspace if another PDF from another workspace is already open.

In order to reproduce:
- Open a PDF file using Acrobat Reader (from a workspace or elsewhere on the system)
- Go to a different workspace
- Try to open a PDF file from this workspace using either the file explorer or the application
- Acrobat is expected to pop up and the PDF is expected to open in a new tab
- Instead nothing happens
- Note that it works fine if the file is open directly from acrobat reader

I have absolutely zero idea why this happens...

**Comment by vxgmichel** [comment]
This is due to an Acrobat Reader bug and can be worked around by disabling the protected mode. However, this is not an acceptable solution for us.

The mountpoints-as-drive approach should be to be reconsidered.

**Comment by touilleMan** [comment]
Will be fixed by #1159
