### ISSUE TITLE
Configuration : Make possible the choice of mounting point

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1083]
By default, the software mounts the Parsec enclaves on disk C:
It may happen that the user wishes to mount the disk on another disk, for example Z:
Indeed, if the default mount point corresponds to a disk at capacity limit, the encrypted blocks will not be able to be imported.
A choice should be made in the configuration menu for the mounting point. This function would also be useful in Linux.

**Comment by touilleMan** [comment]
Mountpoint is done on folder not on drive.
Using a Parsec directory in the user home folder as root mountpoint is a good default, I don't see any usecase for adding configuration on this.

**Comment by tleblond** [comment]
When a file on a Parsec enclave is downloaded, its cypher blocks must be stored localy. If the user as no more place on C: (which is the true reason why he wants to mount Parsec on a Z: or else) what happens to the local downloaded blocks ?

**Comment by vxgmichel** [comment]
@tleblond 
> what happens to the local downloaded blocks ?

The block cache and the mountpoint directory are two different things, at two different locations. On windows, the block cache is typically in `C:\Users\User\AppData\Roaming\Parsec\data` and is limited to 512MB. I don't see the point in configuring this location, at least not until the local/offline mode is implented.
