### ISSUE TITLE
Ouverture PDF depuis le point de montage

### ISSUE THREAD

**Issue by Jorgeparsec** [Scille/parsec-cloud#1092]
Parsec V1.10.0
OS Window 10 64
Adobe Acrobat Reader DC ver 2020.006.620042
Je sélectionne un fichier dans Parsec point de montage
![image](https://user-images.githubusercontent.com/63036151/78226747-7b5c0500-74cc-11ea-8a25-9e4e0998f139.png)

Un document est ouvert dans Acrobat Reader
![image](https://user-images.githubusercontent.com/63036151/78226876-b2321b00-74cc-11ea-86f7-4a97092cbcdf.png)

J'essaie d’ouvrir le PDF rien y fait.  Je suis obligé de fermer Acrobat . Sélectionner le fichier PDF dans Parsec et là je l'ouvre
![image](https://user-images.githubusercontent.com/63036151/78227106-0dfca400-74cd-11ea-899c-8e5b2e2ab5db.png)

**Comment by Max-7** [comment]
Le problème est connu et a déjà été décrit dans #1081. Je met permets de fermer cette issue.
