### ISSUE TITLE
S3 client library outdated

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1094]
Testing different S3 providers with Parsec, one is not working, and the error `botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden` is thrown.
This behavior is fixed when the boto3 package is updated to the latest pip version v1.12.34. The actual package version specified in Parsec v1.4.4 is more than 3 years old. It might need a little update.
We are testing multiple providers to see if this update is not breaking anything.
We'll update our PR #1088 with this change if everything OK.

**Comment by touilleMan** [comment]
I agree, we should have updated this dependency a looong time ago !

**Comment by touilleMan** [comment]
fixed by #1088
