### ISSUE TITLE
parsec:// urls do not bring the app to the foreground if it's minimized

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1100]
If parsec is miminized (in the task bar, not in the tray), then opening a parsec URL do not bring the application to the foreground. This is confusing as users expect something to happen but nothing is visible on screen.

Happens on windows and linux.

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/840c4f555e5250af3861b471404ee05f925f3ee5
