### ISSUE TITLE
Parsec en racine de Explorer windows

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#1113]
![Capture d'écran 2020-04-07 16 51 04](https://user-images.githubusercontent.com/46708918/78684051-531b3e80-78f0-11ea-9ad8-7aaefff7616c.png)

je n'arrive pas a avoir Parsec ( icone ) racine de mon gestionnaire de fichier Windows , sauf à aller le chercher je ne me souviens plis ou  et de le mette en lien rapide

**Comment by Max-7** [comment]
Dupplicate of #839, closing this one.
