### ISSUE TITLE
optimization interface user

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#1114]
Quelques idees pour designer l'interface user
![Capture d'écran 2020-04-07 18 40 08](https://user-images.githubusercontent.com/46708918/78698985-6edc1000-7903-11ea-89c3-1a03c452d357.png)
Dans celui ci , il y a une inforlation qui donne la taille du stockage occupé
je mettrais le chemin pour acceder au fichier au dessus des fichiers et pas en haut à gauche ou ca n'est pas evident à trouver
![Capture d'écran 2020-04-07 18 53 01](https://user-images.githubusercontent.com/46708918/78699225-d8f4b500-7903-11ea-9132-5b04eb9fcb6a.png)
et sur google il y a une fonctionnalité derniers vus , et/ou favoris

**Comment by touilleMan** [comment]
too old, closing
