### ISSUE TITLE
Improve workspace creation experience for first time users  

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1121]
So far we discussed UI/UX improvements for creating an organization (#1014) and inviting users (#1037). The current issue differently proposes investigating improvements for the scenario of : creating a workspace.

Example of suggestions : 
* Creating a workspace could imply adding data and inviting users as fast as possible in the actions flow (maybe by a wizard during workspace creation?) 
* Creating an organization could imply creating a first workspace? (again with a wizard)
* Have animations to go along with the actions of the user (create workspace, add data, add users)

**Comment by stefan-contiu** [comment]
UX Workshop 23/04/2020 converged to the following requirements :

First time users  (by wizard or guided by animations) :
1. Immediately after creating the organization, the administrator should invite a list of other users in the organization.
2. Create a first workspace (name by default or changed by the user)
3. Add rights on the workspace to users invited at step 1.These rights should go in a pending list and be activated only once the invited user joins the organization by the security protocol.

**Comment by touilleMan** [comment]
Too old
