### ISSUE TITLE
Lancement de l'executable

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#113]
1 - blocage par windows defender qu'il faut bypasser 
![image](https://user-images.githubusercontent.com/46708918/51172652-f9c28c00-18b3-11e9-877d-51082c933115.png)
Peut on eviter?

2- comment eliminer la page "parsec core"
![capture d ecran 2019-01-15 10 43 43](https://user-images.githubusercontent.com/46708918/51172739-30000b80-18b4-11e9-909b-0785664395c8.png)

3 - si je sors de cet ecran sans avoir créé un user , le pgm parsec disparait et je suis oblige de relancer l'executable

**Comment by frossigneux** [comment]
1 - À partir du build 05ab3c5d39ae702d59a92bac9cace13c, je signe les exécutables.
Cependant, nous avons pris un certificat peu cher, et du coup il y aura probablement cette fenêtre.
Plus tard on prendra un certificat plus cher pour ne plus avoir cette fenêtre.
La signature devrait néanmoins empêcher les antivirus une mise en quarantaine injustifiée.

2 - Cette fenêtre est présente à des fins de débogage. On la laisse activée pendant la phase de tests, mais on la désactivera pour les builds correspondant à des tags (et non pas des commits).

3 - C'est normal. La fenêtre disparaît mais reste présente en zone de miniature. D'où on peut la rouvrir, peut-être via un clic droit.
