### ISSUE TITLE
double login

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#1135]
![Capture d'écran 2020-04-23 11 14 43](https://user-images.githubusercontent.com/46708918/80082352-8a2a5a80-8554-11ea-9059-eb28aba91da2.png)ca fait 2 fois qu'il me dit que je suis deja logge alors que non

par ailleurs , mon icone Parsec qui apparait dans la barre de tache n'ouvre pas Parsec

**Comment by touilleMan** [comment]
Fixed since last GUI upgrade
