### ISSUE TITLE
comment creer une organisation 

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#114]
Sur la fenetre de saisie Id etc....
 il faut un jeton , mais quand le premier du groupe démarre , il n'y a pas de jeton j'imagine ?
et on ne voit pas de champ :"organisation" du coup , comment le premier qui veut créer une organisation peut il demarrer

**Comment by stefan-contiu** [comment]
Serge suggests that the first user should download the application and then create the organization from the app. The current steps and their justification for users are unclear.

**Comment by frossigneux** [comment]
Il y a une documentation ici :
https://github.com/Scille/parsec-cloud/wiki/Parsec-overview

On crée l'organisation sur l'interface web (ou à défaut via la command line... en fournissant un token secret permettant le management du backend).
En retour, on obtient une URL (contenant un paramètre bootstrap-token).
Cela évite qu'un utilisateur malveillant, connaissant le token de management du backend, crée le compte du premier utilisateur à notre place.

Ensuite, sur la première machine appartement à l'organisation, on boostrap l'organisation en créant le 1er utilisateur. Pour l'instant en command line, bientôt via une fenêtre graphique.
