### ISSUE TITLE
Create a limited user role (e.g., guest) 

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1144]
Client needs for a limited guest role, different than current roles of administrator, writer, and reader :
* guest user should not be able to create workspaces
* guest user should not see who else is part of the organization
* guest user should not see who else has right on the workspace

**Comment by touilleMan** [comment]
API changes done in #1174
We still have to modify the Core and the GUI for this new kind of user profile

**Comment by touilleMan** [comment]
done since v2.4.0
