### ISSUE TITLE
Revisit naming of restored files/folders

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1146]
Currently when restoring past versions of files/folders the name receives a counter value, example : "File (2)". Instead we should use meaningful names such that the user can discriminate between the current and the (potentially many) restored past version(s). A possibility is to include the timestamp in the name (yyyyMMdd) of restored files/folders.

**Comment by bitlogik** [comment]
Any update on that topic?

**Comment by c4ffein** [comment]
> Any update on that topic?

It should be fixed that month

**Comment by touilleMan** [comment]
too old
