### ISSUE TITLE
Freeze while opening big folder in cli

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#116]
La cli récupère toutes les métadonnées des fichiers d'un répertoire avant d'afficher celui-ci.
Sur un gros répertoire qui n'est pas dans le cache local, la gui freeze pendant longtemps avant de réaliser l'affichier.

Une solution serait de récupérer uniquement la liste des éléments du répertoire, de rafraichir la vue avec ces infos, puis d'avoir une tache de fond requêter les détails pour chaque fichier (on verait donc les infos du fichiers du répertoire s'afficher au fur et à mesure)

**Comment by Max-7** [comment]
Should be fixed.
