### ISSUE TITLE
Erreur en cas de création d'un utilisateur déjà présent sur le poste

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#117]
C'est un cas où quelques temps auparavant, on avait créé un user sur son poste (ex : Alice) et qu'on l'a oublié. Si on veut de nouveau créer un user du nom de Alice ou reçoit un message d'erreur "Impossible d'enregistrer le nouvel utilisateur" sans autre précision.
Si dans le répertoire .config/parsec/devices on supprime le compte Alice, il n'est toujours pas possible de créer l'utilisateur Alice sans doute parce que le compte Alice est déjà sur le serveur de métadonnées (??).

Lorsque l'on veut créer un compte Alice3, donc qui n'existait pas avant, on reçoit le même message d'erreur. Ce qui veut dire que ce n'est peut-être pas seulement lié à la dupplication d'un compte existant.

A noter que, dans ce cas d'usage, les deux clients parsec (celui coté de l'enroleur et celui côté de l'enrôlé) sont ouverts sur la même machine
Il faudrait que le message soit plus précis sur ce qu'il convient de faire ans ce cas.

**Comment by touilleMan** [comment]
cf. https://github.com/Scille/parsec-cloud/pull/161

**Comment by touilleMan** [comment]
cf. https://github.com/Scille/parsec-cloud/issues/169

**Comment by touilleMan** [comment]
fixed by #359
