### ISSUE TITLE
Client GUI shows in-progress sync while file explorer correctly shows completed

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1192]
I did a ~500 MB copy from an outside dir into the workspace mountpoint... it took few minutes. File explorer progress shows completed, which is correct, while Parsec GUI shows the in-sync icon. See attach. 

![image](https://user-images.githubusercontent.com/8625772/84676297-a1227300-af2d-11ea-9fdc-645835e6e854.png)

**Comment by touilleMan** [comment]
This is the expected behavior: red arrows represent the need for remote sync which is de-correlated from the copy of data into Parsec (i.e. storing in the local parsec storage)

**Comment by touilleMan** [comment]
related to #694
