### ISSUE TITLE
Notify org admin / workspace owner in case of direct copy to an external storage

### ISSUE THREAD

**Issue by c4ffein** [Scille/parsec-cloud#1195]
It could be nice for an admin / owner to have an option to know if an user take out data he is not supposed to.
He could be notified in case of a direct copy, it wouldn't be useful in case of indirect copies (for exemple, to his desktop, then to a thumbdrive), but it would still be valuable in the case of non-malicious but not privacy-aware enough users.

**Comment by c4ffein** [comment]
Proposes partial solution for #1197

**Comment by touilleMan** [comment]
too old, closing
