### ISSUE TITLE
Export workspace to encrypted archive

### ISSUE THREAD

**Issue by c4ffein** [Scille/parsec-cloud#1196]
Currently, the most convenient way for an user to put multiple document out of Parsec is to simply copy partial or total content to another place, and there is no technical way to prevent that.
A mitigation taking into account that user behavior would be to propose an "export as encrypted archive" option, which could mitigate the risk of having users taking out unencrypted documents.
We could also notify the workspace owner / org admin, or at least keep track of those exports.

**Comment by c4ffein** [comment]
Proposes partial solution for #1197

**Comment by touilleMan** [comment]
too old, closing
