### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#1209]
J'ai voulu tester le site marchand à partir du Parsec.cloud

1/ obligation de telecharger Parsec : j'avais deja parsec installé et tu ne sais pas quoi faire à partir du site sauf a recharger parsec??

2/  j'ai telecharger Parsec et je l'ai utilisé ; une fois utilisé , j'ai voulu creer un compte en cliquant sur espace client : et là je returne à la page telecharger Parsec que j'ai deja telechargé ??

Bref : as a result , pas pu entrer sur le site marchand

**Comment by c4ffein** [comment]
Will be fixed in merchant site frontend
