### ISSUE TITLE
Accept user invitation CLI

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1212]
What's the CLI command to accept a user invitation for an organization ? Is it claim_invitation?

`parsec core claim_invitation --password=764084 "parsec://server.com/ORG?action=claim_user&user_id=User&rvk=25HJXPL065MND43TMMBSR62MIEWXKVZFJXNL4ZQGOZD7COGLX4FQdddd"
`

I keep getting :
`Error: Invalid value for "ADDR": parsec://server.com/ORG?action=claim_user&user_id=User&rvk=25HJXPL065MND43TMMBSR62MIEWXKVZFJXNL4ZQGOZD7COGLX4FQdddd
`

If claim_invitation, what's the ADDR format?

**Comment by bitlogik** [comment]
Is it fixed by https://github.com/Scille/parsec-cloud/pull/1211/commits/73e2e8f335610fc9b547beded9fa71da75b36246#diff-8471fefaa5e6b558ce24a40f3551e1d5 ?

**Comment by touilleMan** [comment]
yup, sorry fix this ;-)
