### ISSUE TITLE
Affichage comprimé avec mise à l'échelle > 100%

### ISSUE THREAD

**Issue by Gaspard-a11y** [Scille/parsec-cloud#1219]
![image](https://user-images.githubusercontent.com/64432027/85299283-6082a680-b4a5-11ea-9ce6-9529a665f03b.png)

![image](https://user-images.githubusercontent.com/64432027/85299526-a9d2f600-b4a5-11ea-8abf-1fcb99b958c3.png)

L'affichage se passe sans soucis à 100%

**Comment by Max-7** [comment]
Merged. Closing the issue.
