### ISSUE TITLE
dimension d'

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#1238]
Vue ecran sur microsoft surface
<img width="900" alt="2020-07-01" src="https://user-images.githubusercontent.com/46708918/86251448-2bb3d500-bbb2-11ea-8fa1-79556e15a54f.png">

**Comment by Max-7** [comment]
Should be fixed by https://github.com/Scille/parsec-cloud/commit/717d9cb32781ba3670710abacb5da9f014c577ca
