### ISSUE TITLE
Mismatch password not explained in user claim dialogue

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1265]
![image](https://user-images.githubusercontent.com/3187637/87222422-cf03a780-c373-11ea-9be6-44de735f425f.png)

There should be a text under the `password: WEAK` to explain the passwords mismatch (and hence the ok button is greyed out)

**Comment by bitlogik** [comment]
Instead of adding a new text field under the WEAK info, better to compute the password strength on the first input only, and only display one info about the mismatch. The second password is as strong as the first one, when they're identical : they're either mismatched or both weak.

**Comment by Max-7** [comment]
Closed by #1375
