### ISSUE TITLE
Improve device invitation error message when greeter pick a wrong code

### ISSUE THREAD

**Issue by AntoineDupre** [Scille/parsec-cloud#1278]
![Screenshot 2020-07-16 16:23:03](https://user-images.githubusercontent.com/1070501/87683015-d1ee0600-c780-11ea-9023-5a706dbded01.png)

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/5d5863a7d2a5dcb6df8c5c9dfc5e0681b62da874
