### ISSUE TITLE
Can't run when install by pip (whl)

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1307]
On Ubuntu 20.04

pip3 install xx.whl["core"] (v0.14)

At start :
```
$QT_DEBUG_PLUGINS=1 /home/myuser/.local/bin/parsec core gui
...
Cannot load library /home/myuser/.local/lib/python3.8/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so:
(libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/myuser/.local/lib/python3.8/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so":
"Cannot load library /home/myuser/.local/lib/python3.8/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so:
(libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
...
```

Parsec GUI can't start.
It can, after installing:
`apt-get install libxcb-xinerama0
`

So, this would require to add a pip package which brings the missing lib.

One cause of the issue is that the core gui test is disabled in the PIP wheel production, so this requires a manual test, as we did.
https://github.com/Scille/parsec-cloud/blob/master/.azure-pipelines.yml#L339

If we load the present version (1.9.1) :
```
pip3 install parsec["core"]
/home/myuser/.local/bin/parsec core gui
```
-> Parsec GUI is starting right, without any added package (such as libxcb-xinerama0)

We don't know yet, what is causing this change. It may be
```
- PYQT_DEP = "PyQt5==5.13.1"
+ PYQT_DEP = "PyQt5==5.15.0"
```
This maybe also a bug on PyQT, which doesn't bring the right Qt dependencies lib.
This dev battle might be of interest for this matter :
https://forum.qt.io/topic/115418/test-under-xvfb-fail-after-upgrade-to-qt-5-15-0-for-python

**Comment by vxgmichel** [comment]
Hi @bitlogik, thanks for the report!

We ran into other issues with PyQt5 version `5.15.0`, would you mind trying with `PyQt5==5.14.2`?

**Comment by bitlogik** [comment]
OK, I guess this issue in Parsec is the direct result of this "P1" critical opened bug in QT 5.15.0.
https://bugreports.qt.io/browse/QTBUG-84749

The QT dev started to work on this a week ago and wondered "how did this pass the RTA testing?"

**Comment by bitlogik** [comment]
It works well with pyQT5 5.14.2.
As you suggest, I would recommend to setup PyQt5==5.14.2. QApplication.setHighDpiScaleFactorRoundingPolicy only requires 5.14. And 5.15.0 has this dismaying bug in Ubuntu 20.
When this will be fixed in QT and pyQT, pyQT5 could be upgraded to the newest version (5.15.1, 5.15.2 ?).
