### ISSUE TITLE
Rollback to PyQt 5.14.2 might break Windows production in some environments [investigating]

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1309]
Following, the [PyQT5 issue fixing](https://github.com/Scille/parsec-cloud/pull/1308), and the [issues related to the binaries package builds](https://github.com/Scille/parsec-cloud/commit/2fbe93b4c2fa99f8647640b5622587ef00fbae01), we'd like to report a potential issue when you'll build the package for Windows. Full software testing is part of the delivery, but sadly, there's no test dedicated to binary package production, so you mostly discover the issue once the new version is tagged for released.

The Windows installer production script seems to be broken by this PyQT5 rollback.
One of our pipeline was OK for Windows, we just merged 23c939e9d53c4d1e0a1fa6ed70219a68a1ffae3b, and it now fails, as follow :

```
Building wheels for collected packages: parsec-cloud, msgpack, pendulum, PyPika
  Building wheel for parsec-cloud (setup.py): started
  Building wheel for parsec-cloud (setup.py): finished with status 'error'
  Running setup.py clean for parsec-cloud
  ERROR: Command errored out with exit status 1:
  ImportError: DLL load failed while importing sip: The parameter is incorrect.
```

Full log (from the failure point) :
```

Collecting pytz>=0a
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
  Saved c:\test_user\builds\parsec\parsec-cloud\packaging\win32\build\wheels\pytz-2020.1-py2.py3-none-any.whl
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
  Saved c:\test_user\builds\parsec\parsec-cloud\packaging\win32\build\wheels\pycparser-2.20-py2.py3-none-any.whl
Skipping attrs, due to already being wheel.
Skipping click, due to already being wheel.
Skipping wsproto, due to already being wheel.
Skipping toastedmarshmallow, due to already being wheel.
Skipping PyNaCl, due to already being wheel.
Skipping trio, due to already being wheel.
Skipping python-interface, due to already being wheel.
Skipping async-generator, due to already being wheel.
Skipping sentry-sdk, due to already being wheel.
Skipping structlog, due to already being wheel.
Skipping importlib-resources, due to already being wheel.
Skipping colorama, due to already being wheel.
Skipping async-exit-stack, due to already being wheel.
Skipping outcome, due to already being wheel.
Skipping PyQt5, due to already being wheel.
Skipping Babel, due to already being wheel.
Skipping zxcvbn, due to already being wheel.
Skipping psutil, due to already being wheel.
Skipping winfspy, due to already being wheel.
Skipping h11, due to already being wheel.
Skipping tzlocal, due to already being wheel.
Skipping python-dateutil, due to already being wheel.
Skipping pytzdata, due to already being wheel.
Skipping cffi, due to already being wheel.
Skipping six, due to already being wheel.
Skipping sortedcontainers, due to already being wheel.
Skipping sniffio, due to already being wheel.
Skipping idna, due to already being wheel.
Skipping urllib3, due to already being wheel.
Skipping certifi, due to already being wheel.
Skipping PyQt5-sip, due to already being wheel.
Skipping pytz, due to already being wheel.
Skipping pycparser, due to already being wheel.
Building wheels for collected packages: parsec-cloud, msgpack, pendulum, PyPika
  Building wheel for parsec-cloud (setup.py): started
  Building wheel for parsec-cloud (setup.py): finished with status 'error'
  Running setup.py clean for parsec-cloud
  ERROR: Command errored out with exit status 1:
   command: 'C:\test_user\builds\parsec\parsec-cloud\packaging\win32\build\tools_venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\test_user\\AppData\\Local\\Temp\\pip-req-build-5j1f6xs_\\setup.py'"'"'; __file__='"'"'C:\\Users\\test_user\\AppData\\Local\\Temp\\pip-req-build-5j1f6xs_\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\test_user\AppData\Local\Temp\pip-wheel-hxyz5n3f'
       cwd: C:\Users\test_user\AppData\Local\Temp\pip-req-build-5j1f6xs_\
  Complete output (44 lines):
  C:\test_user\builds\parsec\parsec-cloud\packaging\win32\build\tools_venv\lib\site-packages\setuptools\dist.py:454: UserWarning: Normalizing 'v1.14.0-rc4+dev' to '1.14.0rc4+dev'
    warnings.warn(tmpl.format(**locals()))
  running bdist_wheel
  running build
  running build_py
  running generate_pyqt_forms
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\test_user\AppData\Local\Temp\pip-req-build-5j1f6xs_\setup.py", line 346, in <module>
      setup(
    File "C:\test_user\builds\parsec\parsec-cloud\packaging\win32\build\tools_venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "C:\Python38\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Python38\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\test_user\builds\parsec\parsec-cloud\packaging\win32\build\tools_venv\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\Python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Python38\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\test_user\AppData\Local\Temp\pip-req-build-5j1f6xs_\setup.py", line 248, in run
      self.run_command("generate_pyqt_forms")
    File "C:\Python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\test_user\AppData\Local\Temp\pip-req-build-5j1f6xs_\setup.py", line 117, in run
      fix_pyqt_import()
    File "C:\Users\test_user\AppData\Local\Temp\pip-req-build-5j1f6xs_\setup.py", line 43, in fix_pyqt_import
      module = importlib.util.module_from_spec(spec)
    File "<frozen importlib._bootstrap>", line 556, in module_from_spec
    File "<frozen importlib._bootstrap_external>", line 1101, in create_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  ImportError: DLL load failed while importing sip: The parameter is incorrect.
  ----------------------------------------
  ERROR: Failed building wheel for parsec-cloud
  Building wheel for msgpack (setup.py): started
  Building wheel for msgpack (setup.py): finished with status 'done'
  Created wheel for msgpack: filename=msgpack-0.6.0-cp38-cp38-win_amd64.whl size=72992 sha256=bab8f69c6acb67afec17aa7425226cf66b0896bafed8ff80bbeb4c681189f7e0
  Stored in directory: c:\users\test_user\appdata\local\pip\cache\wheels\93\5f\65\8c8599cd811e13172717cdede5b3f8343f26b5ac8ea67b092e
  Building wheel for pendulum (setup.py): started
  Building wheel for pendulum (setup.py): finished with status 'done'
  Created wheel for pendulum: filename=pendulum-1.3.1-cp38-cp38-win_amd64.whl size=113171 sha256=53617d281e5b03b02f4aa85df50a3af90b8a54044cff4bf38109317ac943744a
  Stored in directory: c:\users\test_user\appdata\local\pip\cache\wheels\c8\08\24\2096bb9a80cba0047a5a1652616d8bfdb3fef177630d9f30bd
  Building wheel for PyPika (setup.py): started
  Building wheel for PyPika (setup.py): finished with status 'done'
  Created wheel for PyPika: filename=PyPika-0.36.5-py2.py3-none-any.whl size=90584 sha256=6bd9149d73cb7646757ab796bbe68d9e8344140338d8cfea3f55767427245076
  Stored in directory: c:\users\test_user\appdata\local\pip\cache\wheels\11\66\c3\44000e0fac56d0162c918d13e962a1f999175e72a0cf8eb110
Successfully built msgpack pendulum PyPika
Failed to build parsec-cloud
ERROR: Failed to build one or more wheels
### Detected Parsec version v1.14.0-rc4+dev ###
### Fetch CPython 3.8.5 build ###
### Create tool virtualenv ###
>>> python -m venv build\tools_venv
>>> build\tools_venv\Scripts\python -m pip install wheel
### Generate wheels from Parsec&dependencies ###
>>> build\tools_venv\Scripts\python -m pip wheel ..\..[core] --wheel-dir build\wheels
Traceback (most recent call last):
  File "freeze_parsec.py", line 195, in <module>
    main(Path(args.parsec_source))
  File "freeze_parsec.py", line 64, in main
    run(
  File "freeze_parsec.py", line 37, in run
    assert ret.returncode == 0, ret.returncode
AssertionError: 1

```

We might consider using PyInstaller with a spec file, to replace most parts of the freeze_parsec script in our upcoming fork, to tackle this kind of issue.

**Comment by bitlogik** [comment]
Well, it ran well on Azure CI.
https://pastebin.com/tw290PgL

I'm investigating the difference with the other production pipeline.

**Comment by vxgmichel** [comment]
Thanks for the info! 

At the moment, I'm adding a task to the build pipeline to make sure the produced installer work correctly.

In the meantime, you might want to check your version of sip since we're not enforcing any in our requirements.

**Comment by bitlogik** [comment]
"check your version of sip"
Good point! I was focused on pip and setup-tools, as the Azure pipeline keeps saying "You are using pip version 18.1, however version 20.2b1 is available. You should consider upgrading via the 'python -m pip install --upgrade pip' command.". And I think the other pipeline with the issue is running a more update pip (v20). But the PyQt5-sip version might also be a concern.

**Comment by vxgmichel** [comment]
I've been unable to install the NSIS installer in Azure after it's built, the following command hangs forever:
```
dist/parsec-v1.14.0-rc4-15-ga63163f0-win64-setup.exe /S /D=d:a_temp/parsec-install
```
(https://dev.azure.com/Scille/parsec/_build/results?buildId=2468&view=logs&j=d80f536d-c2bc-56c3-145e-ff09338295d8&t=95fd2aaf-ced0-57fd-e83b-dc0932e0cd76&l=15)

Any suggestion on how to do that?

**Comment by bitlogik** [comment]
First of all, when the Windows setup was generated, it was never ever an issue (so far), so I don't think think is useful to test the real installation. What's matter is the installer pipelines sturdiness, up to the final package creation.

If you really want to test the setup in the Windows pipeline, here's what I'm doing when there are complex commands or behavior to test in the CI/CD. I start a VPS online and try to figure out manually what can be the right commands to have in the CI/CD pipeline, as this is 10000x faster than in the yml pipeline where each try takes 5-20 minutes. With a VPS you can have a live sandbox, and when you want to start from zero (when the sandbow is dirty by many commands, or to test the final commands list), some providers offer a one-click VPS reinstallation that takes 2 minutes. In the present case, you need a VPS provider which offers Windows VPS machine (then reaching through RDP), and I advise one with a one click VPS OS re-installation for fast cleaning reset. I did that many times for this project, Ubuntu, Windows, this offers a full environment (after a couples of init packages install), and very fast to get a new clean system.

**Comment by vxgmichel** [comment]
@bitlogik Thanks for the advice, I'll try that !

**Comment by vxgmichel** [comment]
@bitlogik Did you find out what you problem was? Can we close this issue?

**Comment by bitlogik** [comment]
didn't have time to work on this. First thing I consider is to make a table with the different versions of the different package (Python, pip, PyQT5-sip,...) Azure Here vs Others. Also, I'll give it a try with Python 3.7 instead of 3.8 (yours is 3.6).

**Comment by bitlogik** [comment]
And one can left it opened, the time to investigate. We'll see when we'll know more.

**Comment by vxgmichel** [comment]
Sure no problem ! :)

**Comment by bitlogik** [comment]
Here's the result of the study.

Versions | Azure-515 | Azure-514| AltCICD-515 | AltCICD-514 | AltCICD-514-37 |
--------- | ------------ | ---------- | -------------- | ------------- | -----------------
Windows 10 | 1809 | 1809 | 1809 | 1809 | 1809
VS | 2019 | 2019 | 2019 | 2019 | 2019 
build tools | v16.6.4 | v16.6.4 | v16.2.3.0 | v16.2.3.0| v16.2.3.0
Python | 3.6.8 | 3.6.8 | 3.8.5 | 3.8.5 | 3.7.8
pip | 18.1 | 18.1 | 20.1.1 | 20.1.1 | 20.1.1
wheel | 0.34.2 | 0.34.2 | 0.34.2 | 0.34.2 | 0.34.2 
pyQT5 | 5.15.0 | 5.14.2 | 5.15.0 | 5.14.2 | 5.14.2
PyQT5-sip | 12.8.0 | 12.8.0 | 12.8.0| 12.8.0| 12.8.0
Build? | OK | OK | OK | Nok* | OK

Nok * = this current issue :
 ```
File "C:\Users\usr\AppData\Local\Temp\pip-req-build-1ifipgyu\setup.py", line 43, in fix_pyqt_import
      module = importlib.util.module_from_spec(spec)
    File "<frozen importlib._bootstrap>", line 556, in module_from_spec
    File "<frozen importlib._bootstrap_external>", line 1101, in create_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  ImportError: DLL load failed while importing sip: The parameter is incorrect.
```

I notice that the pyqt5-sip installation is performed from whl, but 3.7 or 3.8, this is a different whl :  
  pyqt5_sip-12.8.0-cp38-cp38-win_amd64.whl or  
  pyqt5_sip-12.8.0-cp37-cp37m-win_amd64.whl

This issue appears to be related when importing pyQT5-sip with Python 3.8. I seek for this issue on the web, and I haven't reched any conclusive issues, except that many people are facing this trouble, no clear fix. Some people tell "update Windows", no fix yet, or back down to Python 3.7. Maybe there's an issue in the pyqt5sip-py38.whl, or the importlib has a bug in Python3.8.

For this project, and for now, the best is to stick with Python 3.6 or 3.7 to build the package.

And related to this matter, I suggest to define the pyQt5-sip version to 12.8.0, in the relevant place (setup.py?). This would avoid [breaking change issue in the future](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1756581.html).

**Comment by vxgmichel** [comment]
> This issue appears to be related when importing pyQT5-sip with Python 3.8. 

Yes we don't support python 3.8 at the moment, but we will work on it at some point

> And related to this matter, I suggest to define the pyQt5-sip version to 12.8.0, in the relevant place (setup.py?). This would avoid breaking change issue in the future.

Great suggestiion, I'll make a PR for it :)

**Comment by vxgmichel** [comment]
Now that #1360 is merged, I'm closing this issue for the moment if that's ok with you !
