### ISSUE TITLE
disques virtuels

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#1310]
![Capture d'écran 2020-07-27 23 10 58](https://user-images.githubusercontent.com/46708918/88592753-cb07a300-d05e-11ea-8f21-09c806f33c54.png)
les disk virtuels ne permettent pas de savoir à quelle organisation ils font partie

**Comment by vxgmichel** [comment]
Ajouter le nom de l'organisation dans le nom du drive risque d'alourdir l'expérience utilisateur dans le cas nominal, à savoir celui d'un poste avec un seul utilisateur parsec configuré.

Les alternatives pour l'utilisateur mutli-organisation sont:
- controller le nombre de disques disponibles en désactivant les espaces de travail non utilisé
- renommer les espaces de travail pour leur donner des noms plus signifiants
- utiliser la GUI pour ouvrir l'explorateur de fichier dans un espace de travail donné
