### ISSUE TITLE
Error when sending email for inviting a new device

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1319]
I clicked on the "Send email" button for inviting a new device and I received the error : "Impossible d'envoyer l'email". 
Stack trace : 
```
error

Traceback (most recent call last):

File "/snap/parsec/182/lib/python3.6/site-packages/parsec/core/gui/greet_device_widget.py", line 117, in _do_send_email
return await core.new_device_invitation(send_email=True)

File "/snap/parsec/182/lib/python3.6/site-packages/parsec/core/logged_core.py", line 193, in new_device_invitation
raise BackendConnectionError(f"Backend error: {rep}")

parsec.core.backend_connection.exceptions.BackendConnectionError: Backend error: {'status': 'not_available'}


The above exception was the direct cause of the following exception:


parsec.core.gui.trio_thread.JobResultError: error

```
![image](https://user-images.githubusercontent.com/8625772/88779849-80834500-d18a-11ea-9b98-03f1585108f5.png)

**Comment by touilleMan** [comment]
The gui should hide the "send email" button for device invitation when the corresponding user doesn't have a human handle (and hence it has no email address to send to)

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/b8977b715538726a06328bfdc8e7dae3070bc329
