### ISSUE TITLE
User invitation email : the "Invite Link" button does not work

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1320]
I am using Chrome on Ubuntu. The email displays well. However, differently than "Download Parsec" the "Invite Link" button : 

1. Does not change mouse pointer when hovering.
2. Has no action associated, source code lists a simple `<a>Invite Link</a>` tag without a target link.

![image](https://user-images.githubusercontent.com/8625772/88781283-7eba8100-d18c-11ea-85ec-803e7aafef3d.png)

**Comment by bitlogik** [comment]
Same as this https://github.com/Scille/parsec-cloud/issues/1168 ?
If so, this is fixed by https://github.com/Scille/parsec-cloud/pull/676 (available in next version)

**Comment by vxgmichel** [comment]
Fixed in #1289
