### ISSUE TITLE
Correctly execute Fuse on MacOS

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1323]

**Comment by Ironicbay** [comment]
Issues met on macOS with osxfuse :

- `cmd + Q` works fine to quit the program at any moment, quitting from the menu works as long as no mountpoint were mounted during execution (doesn't work if one was mounted then unmounted)

- Opening certain files from Parsec doesn't work (.txt files work and opens the Apple text editor, .jpeg files don't as the Apple image viewer crashes doing so)

- Mounted volumes have osxfuse names and not workspace names

- Mountpoints only shows in directories in the finder, not as ejectable volumes on the "quick access"-type window

- Can't copy and paste files from Finder in a workspace ("not enough space" error), although this operation is working fine from Parsec app
