### ISSUE TITLE
Make offline mode more obvious to the users

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1330]
@tleblond reported that users don't necessarily realize that the reason why a document fails to open is because the system is offline at the moment. This could be solved by making offline mode more obvious to the users.

**Comment by stefan-contiu** [comment]
Stress the case when the user is not in the GUI.

**Comment by AntoineDupre** [comment]
Fixed in PR #1342 

Now a systray notification is sent when one logged in organization backend is disconnected. This makes the disconnection obvious even if the parsec client is not directly in used. (It does not wok for user that logged in through the CLI)
