### ISSUE TITLE
Mountpoint stays in the windows file explorer side menu even after unmounting

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1344]
![image](https://user-images.githubusercontent.com/3187637/89521166-51e71900-d7df-11ea-967b-aea775e4f0ae.png)

To reproduce:
- login into Parsec, mount a workspace
- open the windows file explorer, the drive corresponding to the workspace is visible
- unmount the workspace (without login out from Parsec)
- go back to the windows file explorer, the drive is still there and accessing it end up in an error (which is expected of course ^^)

**Comment by Max-7** [comment]
Works fine now.
