### ISSUE TITLE
Wrong error message when creating an org with a name already taken

### ISSUE THREAD

**Issue by Sithi5** [Scille/parsec-cloud#1345]
![image](https://user-images.githubusercontent.com/39769509/89549376-83c0a580-d808-11ea-9b84-64d91bd9bbaf.png)
![image](https://user-images.githubusercontent.com/39769509/89548599-87076180-d807-11ea-9e07-9ef7649b36ba.png)

**Comment by touilleMan** [comment]
related to #1343

**Comment by Max-7** [comment]
The problem is not exactly the same with the new org creation process, but trying to use an org name that's already used leads to incorrect error.

![org-create-error](https://user-images.githubusercontent.com/18075498/92700821-8e161800-f34f-11ea-83c2-b283ce0b2fab.png)
