### ISSUE TITLE
Window is closing when password missmatch when creating an organization

### ISSUE THREAD

**Issue by Sithi5** [Scille/parsec-cloud#1376]
![image](https://user-images.githubusercontent.com/39769509/90522240-c325b500-e16b-11ea-8415-077e88b857dd.png)
![image](https://user-images.githubusercontent.com/39769509/90522268-cb7df000-e16b-11ea-94ba-e35ef19ae410.png)
![image](https://user-images.githubusercontent.com/39769509/90522306-d769b200-e16b-11ea-8ba1-beb14e11cf57.png)

**Comment by Max-7** [comment]
Linked to #1265

**Comment by Max-7** [comment]
Closed by #1375
