### ISSUE TITLE
No user email check when creating organization

### ISSUE THREAD

**Issue by Sithi5** [Scille/parsec-cloud#1377]
![image](https://user-images.githubusercontent.com/39769509/90522535-1ef03e00-e16c-11ea-874a-d7eca7653917.png)
![image](https://user-images.githubusercontent.com/39769509/90522578-2c0d2d00-e16c-11ea-83cc-91d3a6733915.png)

**Comment by Max-7** [comment]
Included in #1375

**Comment by Max-7** [comment]
Closed by #1375
