### ISSUE TITLE
Not matching password cancel the organization creation

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1379]
![image](https://user-images.githubusercontent.com/3187637/90615965-17cd3c80-e20d-11ea-9aed-d7ce125c7169.png)
then closing the dialog make us jump to the login screen:
![image](https://user-images.githubusercontent.com/3187637/90616046-37fcfb80-e20d-11ea-9e5e-824a4158b48a.png)

**Comment by Max-7** [comment]
Dupplicate of #1376
