### ISSUE TITLE
test_workspaces unreliable

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1428]
The test script about workspace is broken. It test the workspace in the GUI with the assumption it starts as unmounted. And this is the opposite. But why does this test pass 90% of the time?
1) At the beginning, it tests `button_open.isEnabled` and should be `not button_open.isEnabled`
2) wait_until right after click actions pass as the values are not yet change during the first testing in waituntil immediately after the click. A small delay after click action is preventing this.
3) the mockup used is participating to pass the tests where everything is inverted in fact

See the modification needed here :
https://github.com/bitlogik/guardata/commit/1a8ee3d2f13b21e9f0f0bd74a1a82cd9c0bec9a9

**Comment by bitlogik** [comment]
Additionally, in the test_workspacefile script, there is a "unawaited" file read, just a warning raised by pytest, not an error issue, as the following command is file close and the test is finished.
https://github.com/bitlogik/guardata/commit/81d9f2fb2e2aa64362b8e123ea9fd7b6e5c070a4

**Comment by AntoineDupre** [comment]
@bitlogik thanks for the report.
Those tests are unreliable and assertions logic can be flipped without having assertion error. This is mainly an issue due to the fact that button are recreated with a default value and that some signals are mocked.
It is fixed now in PR #1477
