### ISSUE TITLE
test_fuse unreliable

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1429]
The test_unmount_with_fusermount test in [the test_fuse script](https://github.com/Scille/parsec-cloud/blob/master/tests/core/mountpoint/test_fuse.py) can fail in the case where the fuse unmount (fusermount -u) is throwing an error at the first call (most probable error is "resource currently in use").

See here a proposal of change :
https://github.com/bitlogik/guardata/commit/53fc04e8bbb1d05d5c9353f708a8f244d0731639#diff-551d9afe2444f8c52dd266bbe1345b22

**Comment by vxgmichel** [comment]
Hm I've never seen this test failing inconsistently, I'm curious about this `resource currently in use` error. I'll wait to encounter this issue in our own CI before implementing the fix you suggest.

Thanks for the report though!
