### ISSUE TITLE
Slow workspace display when big list of users shared with

### ISSUE THREAD

**Issue by Sithi5** [Scille/parsec-cloud#1436]
With 2 workspaces shared with around 250 users in each, it takes more than 10 seconds to have workspace displayed (with postgresql).
![image](https://user-images.githubusercontent.com/39769509/92500942-2dc39100-f1fe-11ea-8bb7-de7ed1e008ca.png)
![image](https://user-images.githubusercontent.com/39769509/92503084-04f0cb00-f201-11ea-9398-2421ad751de7.png)

**Comment by Max-7** [comment]
Made partially better with #1432 but the main problem is probably the `get_user_info()` for each user (https://github.com/Scille/parsec-cloud/blob/master/parsec/core/gui/workspaces_widget.py#L89).
