### ISSUE TITLE
Use "auto_envvar_prefix" click option to automatically support environement variables

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1473]
At the moment, only the backend CLI supports CLI options as environment variables. Those variables are declared using the `envar` argument of `click.option`.

Instead, those variables could be generated automatically by passing `auto_envvar_prefix="PARSEC"` to the script that is invoked:
https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables

We could use `auto_envvar_prefix` to easily and consistently support options as environment variables for the core CLI too.

**Comment by AntoineDupre** [comment]
closed by #1480
