### ISSUE TITLE
exec_ in parsec.core.gui.custom_dialogs.py::show_error() blocking

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#1521]
When using an incorrect invitation URL, the GUI doesn't show up and Parsec crashes on macOS.
This works fine by changing `return d.exec_()` with `return d.show()` in the function.

**Comment by Max-7** [comment]
Solved by https://github.com/Scille/parsec-cloud/commit/b6aad6847c3a2c5ba21063ae64e8279d5948cac7

The exec_ wasn't the root of the problem, that crash was caused by resetting the parent of a dialog.
