### ISSUE TITLE
Backup local keys on an external device (ie USB) ?

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1530]
Provide a function "creation of a backup key" for saving the keys locate from the device :
- on Linux dans : /home/thierry/.config/parsec/devices
- on windows : C:\Users\Thierry\AppData\Roaming\parsec\config\devices
to a external device to store on a secure place.

**Comment by Max-7** [comment]
Discussed between us.

Our worries are that an experienced user will have no trouble making manual backups whereas adding a functionality for that could prove confusing or even dangerous to a novice.

Still, I'm keeping the issue opened.
