### ISSUE TITLE
Importing a big folder in GUI overflow Qt

### ISSUE THREAD

**Issue by Sithi5** [Scille/parsec-cloud#1553]
When trying to import a big folder in the GUI, we get a Qt error. Also, the GUI isn't displaying any error and just do nothing.
It seems there is a problem with the progress bar max size.
![image](https://user-images.githubusercontent.com/39769509/97875565-dd0e7700-1d1a-11eb-9a69-811737ba4dce.png)
![image](https://user-images.githubusercontent.com/39769509/97875589-e7307580-1d1a-11eb-8b9c-b5762cc38a51.png)
![image](https://user-images.githubusercontent.com/39769509/97875609-f0214700-1d1a-11eb-9471-7ad8ee6d4ab3.png)

**Comment by Max-7** [comment]
Seems to be a dupplicate of #1543. Please retry with #1550 to check if it solved the problem.

**Comment by Max-7** [comment]
Closed by #1550
