### ISSUE TITLE
Imossible de créer ou supprimer dans le point de montage du workspace

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#156]
A l'issue de la connexion, lorsque l'on navigue dans le point de montage, il est impossible de créer ou de copier un répertoire. De même la suppression est impossible. #

**Comment by touilleMan** [comment]
Solution: rendre le répertoire racine en read-only

**Comment by touilleMan** [comment]
cf. #212

**Comment by touilleMan** [comment]
fixed by #212
