### ISSUE TITLE
Improve MacOS "macosxfuse is not available" error message in gui

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1565]
currently the link to macosxfuse website cannot be clicked, it would be better to display a "install osxfuse" button to directly redirect to the website

**Comment by bitlogik** [comment]
Our solution to this issue
https://github.com/bitlogik/guardata/commit/4d303906041b01ba9f62c656a95771820f9c9d92

**Comment by Ironicbay** [comment]
@bitlogik It works nicely indeed. Thanks !
