### ISSUE TITLE
GUI keeps reloading (causing blinking and unselecting) when importing/renaming/deleting files

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#1567]

**Comment by bitlogik** [comment]
Is the in-progress PR #1571 a solution, or can help about this issue ?

**Comment by Max-7** [comment]
Yes, it will help. Currently we update the whole file list everytime there's a change in a any file. The goal is to update just the specific file, using the information given with the event FS_ENTRY_UPDATED.

**Comment by Max-7** [comment]
Fixed.
