### ISSUE TITLE
Mac Big Sur compatibility

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1575]
Not 100% sure if parsec original is affected, but the current software might not run on Mac OS 11.x. We downgraded the QT version to 5.13.1 on MacOS so that it can run on Mac OS 11. This is not yet tested on ARM architecture.
Here's our change to allow a window opening in Big Sur (else it can't start the GUI at all).
https://github.com/bitlogik/guardata/commit/a55d0d98a1776b2ba6699f5cdbd750f7b9d15078

**Comment by bitlogik** [comment]
AS an additional note on this matter, we recommend the use of the latest osxfuse version (3.11.2). And one major change about MacOS 11 is that it now requires a reboot of the system before loading external kernel module, such as osxFUSE (which was not required on Mac 10.x). So this change the instructions to the user on how to install osxfuse, as it requires an additional step with Big Sur. See [more info here]( https://github.com/osxfuse/osxfuse/issues/740), where the leading developer tells he can't avoid a reboot.

**Comment by touilleMan** [comment]
thanks 👍
