### ISSUE TITLE
Missing dependency in pip

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1576]
Using "pip3 install parsec-cloud", the gui can't be started because psutil is missing (_No module named 'psutil'_ during import). The psutil package is only listed as "extra equirements" but should be listed in the standard requirements for the parsec client.

**Comment by touilleMan** [comment]
The GUI is only available when installing `core` extra requirement. As a matter of fact, this is a poor naming, it should be called `desktop` instead.
Installing no extra requirement means we only want the vital parts of parsec, for instance to package it for mobile platforms.
