### ISSUE TITLE
GUI freezes in some Linux

### ISSUE THREAD

**Issue by bitlogik** [Scille/parsec-cloud#1578]
The Qt GUI sometimes blocks and freezes on some Linux platforms. The window hangs and the only way to close the window is to click on the window close cross and wait for the system "not responding" and select Force Quit (also CTRL+C in the terminal or kill).

To trigger it, run many times (something like 1 over 20 tests is blocking for ever) :
`python3 -m pytest -x tests/core/gui/test_files.py::test_cut_files -runmountpoint --runslow --rungui -m gui -v`
If starting a full gui test with all the tests, there is a high probability the issue happens as there are hundreds of tests, so one will be face this and will freeze forever the GUI window.
It also happens outside of pytest, when we "manually" use the GUI core GUI.

Affected systems are Ubuntu 20.04 (Python38) and Ubuntu 18.04 (Python36), but we didn't reproduced that issue on a physical computer nor a local VM, it was only present on a remote machine through RDP, using the X11 windowing system instead of the modern wayland.

We did the following without any success trying to solve this issue :
* downgrade pyQt to 5.13.0, 5.13.1 and 5.13.2
* upgrade pyQt to 5.15.1
* add many QCoreApplication.processEvents() in the code, maybe we missed a keypoint or the required one was QApplication

The possible root causes can be :
* An issue with Qt5 and x11
* A mishandling of Qt5 GUI, like missing .processEvents()
* An issue with threading or trio (deadlock, lost thread,...)

**Comment by touilleMan** [comment]
Too old
