### ISSUE TITLE
Show organization last usage time in back-end data clip

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#1584]
Our current data clip (heroku) for showing created organizations does not capture the last usage time and thus preventing us to know which organizations are actually using the system.

**Comment by stefan-contiu** [comment]
Can we add the IP address used for creating the organization?

**Comment by touilleMan** [comment]
IP address might be a good idea (given it should be pretty straightforward to implement), but I'm wondering if Parsec should instead just output a log and leave the rest to an analytics tools (typically [ELK stack](https://www.elastic.co/fr/what-is/elk-stack))

pros:
- dead simple
- dedicated tools such as ELK allow much better view on analytics

cons:
- cannot provide those stats from within Parsec

My position here is we should leave the analytics to ELK and only add into Parsec database what is actually needed by the application.
For instance we should store the device last connection time in the database if we want to display this information, and we should store it as a single value and not as a history of all the connections that occurred (which is something that would be left to the analytics)

@Max-7 @AntoineDupre  any idea ?

**Comment by touilleMan** [comment]
Too old
