### ISSUE TITLE
Run core without core extra requirements installed

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1587]
Currently there is two flavors of extra requirements:
- backend that should be installed to run the Parsec server
- core that should be installed to run the Parsec client

However the core extra requirements is only needed when running Parsec client on the desktop: it contains Qt, i18n and fuse/winfsp stuff, all of which is not strictly needed for running the actual "core" of Parsec.

This was fine so far but now that we want to provide Parsec on mobile we want to be able to install the bare minimum to run Parsec core.

**Comment by touilleMan** [comment]
We could rename the extra requirements to make them more understandable, core and backend are some silly historical names at this point and I think we could replace them by `desktop` and `server`

This way pip install would become much more readable I think:
```shell
$ pip install parsec  # install the actual "core", i.e. the bare minimum needed to have a parsec client
$ pip install parsec[desktop]
$ pip install parsec[server]
```

**Comment by FirelightFlagboy** [comment]
The `core` exist no more, I'm closing this issue
