### ISSUE TITLE
enrolement user

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#159]
Le process d'enrolement me smeble assez complexe 
il faut passer 3 infos ( pseudo, token , URL ) et être en simultané avec l'enrolé 
comment peut on simplifier ( j'imagine que le token fait partie d'un process de double authentification , mai quid du pseudo et de l'URL?
et pourquoi faut il être en simultané ?

**Comment by touilleMan** [comment]
Discution de slack sur le sujet:

@Serge DUBRANA @pepere concernant possibilité de simplification du système d’enrôlement dont on parlait l'autre jour, voici comment fait matrix (protocole de open source de communication instantané sur lequel se base riot, qui est grosso modo un slack décentralisé avec un chiffrement fort côté client)

comme le système est décentralisé, un utilisateur peut choisir sur quel "home server" il veut se connecter. Au niveau de l'ergonomie c'est assez bien fait car le client est configuré pour utiliser un home server par défaut et propose un bouton d'option avancé pour configurer cela.

Pasted image at 2019-02-08, 8:02 AM 

Pasted image at 2019-02-08, 8:02 AM

Pasted image at 2019-02-08, 8:02 AM 

Pasted image at 2019-02-08, 8:02 AM

touilleman [08:17]

si on compare à Parsec, on peut dresser un parallèle entre le "home server" de matrix et l'organisation de Parsec, toutefois c'est plus délicat de notre côté:

- le "home server" est quelque chose de purement technique (en effet Alice sur le home server 1 pourra communiquer avec Bob sur le home serveur 2) alors que les organisations sont des mécanismes de cloisenement (Alice sur organisation 1 est totalement indépendent de Bob sur organisation 2)

- du coup il n'y a pas de valeur par défaut pour l'organisation

- en plus de cela, l'organisation est définie par un nom ET une clé publique (qui est du style `RMyd6zhlbifsACM1DXkCbioZ2u0SywGljTH8JmGcylg`, donc totalement imbitable pour l'utilisateur...)

- dans le client parsec, en plus de l'organization, on doit renseigner l'adresse de server de métadonnées. Ici on pourrait fournir une valeur par défaut (qui serait l'adresse sur serveur SAAS de parsec) mais on ne gagne pas grand chose car cette info est actuellement passée avec l'organisation (on passerait de `ws://saas.parsec.cloud/org42?rvk=RMyd6zhlbifsACM1DXkCbioZ2u0SywGljTH8JmGcylg` à `org42?rvk=RMyd6zhlbifsACM1DXkCbioZ2u0SywGljTH8JmGcylg` ce qui est tout aussi abscon)Bref de ce côté je ne pense pas qu'on puisse faire grand chose de ce côté

touilleman [08:29]

Un autre point intéressant sur matrix est comment ils gère la vérification des clés de sécurité des utilisateurs (https://matrix.org/docs/spec/client_server/r0.4.0.html#device-verification)

En gros c'est le boxon:

Pasted image at 2019-02-08, 8:29 AM 

Pasted image at 2019-02-08, 8:29 AM

quand on créé un nouvel utilisateur, celui-ci upload sa clé publique de device sans qu'il ne lui soit rien demandé. (edited) 

par la suite un autre utilisateur peut procéder à la vérification du device en contactant le premier utilisateur et en comparant à la main les clés affichées sur leur client réciproque

touilleman [08:45]

les choses sont assez complexe car la vérification doit être fait pour chaque device depuis chaque device (donc si alice est connéctée sur pc1 et pc2 et Bob sur pc3, pc1 doit vérifier pc2 et pc3, pc2 doit vérifier pc1 et pc3 et pc3 doit vérifier pc1 et pc2...)

Bref c'est un système qui n'est pas encore au point (ils disent qu'ils sont en beta sur le chiffrement), et d'ailleurs il n'est pas activé par défaut

par contre ce qui m'a pas mal intéressé c'est ça :

Pasted image at 2019-02-08, 8:45 AM 

Pasted image at 2019-02-08, 8:45 AM

touilleman [09:00]

je me demande si on ne pourrai pas faire un système un peut similaire dans Parsec: Plutôt que de devoir passer le token via un canal sécurisé, on pourrait tout simplement afficher sur les deux clients (celui du nouvel utilisateur et celui de l'utilisateur l'ayant invité) la clé de sécuritéL'avantage étant qu'on supprime le passage du token (il n'y a donc plus que l'url du style `ws://saas.parsec.cloud/org42?rvk=RMyd6zhlbifsACM1DXkCbioZ2u0SywGljTH8JmGcylg&user_id=bob` à passer par un canal n'ayant pas besoin d'être sécurisé) et que la phase de vérification est très explicite:côté utilisateur existant:

- on clique sur "inviter utilisateur", une page avec juste un champ "nom d'utilisateur" s'ouvre

- une fois renseignée la page est remplacé par une autre contenant l'url `ws://saas.parsec.cloud/org42?rvk=RMyd6zhlbifsACM1DXkCbioZ2u0SywGljTH8JmGcylg&user_id=bob` ainsi qu'un texte expliquant qu'il faut passer ça au nouvel utilisateur

- une fois que le nouvel utilisateur s'est manifesté, la page est remplacé par une nouvelle affichant la clé publique reçu et demandant si il s'agit de la bonne (avec deux bouton "valider" et "annuler")côté nouvel utilisateur:

- on clique sur "nouvel utilisateur", une page avec juste un champ "url" s'ouvre

- on rempli l'url dans un champ et clique sur suivant

- la page est remplacée par une nouvelle affichant la clé publique et expliquant qu'il faut la comparer avec ce qu'a reçu l'utilisateur nous ayant invité

- une fois que l'utilisateur ayant invité a valider ou annuler notre enrolement, la page est remplacé par une dernière indiquant le résultat@nicotux et @max pour savoir ce qu'ils en pensent
