### ISSUE TITLE
organisation

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#160]
du point de vue de l'utilisateur , pourquoi avoir besoin de créer une organisation ? la bulle de confiance est au niveau du workspace si j'ai compris , donc à quoi l'organisation peut elle servir , encore une fois vue du user et pas de nous  ?

**Comment by Max-7** [comment]
Y'a trois raisons qui me viennent immédiatement a l'esprit, mais il y en a sûrement d'autres:
- ça permet d'avoir un administrateur par groupe d'utilisateur. C'est cet administrateur qui peut ensuite créer les comptes utilisateurs, ou potentiellement les révoquer.
- ça permet de séparer les noms d'utilisateurs. Si deux utilisateurs de deux entreprises différentes veulent s'appeler "Max", sans l'organisation ce n'est pas possible car ce nom sera déja utilisé.
- ça masque les utilisateurs d'un autre groupe. Du coup on ne peut voir que les utilisateurs de son organisation (ça évite les erreurs de partage par exemple).
