### ISSUE TITLE
Function  "abandon enlistment"

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1622]
It would be great to have a button "abandon enlistment". 
 
![image](https://user-images.githubusercontent.com/9845177/104543963-fd19bb00-5626-11eb-8e5a-f2cc4b7f6ca3.png)

**Comment by Max-7** [comment]
That's what the red button is for.

**Comment by tleblond** [comment]
Le fait que je n'ai pas vu le "sens interdit" montre que ce n'est pas très intuitif. Peut-on mettre en bas deux boutons : A gauche en bleu "Accueillir" et à droite en rouge "Abanbonner" (on peut laisser le sens interdit car qui peut le plus peut le moins).

**Comment by Max-7** [comment]
![invitation](https://user-images.githubusercontent.com/18075498/162713712-4551744c-f687-4ed0-bcb5-6ebf4aff46c8.png)
We've updated how invitations look.
