### ISSUE TITLE
Function "restore file"

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#1623]
Il peut arriver que l'on supprime un très gros fichier par erreur. Dans ce cas, pour le récupérer, on ouvre un historique de l'enclave et on le récupère en faisant un copier-coller. Ce n'est pas très économique en terme de stockage. Peut-on imaginer lors d'un clic droit sur le fichier ajouter une fonction restaurer qui demande la localisation de la restauration du fichier ?

It can happen that a very large file is deleted by mistake. In this case, in order to recover it, we open the history of the enclave and we recover it by making a copy-paste. This is not very economical in terms of storage. Can we imagine when right-clicking on the file to add a restore function that asks for the location of the file restoration?

**Comment by mmmarcos** [comment]
This will be implemented in #6147
