### ISSUE TITLE
Trademark Parsec & Scille on headers

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#163]
Recommendation R13 of the january 2018 Scille strategy committee :

> A code branding strategy should be implemented by incorporating the Scille company name into the commits.

Each file pushed by a Scille member on the `parsec-cloud` repository must have a header specifying the name of the **Parsec trademark** and **the name of the company Scille** author of the commit.

**Comment by touilleMan** [comment]
closed by #175
