### ISSUE TITLE
Text flickers when opening file from GUI

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#1630]
![Jan-29-2021 15-47-55](https://user-images.githubusercontent.com/41511029/106289336-76312900-6249-11eb-9b02-6bf588c405b3.gif)

**Comment by Ironicbay** [comment]
The same behaviour occurs when opening the same files from the Finder.

**Comment by touilleMan** [comment]
related to #1582

**Comment by touilleMan** [comment]
duplication of #1567
