### ISSUE TITLE
Licensing Affero GPL on headers

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#164]
Recommendation R16 of the january 2018 Scille strategy committee : 

> choose  a free license "Affero GPL" for the free platform of the software (kernel) and a private license for differentiating modules that can bring a high value to large accounts.

Each file pushed on the `parsec-cloud` repository must have a header specifying the applicable license **Affero Gnu Public License v3 (AGPL v3)**.

**Comment by touilleMan** [comment]
duplicate https://github.com/Scille/parsec-cloud/issues/163
