### ISSUE TITLE
Do not display workspaces if the corresponding workspace manifest is not available

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1664]
It's confusing for the user to be displayed with a workspace they can barely interact with.

That happens when:
- the user logs in while offline
- AND their user manifests knows about a new workspace
- BUT the workspace manifest has not been downloaded yet

In this case it's better to not display the workspace at all and wait for the user to get back online and download the workspace manifest.

**Comment by touilleMan** [comment]
Speculative manifests solve this issue in a much better way
