### ISSUE TITLE
CalledProcessErrors in MacOS cleanup function

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#1714]
See #1704 

Due to the `auto_unmount` option missing on Mac, unmounting can be incomplete in case of the application crashing or not being properly closed.

The cleanup function was implemented to address this issue and empty the mountpoint folder, but the unmount calls inside can crash.

TODO : replicate the issue locally and uncover its mysteries

**Comment by FirelightFlagboy** [comment]
The new mountpoint system on `parsec v3` don't use the `auto_unmount` feature currently
