### ISSUE TITLE
Parsec logo doesn't show on invitation emails sent by the backend

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1770]
https://github.com/Scille/parsec-cloud/blob/702fc5fd90a95644b07e7941d6a9acab952df4c9/parsec/backend/templates/invitation_mail.html#L358

This link appears to be broken: https://www.parsec.cloud/parsec-new.png

**Comment by touilleMan** [comment]
The https://www.parsec.cloud/parsec-new.png is now fixed

However emails sent from Parsec server should rely on themselves (i.e. the logo in the email should be hosted by the Parsec server and not by the main parsec.cloud website)
