### ISSUE TITLE
Workspace history date font display is white on white

### ISSUE THREAD

**Issue by Delantonio** [Scille/parsec-cloud#1845]
When launching parsec client in command line

![image](https://user-images.githubusercontent.com/47568430/132859737-24a37dc7-5fe4-44b2-b3da-b1e13ce42b33.png)

![image](https://user-images.githubusercontent.com/47568430/132859832-f050c3ad-4314-44cf-bb2b-560c9da31976.png)

**Comment by Max-7** [comment]
Days do not display properly either, you should have "lun. mar. mer. etc...", not just sam. and dim. They're probably displayed as white on white. But this might be hard to fix given that the calendar widget is a made up widget composed from different widgets, it does not have proper styling in itself.
