### ISSUE TITLE
Add timeout support for GUI when calling the core

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#1875]
In trio timeout should be handle by caller using a `with trio.move_on_after(timeout):` block

However currently the GUI doesn't use timeout at all, meaning we rely on the kernel to trigger timeout when sending request to the backend. However kernel timeout on TCP can make us wait really really long (~30s on desktop, and a loooot more on Android !)

Maybe we should add a timeout handling directly in the core to avoid cluttering the GUI with the `trio.move_on_after` blocks...

**Comment by FirelightFlagboy** [comment]
Thie python gui was removed, closing this issue
