### ISSUE TITLE
Set&enforce limits for Organization

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#192]
Should provide an API to allow set:
- max users
- max data

**Comment by stefan-contiu** [comment]
This issue has been validated upon the discussion on the tarrification. The _individual_ plan requires a hard limit on the data while the _team_ plan requires a hard limit on number of users within an organization.

**Comment by stefan-contiu** [comment]
Should be implemented once the tarification changes are available in the site marchand.

**Comment by c4ffein** [comment]
Closed as we don't need this for now using our merchant system implementation
