### ISSUE TITLE
Inconsistent data generation on test_sync_monitor_stateful

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#1951]
https://dev.azure.com/Scille/parsec/_build/results?buildId=8317&view=logs&jobId=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=ed095f08-b949-549a-bd29-bb167da12587
```
test_sync_monitor_stateful
E hypothesis.errors.Flaky: Inconsistent data generation! Data generation behaved differently between different runs. Is your data generation depending on external state?
You can add @seed(21406537388784977495047167082191333860) to this test or run pytest with --hypothesis-seed=21406537388784977495047167082191333860 to reproduce this failure.
```

**Comment by touilleMan** [comment]
https://dev.azure.com/Scille/parsec/_build/results?buildId=11228&view=logs&j=5ba45810-c0e9-5996-abe7-b2cb0c9b6baa&t=ed095f08-b949-549a-bd29-bb167da12587&l=57
```
