### ISSUE TITLE
perte du point de montage

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#208]
je perds le point aleatoirement 
il se remet qd je me relogge

![capture d ecran 2019-02-20 17 19 55](https://user-images.githubusercontent.com/46708918/53106676-d4204680-3533-11e9-99a5-d2bbd1eccc61.png)

sur l'exemple le fichier psf cryptobox n'a pas été chargé alors que les précédents oui

ou sinon vu dans les messages

![capture d ecran 2019-02-20 19 23 07](https://user-images.githubusercontent.com/46708918/53116913-0f2d7480-354a-11e9-8cd3-92e792ada631.png)

**Comment by Max-7** [comment]
See #236
