### ISSUE TITLE
Message d'alerte Norton à l'installation de Parsec

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#2084]
Un nouvel utilisateur sur Windows ayant l'antivirus Norton m'informe que message d'alerte ci-dessous :
A new user on Windows with Norton antivirus informs me that the following alert message appears:
![image](https://user-images.githubusercontent.com/9845177/158654990-62114cae-2aeb-4f00-a4ce-2c1f64fdc2d9.png)
Or nous payons un abonnement à Microsoft pour garantir la qualité de notre code Parsec. 
Est-il possible d'entreprendre une action auprès de Microsoft dans le cadre de notre contrat pour que le logiciel Parsec soit considéré comme une application de confiance par les éditeurs d'antivirus ?

We pay a subscription fee to Microsoft to guarantee the quality of our Parsec code. 
Is it possible to take action with Microsoft in the framework of our contract so that the Parsec software is considered as a trusted application by the antivirus editors?

**Comment by mmmarcos** [comment]
This seem outdated. We'll reopen if the issue is still present.
