### ISSUE TITLE
pb lors de l'enrolement de Philippe

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#209]
![capture d ecran 2019-02-20 19 17 25](https://user-images.githubusercontent.com/46708918/53116960-266c6200-354a-11e9-883c-65df555352db.png)

user Philippe non créé suite à ce message 

on a créé Philippe1 qui a marché

par contre qd j'essaye de recreer un Philippe , le systeme me dit qu'il existe deja , mais je ne le vois pas

![capture d ecran 2019-02-20 19 23 07](https://user-images.githubusercontent.com/46708918/53117061-561b6a00-354a-11e9-8e3c-0cf159bb1c61.png)

**Comment by Max-7** [comment]
Fixed with the new invitation system (#1158), closing the issue.
