### ISSUE TITLE
apparition de code Python

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#210]
![capture d ecran 2019-02-20 19 46 06](https://user-images.githubusercontent.com/46708918/53117123-76e3bf80-354a-11e9-9c10-dbda733c4e31.png)

**Comment by Max-7** [comment]
Lié au fait que dans local_folder_fs.py:302, l'event fs.entry.updated est envoyé avec juste un id, alors qu'il requiert également un path.

**Comment by touilleMan** [comment]
Ce type de crash provient d'une erreur dans le point de montage windows. C'est un type d'erreur assez bas niveau (ce qui fait qu'on ne peut pas facilement récupérer cette erreur et qu'elle finit affiché à l'utilisateur)

Bref c'est le bon reflexe quand une erreur comme ça arrive de faire une copie d'écran et de fournir le context ayant conduit à celle-ci ;-)

**Comment by touilleMan** [comment]
Après investigation il s'agit d'un bug dans le nettoyage des callback d'event en weakref.
Fixé par fdfd3b42d04327c3481be5e4b47b3e87647e1084 qui supprime totalement les callbacks en weakref
