### ISSUE TITLE
workspace en double 

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#211]
Philippe a mis a jour le WS avocats dubrana avec des documents : on les retrouve en doucle dans le WS  Bureau Fred sans que personne n'y touch et sans qu'il ait ete partage avec philippe

![capture d ecran 2019-02-20 19 53 47](https://user-images.githubusercontent.com/46708918/53117207-adb9d580-354a-11e9-8e49-97d8788deb7c.png)

**Comment by touilleMan** [comment]
sur la capture d'écran les modifications dans `Bureau Fred` sont directement répercutées dans `Projet Fusac interne`.  Probablement un problème lors du renommage des workspace.

**Comment by touilleMan** [comment]
à retester une fois #259 mergé
