### ISSUE TITLE
Treat each workspace as a separate mount point, controlled independently

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#212]
After a discussion with @touilleMan, the following proposal is submitted to the team (feel free to edit this comment to add more information):

## Treat each workspace as a separate mount point, controlled independently

A workspace would no longer be treated as a directory at the root of the mount point, but as a mount point itself. Conceptually, this seems to be a better fit than the current design, which feels a bit clumsy.

### Pros

- Greatly simplify filesystem logic as in many places, workspaces are treated very differently than regular folders:
  * Manifests are not recursively copied when a workspace is renamed.
  * It is not possible to create a file or a folder at the root of the mountpoint.
  * And more:
    ```console
    $ git grep workspace_manifest parsec/core/fs
    parsec/core/fs/local_folder_fs.py:                if is_workspace_manifest(child_manifest):
    parsec/core/fs/local_folder_fs.py:        if is_workspace_manifest(manifest):
    parsec/core/fs/local_folder_fs.py:        elif is_workspace_manifest(manifest):
    parsec/core/fs/local_folder_fs.py:        if not is_workspace_manifest(src_manifest):
    parsec/core/fs/local_folder_fs.py:            if is_workspace_manifest(src_ro_manifest):
    parsec/core/fs/local_folder_fs.py:            if is_workspace_manifest(src_manifest):
    parsec/core/fs/local_folder_fs.py:            if is_workspace_manifest(src_manifest):
    ```
- Solve existing issues with the current implementation of the file system module:
  * Issue #206 only happens when workspaces are involved.
  * Moving a folder from a workspace to another should copy the corresponding blocks (see [this comment](https://github.com/Scille/parsec-cloud/issues/120#issuecomment-465519751)). This issue is currently not trivial to solve, because the move operation might require the downloading of many blocks not present on the system. With independent mount points, this move operation simply disappears: the OS takes care of it by recursively copying the files (i.e. reading and writing their content) from one mount point to the other before removing the source.
  

### Cons

- Require a lot of refactoring on the core side
  * Each workspace gets its own mountpoint manager and filesystem manager.
  * The API is also going to change since workspace-specific functions have to be moved.
- Require new features in the GUI:
  * Each workspace/mountpoint has to be controlled independently.
  * The current status of each mountpoint has to be displayed.
- Require a lot of changes in the test modules, obviously.

### Questions

- Is having many mount points mounted and displayed in the file manager a problem:
  * from the user experience point of view?
  * from the technical point of view (i.e. technical limitation)?

**Comment by touilleMan** [comment]
Two other pros I see:

1
-
Displaying history is more straightforward given we could mount another mountpoint to display the history, example:
- you start with only`workspace42` mountpoint
- you enable history mode by right clicking on the workspace in the parsec gui
- a new mountpoint `workspace42-history` appears, it is mounted in read-only
- you can easily compare both mountpoints ;-)

2
-
User manifest in mountpoint is weird for user given he cannot create file&folder (but can modify within the folders...), especially during first use when the user hasn't created any workspaces.
We though about allowing the user to create folders in the root (which would be translated into workspace creation by fuse) but it's even worst given user see he can create folder but not files !

**Comment by touilleMan** [comment]
Considering the cons:

> * Require a lot of refactoring on the core side

> * Require a lot of changes in the test modules, obviously.

I agree cleaning up the whole internal API is a big job (too big to deal with before the v1.0 deadline). However internal API can be kept (it's... internal after all ^^) for the moment and we would only change the mountpoint manager to provide a API to start/stop mountpoints on given workspaces.

This seems to me a lot more doable (given we need to do something like that anyway to implement the history system)
