### ISSUE TITLE
[GUI] Disable notification for on line / off line events

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#213]
Quand on passe de online à offline, plutôt que de spammer le bouton "cloche" avec des notifications très nombreuses, il serait plus ergonomique de passer l'icone en bleu pour "on line" et en grisé pour "off line". Ce serait immédiatement visible et ne produirait pas de notification sans intérêt pour l'utilisateur

**Comment by Max-7** [comment]
J'ai limité les notifications au moment de la connexion, on ne devrait plus avoir de notifications inutiles.
