### ISSUE TITLE
[GUI] Le bouton "partager" ne fonctionne pas

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#214]
**Version v0.9.2.176-g6c38478**. Quand on essaie de partager un Workspace, on arrive à sélectionner un user mais quand on clique sur Partager, il ne se passe rien. Il semble que le bouton ne permette pas de communiquer avec le backend.

**Comment by Max-7** [comment]
Possiblement fixé par https://github.com/Scille/parsec-cloud/commit/612866ec77d2f8f3e2c922e73fa32b97c33090d8.

Je laisse l'issue open en attendant une confirmation.
