### ISSUE TITLE
Force a password according to the recommendations of the ANSSI

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#215]
It must not be possible for a user to choose a password that does not comply with ANSSI's recommendations at the following address: https://www.ssi.gouv.fr/administration/precautions-elementaires/calculer-la-force-dun-mot-de-passe/.
We make the choice to impose a password of 16 characters in an alphabet of 36 symbols (size of equivalent key 82) considered by the ANSSI of average strength and which is a size recommended by the ANSSI for passwords safer

**Comment by c4ffein** [comment]
We already use a common secure library for password checks
