### ISSUE TITLE
Better handling async qt callback

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#2157]
The following pattern is used several times in the code base:
```python
    def _goto_page3(self):
        [...]
        page.succeeded.connect(self._on_finished)
        [...]

    def _on_finished(self, new_device, auth_method, password):
        self.jobs_ctx.submit_job(
            None, None, self._on_finished_async, new_device, auth_method, password
        )

    async def _on_finished_async(self, new_device, auth_method, password):
        [...]
```

Not having a success nor an error signal for those jobs is not a problem, as qt callbacks are not meant to return a value nor raise an exception. We simply want to make sure that an exception in the callback (being sync or async) is reported in a similar way in the logs.

This pattern can be factorized in several different ways:
```python
    # 1. With a decorator
    @async_qt_callback
    async def _on_finished(self, *args):
        [...]

    # 2. With a specific connector
    def _goto_page3(self):
        [...]
        connect_to_async_slot(page.succeeded.connect, self._on_finished)
        [...]

    # 3. By patching Qt signals automatically run a job if the slot is async
    def _goto_page3(self):
        [...]
        page.succeeded.connect(self._on_finished)
        [...]

    async def _on_finished(self, new_device, auth_method, password):
        [...]
```

Solution 1 is simple to implement but the exposed `_on_finished()` method is actually synchronous which can be confusing (it cannot be called directly from another coroutine, although it could be exposed as `self._on_finished.async_target`).

The solutions 2 and 3 are more tricky to implement as Qt requires the slot to be an actual method of the object (and not a wrapper function).

**Comment by Max-7** [comment]
Done by #2172
