### ISSUE TITLE
perte point de montage

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#227]
depuis plusieurs jours pas moyen de retrouver mes fichiers 

AVANT 
![capture d ecran 2019-02-22 13 47 54](https://user-images.githubusercontent.com/46708918/53574931-dfe1bd80-3b70-11e9-801b-773100414ad5.png)

MAINTENANT
![capture d ecran 2019-02-28 15 53 41](https://user-images.githubusercontent.com/46708918/53575047-0c95d500-3b71-11e9-8d0d-1bacd6be171d.png)

**Comment by frossigneux** [comment]
Il est fort probable que cela soit causé par la réinitialisation de la base côté backend.
Idéalement il faudrait un message d'erreur adéquat lors de la connexion.
