### ISSUE TITLE
[🐛 | Bug]: Can only create bug report

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2294]
### Version

Not related

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

I can only create bug report as issue

### Relevant output

N/A

**Comment by touilleMan** [comment]
![image](https://user-images.githubusercontent.com/3187637/168700773-02c7e86e-8e94-4755-adf5-94e8f8d9b61a.png)
