### ISSUE TITLE
[🐛 | Bug]: File saving not working as intended with Xcode

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#2330]
### Version

2.9.0

### What platforms you were running our software when the bug happened ?

MacOS

### What happened ?

Can't save a file through XCode when editing it directly from a Parsec workspace, getting message `The document xxx could not be saved`.

For the file `filename.extension`, the file `filename-.extension` is created in the workspace, and the original get deleted. Its content is the same as the original file. So three issues:

- Original file is deleted, and with it its creation date and history
- New file has to be renamed to replace original
- Changes can't be saved, and auto-save messes up editing with pop-up messages telling it can't save

This could be related to #2211, and interestingly hasn't been fixed by it.

**Comment by FirelightFlagboy** [comment]
Fixed in #4198
