### ISSUE TITLE
Suggestion amélioration ergonomique

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#234]
1. Se voir soi-même dans les utilisateurs partageant un workspace 
2. Divers problèmes de dimensionnement de fenêtres.

![image](https://user-images.githubusercontent.com/13103240/53559774-320fe800-3b4b-11e9-9a5f-d6698554be6c.png)

**Comment by Max-7** [comment]
Divided between #253 and #252
