### ISSUE TITLE
Windows: message d'erreur de démontage intempestif

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#236]
![image](https://user-images.githubusercontent.com/13103240/53559653-e2312100-3b4a-11e9-9913-b2c991fd2e10.png)

**Comment by Max-7** [comment]
Linked to #245.

**Comment by Max-7** [comment]
Linked to #208.

**Comment by c4ffein** [comment]
Closed as we switched to a completly new workspace system.
