### ISSUE TITLE
Windows: suggestion amélioration nom de machine par défaut

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#238]
1. Affichage par défaut : Nom de l’appareil « windows ».
Afficher plutot le nom reseau du PC.

2. Pour moi, le nom du PC est  DELL-PHIL . Le tiret n’est pas supporté et est éliminé (-> DELLPHIL).
![image](https://user-images.githubusercontent.com/13103240/53559521-8ff00000-3b4a-11e9-9fca-5683afb6ee4e.png)

**Comment by Max-7** [comment]
Utilisation du host name si différent de "localhost", sinon on continue d'utiliser le nom de l'OS (https://github.com/Scille/parsec-cloud/commit/6868b34baa0333f2ca55372f5b95584df250cf84).

Les caracteres non-alphanumériques ne sont pas supportés.
