### ISSUE TITLE
Windows: affichage : Fenetre « nouvel utilisateur » : en haut manque une ligne + faute orthographe

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#239]
Screenshot
![image](https://user-images.githubusercontent.com/13103240/53559229-ffb1bb00-3b49-11e9-8e62-810afc98a172.png)

**Comment by Max-7** [comment]
Fixed dans https://github.com/Scille/parsec-cloud/commit/6ee30e4c0a090d5ec645700b9f85ef3c22514e9e et https://github.com/Scille/parsec-cloud/commit/886480f95b089e041fe03642262e4adbc10cf853
