### ISSUE TITLE
Windows: paramètres. Point de montage : case « activer » non cochée ni cochable

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#240]
cf screenshot
![image](https://user-images.githubusercontent.com/13103240/53559099-afd2f400-3b49-11e9-86ef-7b1036f38160.png)

**Comment by Max-7** [comment]
Exact, c'était désactivé sur Windows par défaut quand on avait pas le point de montage. À corriger.

**Comment by Max-7** [comment]
Removed mountpoint configuration entirely (https://github.com/Scille/parsec-cloud/commit/59c3df5563e73afcb9d02e4236f124763bc9955b).
