### ISSUE TITLE
[🐛 | Bug]: Quadratic slowdown in GUI when opening big folders

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2411]
### Version

2.8.0+

### What platforms you were running our software when the bug happened ?

Windows

### What happened ?

On Windows, the folder view in the GUI is very slow to display big folder.
- it is not a network issue as the slow down is the same when going backward and re-entering the folder
- ~the issue is not present on Linux (tested with Parsec 2.9.2 on Ubuntu 20.04)~ edit: issue can be reproduced on Linux with a 4K screen (see comment below)
- ~the issue might be related to the `ItemDelegate.paint` (I've done some profiling and this part is called a lot, see screenshot)~ edit: removing `ItemDelegate` doesn't fix the slowdown, on the other hand using dummy data with `ItemDelegate` is instantaneous, so issue seems to come from scheduling the trio async function responsible for fetching the data

![image](https://user-images.githubusercontent.com/3187637/171478479-dbebf3e0-5823-4d72-9fc2-54f1c6828bdc.png)

**Comment by vxgmichel** [comment]
Happens on Linux too, with 4K full screen

**Comment by vxgmichel** [comment]
Here's an explanation of the issue:

The spinner is displayed on top of the files widget using a `QGridLayout`, which allows to stack several widgets on top of one another. The spinner being updated 30 times per second, it causes the whole files widget to also be updated 30 times per second (through transparency). 

On 4K screen, this files widget can be quite big, which increases the time it takes to render it. Everything goes smoothly as long as the rendering time is below 33 ms. If the rendering time is higher than that, then the main thread takes 100% of the CPU and right after the rendering of the frame is done, a new one is scheduled. That means that very few trio callbacks will be able to run in between frames (probably a single one).It's likely that a single call to the local database will be able to run between frames which causes the loading of the new file list to take several frames per file.

#2425 fixes this issue by not having the spinner on top of the files widget, so the rendering time does not increase with the size of the window.
