### ISSUE TITLE
Windows: bug sur la création d'un premier utilisateur = blocage

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#243]
Invitation de Serge -> Philippe. Terminé en blocage (cf bouton gris du Screenshot). Nécessité de tuer le process Parsec. A noter que l'utilisateur aborté Philippe a été créé en zombie : impossible de créer ultérieurement cet usilisateur Philippe (essai suivant: Philippe1).
Cf scrrenshot.
![image](https://user-images.githubusercontent.com/13103240/53558923-5074e400-3b49-11e9-8bb6-caa17b872263.png)

**Comment by Max-7** [comment]
Dans ce cas là il est nécessaire de cliquer sur Annuler, mais c'est pas forcément explicite. Voir si c'est pas mieux d'ouvrir une fenêtre au-dessus pour ajouter de la clarté.

**Comment by Max-7** [comment]
https://github.com/Scille/parsec-cloud/commit/8723ed595dba43b59b6c92b6dbfa1550cf2d5f1d adds a dialog window to better show the cancel button.
