### ISSUE TITLE
Sequester feature

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2462]
Umbrella issue

## Architecture

- [x] #2463 TODO
- [x] #2461
- [x] #2464 TODO

### Organization bootstrap evolutions

- [x] #2468
- [x] #2467
- [x] #2469

### Sequester services lifecycle

- [x] #2470
- [x] #2471
- [x] #2472

### Data synchro evolutions

- [x] #2473
- [x] #2466

### Realm extract creation

- [x] #2474
- [x] #2475
- [x] #2465

### Realm extract access

- [x] #2364

### Misc

- [x] #2476
- [ ] #2477

**Comment by mmmarcos** [comment]
Closing this issue since the sequester feature was implemented in V2.
Porting to V3 branch will be done in #6407
