### ISSUE TITLE
[Oxidation in prod] Poetry/Maturin based pyproject.toml for main parsec Python project

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2489]
depends of #2371

## Overview

Once Rust extension are mandatory to run Parsec there would be no need to separate the python bindings from the regular parsec codebase.
In fact this separation makes things more complex for packaging given parsec requires libparsec (i.e. the rust extension) but must specify the relation with a relative path, which is not allowed when building a wheel (On top of that dependency means dealing version number which we also would like to avoid).

So the solution is simply to merge together parsec and libparsec into a single hybrid Python package.

## Architecture

The switch to Poetry is under way (see #2371), once it is done we should be able to add maturin to it by [taking example of this project](https://github.com/ArniDagur/python-adblock/blob/master/pyproject.toml)

## Command workflow

First use:
```
$ poetry install  # Create a new virtual env and install all dependencies within it
$ poetry shell  # Jump into the virtual env
$ maturin develop  # Build the Rust extensions and install them within the parsec source code so that they can be imported
```

First use wth a custom virtual env (letting poetry handle the venv should be the preferred way, but this might come handy):
```
$ python -m venv my_venv
$ . ./my_venv/bin/activate
$ poetry install  # Poetry detects it is already in a venv and reuse it
$ maturin develop
```

After that, switching into another branch (considering the venv is already activated):
```
$ poetry install && maturin develop
```

## Rust Release vs Debug build ?

In theory we want to have a debug build when doing maturin develop, but switch to release when installing the project with `pip install .` (or when building the wheel, which is equivalent since `pip install` build a wheel behind the scene).
So we should make sure this is the case !

**Comment by FirelightFlagboy** [comment]
> simply to merge together parsec and libparsec into a single hybrid Python package.

Is the package will contains the native code for each target (Linux, Mac, Windows)
Or we will create a specific package for each target ?

**Comment by touilleMan** [comment]
@FirelightFlagboy I was talking of "package" in a Python sens: a folder contaning a `__init _.py` file is considered a package by Python and hence can be imported. By extension package was referring to the root folder of the code.

So my point was to have a single parsec project containing all the python code and the Rust binding stuff. So this project can be build for multiple platform, each time generating a wheel (i.e. a zip that can be installed by Python) specific for this platform.
