### ISSUE TITLE
[Oxidation in prod] Feature flag in the Rust extension bindings

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2490]
Depends on #2489

## Overview

We want to be able to have feature flag to choose to only use a subset of the Rust extension.

This is required because we want to start small by only shipping the schemas in Rust (so we want to disable all the other components in the Rust extension)

This is probably going to be useful when rewriting other complex part of the application where we want to have it merged on master while not using it in production for some time.

## Architecture

Currently the Python code tries to individually each element (e.g. `UserCertificate`) that might be oxidized.
So feature flag can be achieved by making this import failed

So for the feature flag there is two approaches:
1) implement the flag as a feature in the Cargo.toml, hence the extension module would only contains the elements that are to be used
2) implement the flag in Python, hence there would be a check to determine for a given item if it should be imported from the rust extension or from regular Python code

Approach 1) should bring a faster compilation (less stuff to compile) and a smaller binary size (while this is most likely pretty puny, so I think we can ignore this). However it requires two separate compilation + pip install steps if we want to test in the CI both configurations...

So I guess approach 2) is more flexible and is the way to go.

Considering how to config should be provided, environment variable seems the obvious way to go, typically having a `PARSEC_ENABLE_UNSTABLE_OXIDATIONS` (I don't think a fine grain for enabling only a subset of oxidized element is needed, and this would add complexity)

On top of that we most likely want a `--enable-unstable-oxidations` flag in pytest that modify `os.environ` to simplify running the tests

**Comment by FirelightFlagboy** [comment]
> Considering how to config should be provided, environment variable seems the obvious way to go

Approach **2** allow to dynamically enable/disable features as you say (since it's python code, you don't have to recompile the program).

When the user would need to modify the behavior of parsec dynamically ?

---

Choosing one approach rather than another would not add too much complexity the to CI, since when releasing parsec you would  need to build the package with the chosen configuration and run tests over it, and **it's the tests that take the longest time** in the CI.

**Comment by touilleMan** [comment]
The idea is to have a minimum components rewritten in Rust but considered not ready for production.
Obviously this is not the case currently given we have no Rust in production, but I think we can catch up pretty fast on this ;-)

In theory the only unstable Rust components are the one currently under development. So I think we can have the following strategy:
- always test against the unstable components in the CI
- unless the CI is runnig on a release, then test against the stable components

This way we don't have to run the python tests two time which is going to make things much slower :/

> Choosing one approach rather than another would not add too much complexity the to CI, since when releasing parsec you would need to build the package with the chosen configuration and run tests over it, and it's the tests that take the longest time in the CI.

I'd rather not add complexity to the configuration if it's not needed, typically passing different feature flag to cargo when building a wheel from Python is most likely to be a pain...
