### ISSUE TITLE
[Oxidation in prod] CI test Workflow

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2491]
depends on #2489 & #2490

## Current situation

Currently CI works by:
1) building a wheel of the parsec project
2) using this wheel to install parsec on each platform
3) run the tests for each platform
4) In a separate Linux build: run the Rust tests, then install parsec with the Rust extension (i.e. the `libparsec` package) with pip and run the Python tests

This won't work once the Rust extension will be mandatory to run parsec (for instance once we have totally replaced the python schema code by the rust one).

### Installing

We should no longer rely on wheel building for testing.

Instead we can use poetry & maturin (see #2489 ) to install the correct environment to test.

This approach is simple and should be fine enough (dependencies are locked, difference between a release and a debug build for Rust should not be an issue).

### Testing

So the idea is for each platform:
1) Run Rust-only tests
2) install the project with poetry&maturin
3) Run the fast Python tests
4) Run the slow Python tests

I guess the compilation artifacts generate in step 1) are going to be reused in 2), we should make sure of that (it's easy to have the wrong flag enabled that force a full rebuild...)

**Comment by FirelightFlagboy** [comment]
Do you have considered caching with `poetry` & `maturin`, to reduce subsequent CI run ?
When we do the rework ? after/when migrating to `github-action` ?

**Comment by touilleMan** [comment]
Cache for maturin is of course a good idea !

Cache for poetry would be for the dependencies wheel, still a good idea.

In both case we can implement this later if it is non trivial.

For when, as you say it's better to focus on github-action given it is around the corner!

**Comment by FirelightFlagboy** [comment]
Starting from #2778 We don't rely on building the wheel to test python code
