### ISSUE TITLE
probleme d'affichage des autorisations

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#250]
![capture d ecran 2019-03-01 13 47 14](https://user-images.githubusercontent.com/46708918/53639145-b1bfb480-3c28-11e9-8e4b-f45f4b40d4f0.png)

**Comment by Max-7** [comment]
Du au français qui prend un peu plus d'espace que l'anglais. Corrigé dans https://github.com/Scille/parsec-cloud/commit/cc3b92b98a62853f9b839f54ec9627cbb514ad42.
