### ISSUE TITLE
[🐛 | Bug]: Sneak peek duplicated files contained in a workspace

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2503]
### Version

2.10.0-rc1

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

_I see dead people_

### Relevant output

![image](https://user-images.githubusercontent.com/30697622/175272251-a97e2b75-1097-40c8-9577-1d2ebd743b14.png)

**Comment by vxgmichel** [comment]
Fixed in #2517
