### ISSUE TITLE
Add github action to automatically add issues to project board

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2536]
We want to automatically add issue to the organization project.

for doing that, we could use [`Github CLI`](https://cli.github.com/) in a workflow.

# Todo

- [ ] #2588
- [x] #2589
- [ ] Configure a Github Action to be executed when a new issue is created to add it to the project.

# Sources

- [Create repository secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)
- [Manual Dispatch Github Action](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
- [Dispatch GA on issue](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues)
- [List issue with Github CLI](https://cli.github.com/manual/gh_issue_list)
- [Edit issue with Github CLI](https://cli.github.com/manual/gh_issue_edit)
- [Automating projects](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects)

**Comment by FirelightFlagboy** [comment]
NOTE: we could also add a trigger to add the PR to the project

**Comment by FirelightFlagboy** [comment]
Close this issue because the `action` have taken the form of a script that need to be run on a env with `Github CLI` installed & configured to edit `issue/pr` & `project (beta)`
