### ISSUE TITLE
contenu du point de montage

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#255]
J'ai des fichiers que je peux ouvrir dans Parsec ci dessous 
![2019-03-01 4](https://user-images.githubusercontent.com/46708918/53660441-2f51e780-3c5e-11e9-8587-099efafde426.png)
mais que je ne vois pas dans le point de montage explorer
![2019-03-01 3](https://user-images.githubusercontent.com/46708918/53660471-3ed13080-3c5e-11e9-8504-b623fc83b285.png)

**Comment by c4ffein** [comment]
Closed as we don't use this mountpoint system anymore
