### ISSUE TITLE
 Implement the second layer of local storage

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#268]
Dans la PR https://github.com/Scille/parsec-cloud/pull/261 on a un cache mémoire au-dessus du local DB pour stocker les users et manifests, ainsi que les blocks. L'optimisation pour les blocks a été limitée au contenu et non aux metadatas (date d'accès), car il faut MAJ la date de dernier accès de manière fiable.

Cependant, on pourrait procéder ainsi pour éviter au maximum les requêtes de MAJ de date d'accès.

Clean blocks (provenant du remote et qu'on peut perdre) :
- Set blocks : pas écrits dans local DB mais uniquement en mémoire
- Get blocks (memory cache hit) : MAJ date dernier accès en mémoire, lecture depuis la mémoire
- Get blocks (memory cache miss) : déplacement du block en mémoire, date dernier accès dans local DB à NULL, lecture depuis la mémoire
- Avant purge du cache OU arrêt soft : MAJ date d'accès dans la DB locale depuis les blocks dans la mémoire
- Après arrêt hard : suppression des blocks avec date d'accès à NULL

Dirty blocks (pas encore sauvegardés) :
- Set nouveaux blocks : écrits dans local DB et aussi en mémoire
- Get blocks (memory cache hit) : MAJ date dernier accès dans local DB, lecture depuis la mémoire
- Get blocks (memory cache miss) : déplacement du block en mémoire, MAJ date dernier accès dans local DB, lecture depuis la mémoire
- Après arrêt hard : rien
- Avant arrêt soft : rien

Avec ces optimisations :
- On ne gagne rien sur les dirty blocks
- On gagne lors de clean blocks cache memory hit
- On perd clean blocks lus pendant la session si arrêt hard
- Reprise sur arrêt hard un poil plus lente

**Comment by vxgmichel** [comment]
Nouveau statut
-------------------- 

La politique suivante a été implémenté sur la branche [memory-cache-v2](https://github.com/Scille/parsec-cloud/tree/memory-cache-v2):

**Clean blocks**:
- Set block : écriture dans le cache en mémoire
- Get block + memory cache hit: lecture depuis le cache en mémoire
- Get block  + memory cache miss: chargement du block dans le cache mémoire
- Exit: mise-a-jour du stockage persistent (block et date de dernier accès)

**Dirty blocks** :
- Set block : écriture dans le stockage persistent et le cache mémoire
- Get block + memory cache hit : lecture depuis la mémoire
- Get blocks + memory cache miss: chargement du block dans le cache mémoire
- Exit: rien à faire (la date de dernier accès n'importe pas pour les dirty blocks)

**Avec ces optimisations** :
- Dirty block: on économise un accès disque et une opération de chiffrement sur chaque lecture
- Clean block: on économise un accès disque et une opération de chiffrement sur chaque lecture/écriture
- Perte des clean blocks dans le cache mémoire en cas de crash (non problématique)

**Résultat du benchmark**:
- 16% de gain de performance dans le meilleur scénario
- @frossigneux tu veux rajouter des détails?

**Conclusion**:
- Le gain minime de performance ne justifie pas l'intégration de l'optimisation dans la code base
- La PR #318 (cache mémoire pour les blocks) est repoussé
- La PR  #272 (refactoring du stockage local) est mergé
