### ISSUE TITLE
Unstable GUI test `test_workspace_reencryption_access_error`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2693]
The test `test_workspace_reencryption_access_error` is unstable

https://github.com/Scille/parsec-cloud/blob/3803baa57499bdd5f65169e382adccf0dd3f0571/tests/core/gui/test_workspaces_reencrypt.py#L208-L249

# When the test failed

Here is a list of workflow that as failed to test:

For both workflow the tests is run with the following command:

```
poetry run pytest tests --log-level=DEBUG --durations=10 --side-effects-timeout=10 -x -vv --rungui --runmountpoint --runslow -m gui
```

## For Linux

1. https://github.com/Scille/parsec-cloud/runs/7515358679?check_suite_focus=true#step:10:509

## For Windows
 
1. https://github.com/Scille/parsec-cloud/runs/7515358853?check_suite_focus=true#step:11:424
2. https://github.com/Scille/parsec-cloud/runs/7516331179?check_suite_focus=true#step:10:517
3. https://github.com/Scille/parsec-cloud/runs/7516689013?check_suite_focus=true#step:10:516

**Comment by touilleMan** [comment]
can you provide a PR to mark this test as flaky ? 9 out of 10 @vxgmichel recommands using flaky decorator for your inconsistent test issues ;-)
