### ISSUE TITLE
[🐛 | Bug]: Inconsistent RSA signature length with oscrypto

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#2701]
### Version

2.11.0

### What platforms you were running our software when the bug happened ?

MacOS

### What happened ?

`oscrypto.asymmetric.rsa_pss_sign` should generate a signature 128 bytes long, but sometimes the signature has a length of 127 bytes, raising an error in `tests/backend/sequester/test_vlob.py::test_vlob_create_update_and_sequester_access`.

**Comment by FirelightFlagboy** [comment]
This bug is also present in:

- tests/backend/sequester/test_service.py::test_create_disable_services
- tests/backend/sequester/test_service.py::test_workspacefs_sequester_sync : #2702

**Comment by touilleMan** [comment]
fixed by #2703
