### ISSUE TITLE
[Oxidation] Rust fixtures must have there teardown ordered !

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2711]
## Current situation

Python fixtures can have a teardown step:
```python
@pytest.fixture
def foo_fd():
    foo_fd = os.open("foo")
    try:
        yield foo_fd
    finally:  # Teardown step
        os.close(foo_fd)
```

On the opposite, Rust fixtures return an object, so the way to have a teardown step is to `impl Drop` on the object.

## The issue

Rust fixtures returned objects are dropped in an arbitrary order, this creates unexpected error if a fixture is dropped before another that depend on it (e.g. a fixture creating and opening a sqlite database that depend on `tmp_path` fixture, this will create FS operations error on Windows when trying to remove the `tmp_path` directory while the database within it is still opened)

**Comment by TimeEngineer** [comment]
The issue isn't correct
```Rust
#[fixture]
pub fn alice_workspace_storage(alice: &Device, tmp_path: TmpPath) -> TmpWorkspaceStorage
```
The signature shows that tmp_path is dropped at the end of the function if it is not persisted, however if it is bound to an object that lives, it will continue to live :+1:
