### ISSUE TITLE
[GUI] Create a banner to indicate what is the purpose of Parsec

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#276]
In order the user knows in one slight what Parsec is for, create on all pages a banner that indicates :
**in english** 
> Sovereign enclaves for sharing sensitive data on the cloud

**in french**
> Enclaves souveraines pour le partage de données sensibles sur le cloud

**Comment by Max-7** [comment]
Updated the windows's title for now. I keep this issue open until we can find a better way to handle this.

**Comment by touilleMan** [comment]
fixed, and then counterfixed by #703 :trollface:
