### ISSUE TITLE
The double click on a document does not launch it 

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#277]
When we double click on a document in the Parsec Client, it does not open.
When we click right and ask for open the document, it does not open. 
Configuration of the laptops : Ubuntu 18.04 as well as Ubuntu 16.04.

**Comment by Max-7** [comment]
Link to #273 and fixed by https://github.com/Scille/parsec-cloud/commit/43cb75d092317070aa5608d5b2d6dca36a00cf47.
