### ISSUE TITLE
[GUI] A name of device too long is troncated

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#279]
When the name of a device is longer than 18 characters, there no line return but a truncation at the beginning and at the end (see screen copy) 
![Capture du 2019-03-09 19-20-21](https://user-images.githubusercontent.com/9845177/54075515-b6c3da00-42a0-11e9-94c5-3818c3b1d7a8.png)

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/36bbe0ba656a6bdbf1c9857ef9c40c0fa23af184
