### ISSUE TITLE
[GUI] Display the name of the people one share a workspace with

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#280]
When we click on the button "i" on a workspace, we just have the information that the WS is shared with x persons without knowing who there are :
![Capture du 2019-03-09 19-54-52](https://user-images.githubusercontent.com/9845177/54075969-c2fe6600-42a5-11e9-8556-ee5c071f7d36.png)
It would be usefull to list the name of the users the WS is shared with.

**Comment by Max-7** [comment]
Sharing information are displayed and can be managed using the sharing window. The "i" button could be removed, as it does not currently provide any useful information.

**Comment by Max-7** [comment]
Button has been removed by https://github.com/Scille/parsec-cloud/commit/7036817d86435b6106f6321fa0f6cdf57213712a
