### ISSUE TITLE
GUI test

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#2802]
GUI test doesn't work
```
FAILED tests/core/gui/test_main_window.py::test_show_org_info - AttributeError: 'OrganizationInfoWidget' object has no attribute 'label_sequestration_state'
```

**Comment by Max-7** [comment]
Just tried on master and it works perfectly. My guess is you forgot to run `python misc/generate_pyqt.py` so .ui files were not re-generated and old ones were used where `label_sequestration_state` did not exist yet (it was added fairly recently).
