### ISSUE TITLE
Implement the possibility of demount a workspace

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#281]
In the panel of the workspace, it would be great to have a new button that allows to demount one specific workspace so that one can work on a limited number of mounted devices.
As a consequence it would be great in the downside panel to have a button to mount the totality of the workspace.

**Comment by tleblond** [comment]
1) C'est une idée qui est intéressante pour le cas où un utilisateur est amené à travailler sur plusieurs enclaves. D'expérience, l'ergonomie va devenir très complexe pour les utilisateurs qui auront de plus en plus de "clés USB virtuelles" montées.  Imaginons aussi le cas où un utilisateur déploie plusieurs Parsec sur son poste. 
2) Il faudrait garder en mémoire, à l'extinction de Parsec juste la liste des enclaves montées pour retrouver la configuration lors de la reconnexion. Il faudrait par conséquent une fonction qui permette de monter à la demande telle ou telle enclave. Il faut garder cette fonction sous le coude même si elle n'est pas prioritaire.

**Comment by Max-7** [comment]
As discussed, the issue here is mostly that a large number of workspaces can become difficult to navigate through.
- Unmounting a workspace can be useful to "de-congest" the file explorer.
- In the Parsec app, we could add the possibility to filter the workspaces by name.

**Comment by Max-7** [comment]
Dupplicate of #720 , closing this one.
