### ISSUE TITLE
Handle multiple Parsec on the same machine

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#282]
Discussed with @tleblond 

What would be the best way to handle multiple customized Parsec client running on the same machine ?

As Parsec grows, some companies may want to be able to customize the Parsec client (icons, name, colors, ...). How do we handle a specific company-customized Parsec client running alongside the community-edition Parsec client ? (same app, different apps, ...)

**Comment by c4ffein** [comment]
Tabs system have already been developed
