### ISSUE TITLE
PostgreSQL 13/14 much slower than 12 on CI

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#2850]
Pytest's PostgreSQL tests:
- PostgreSQL12 ~9mn
- PostgreSQL 14: ~36mn !!!!

Currently we stick to 12 on the CI, but it requires ubuntu 20.04, so we should investigate this :/

**Comment by FirelightFlagboy** [comment]
If we don't want to be stuck to `ubuntu-20.04` to install `postgrelSQL` which is provided by the defaults apt repositories, we can:

- Configure a docker container to run `postgreSQL` at the desired version
- Configure add the apt repositories of `postgreSQL` to the runner

**Comment by mmmarcos** [comment]
This is no longer relevant (see #5766), we'll re-open if necessary.
