### ISSUE TITLE
Protect against revoked device signing remote manifest

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#287]
Currently `EncryptionManager.decrypt_with_secret_key` check signature of manifest as part of the decryption mechanism, but doesn't check the timestamp of the signature correspond to the one provided by the backend (i.e. the date the backend received the vlob should be roughly the date the manifest encryption within the vlob has been signed)

To do that `vlob_read` api should be modified to return the timestamp field stored by the backend
The author of this vlob version could be also provided by the backend to make sure it is the same as the device having signed the manifest.

**Comment by frossigneux** [comment]
https://github.com/Scille/parsec-cloud/tree/protect-revoked-signing
Implémentation en cours...

**Comment by frossigneux** [comment]
The signature date might be very different of the creation (or update) date of vlob in the backend.
So how to deal with this? A solution would be so sign data only at upload.

**Comment by touilleMan** [comment]
implemented in #321
