### ISSUE TITLE
Add option to make a workspace available offline

### ISSUE THREAD

**Issue by D-Bao** [Scille/parsec-cloud#2949]
Desktop design: click on 3 dots icon and "Rendre disponible hors connexion" https://www.figma.com/proto/imTcRZY5AFwEmpTwoWNyTc/Parsec-Ionic?node-id=19630%3A65618&scaling=scale-down&page-id=19608%3A64935&starting-point-node-id=19630%3A65618&show-proto-sidebar=1
Mobile design: https://www.figma.com/proto/imTcRZY5AFwEmpTwoWNyTc/Parsec-Ionic?node-id=19630%3A65618&scaling=scale-down&page-id=19608%3A64935&starting-point-node-id=19630%3A65618&show-proto-sidebar=1
(The green offline status icon is just an example, subject to change)

**Comment by mmmarcos** [comment]
Offline mode has been implemented. See: https://github.com/Scille/parsec-cloud/issues/5871
