### ISSUE TITLE
temporisation pour saisie des URL MdP Token etc????

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#295]
1 mn est tres court : je suggere de passer à 1,30 voire 2

**Comment by frossigneux** [comment]
Nous sommes actuellement à 2 minutes (mesurée).
Pourtant dans le code il est à 5 minutes. Peut-être est-ce que à la socket Heroku qui se déconnecte avant l'expiration. Je vais investiguer.

**Comment by frossigneux** [comment]
Nous avons mis en place un mécanisme pour envoyer des pings régulièrement au backend.
Cela résout probablement ce problème :
https://github.com/Scille/parsec-cloud/pull/362

**Comment by c4ffein** [comment]
Closed as we don't use this token system anymore
