### ISSUE TITLE
ouverture fichier

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#297]
Dernière Version Parsec 
toujours pas moyen d'ouvrir les fichiers charges ( par moi ou un autre ) sur aucun de mes 2 devices
![Capture d'écran 2019-03-14 17 02 08](https://user-images.githubusercontent.com/46708918/54372255-4390de00-467b-11e9-9c44-0e048d798c9d.png)

**Comment by Max-7** [comment]
Duplicate of #258. I'll close 258.
