### ISSUE TITLE
apparition ecran de codage

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#298]
j'ai eu ceci je pense , quand j'ai fait des copier coller de mes fichiers vers Parsec_MNT
![Capture d'écran 2019-03-15 09 20 19](https://user-images.githubusercontent.com/46708918/54418343-e5a8d880-4704-11e9-962f-d7d4c7bb6a7b.png)

**Comment by touilleMan** [comment]
Devrait être réglé par #299
