### ISSUE TITLE
[GUI] Popups "this workspace is empty" on workspace creation

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#300]
![image](https://user-images.githubusercontent.com/3187637/54427587-3d523e80-471b-11e9-980b-57a80b42a304.png)

parsec version: 0.10.3
platform: windows 10
steps:
1) login
2) create new workspace

**Comment by touilleMan** [comment]
also present on linux

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/5be36870fbfc57a520b540bc8f1e2fbbedffd401
