### ISSUE TITLE
[GUI] Default behavior on login page

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#302]
1) If no device has been created on the client, user should only have choice between bootstrapping a new organization or registering a new account.

2) When last device is not set (typically when a first account has been added or an organization has been bootstrapped), the login page should select the first device available.

2') When an accound has been added or an organization has been bootstrapped, automatically login into (hence last device will be configured, hence 2) is no longer needed)

**Comment by Max-7** [comment]
Added in https://github.com/Scille/parsec-cloud/commit/ebb9bc359c8f3b9445e20e92e9c177136939e4d4

If there's only one device when adding an organization or a new user, the user is automatically logged in.
