### ISSUE TITLE
[GUI] Increase width of user/device enrollment window

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#304]
The with of credentials window (at user/device creation) is too small to see all data.
So the user is unable to send a screenshot to the enrolled user.

**Comment by Max-7** [comment]
But is he supposed to be able to send a screenshot ? URL can be quite long so the window to show it all would be very large too (and thus not very sexy).
I don't see any case where a user would prefer to send a screenshot instead of using copy/paste.

**Comment by frossigneux** [comment]
Ok, we will reopen this issue if users complain about it.
