### ISSUE TITLE
Sync endup in busy loop when offline

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#305]
parsec version: 0.10.3

steps:
1) switch offline
2) create new file
3) watch logs getting flooded by messages like:
>  [debug    ] Impossible to connect to backend [parsec.core.backend_connection.transport] reason=gaierror(11001, 'getaddrinfo failed')

**Comment by frossigneux** [comment]
https://github.com/Scille/parsec-cloud/pull/340
