### ISSUE TITLE
Should we rename parsec url scheme (ws:// -> parsecws://) ?

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#306]
Would avoid user to use the url with a webbrowser

**Comment by frossigneux** [comment]
Je verrais plutôt cette modif dans la GUI / site (qui rajouterait et enlèverait ce préfix "parsec").
C'est une problématique d'affichage et transmission d'info facilitée plutôt que quelque chose interne à parsec.

**Comment by touilleMan** [comment]
dup of https://github.com/Scille/parsec-cloud/issues/513
