### ISSUE TITLE
Websocket polling seems not activated

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#307]
![image](https://user-images.githubusercontent.com/3187637/54429075-ce2b1900-471f-11e9-9a38-469499e28b2a.png)

parsec version: 0.10.3
Heroku drop websocket after some inactivity (https://devcenter.heroku.com/articles/websockets#timeouts), we should be sending pings to avoid this

**Comment by frossigneux** [comment]
https://github.com/Scille/parsec-cloud/pull/362

**Comment by touilleMan** [comment]
Tant que c'est pas mergé l'issue n'est pas fermé ! ^^

**Comment by touilleMan** [comment]
c'est mergé !
