### ISSUE TITLE
[GUI] filtering per name also filter "Parent Workspace"

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#310]
![image](https://user-images.githubusercontent.com/3187637/54429976-5b6f6d00-4722-11e9-9137-54807d904d00.png)

parsec version: 0.10.3
platform: windows

**Comment by Max-7** [comment]
Small fix in https://github.com/Scille/parsec-cloud/commit/b94cb3d5881b59a5d6f6353dfd26feaadcdf4e75. Parent Workspace/Folder will always be either at the top or the bottom, but not in between. This is only a temporary quick and imperfect fix. I'll keep this issue open.

**Comment by Max-7** [comment]
Fixed by #375
