### ISSUE TITLE
Antivirus: Flag rejected manifest from the antivirus to stop synchronization

### ISSUE THREAD

**Issue by AntoineDupre** [Scille/parsec-cloud#3133]
Webhook event can reject a manifest upload. In this case, file shall be flag to not be synchronized anymore for the current session and an event shall be trigger to notify about the error `WEBHOOK_UPLOAD_REJECTED_ERROR`

**Comment by Max-7** [comment]
Done. Can't find the commit, but the app maintains a list of rejected files and won't retry them until it's restarted.
