### ISSUE TITLE
Antivirus: Notify user on WEBHOOK_UPLOAD_REJECTED_ERROR

### ISSUE THREAD

**Issue by AntoineDupre** [Scille/parsec-cloud#3134]
`WEBHOOK_UPLOAD_REJECTED_ERROR` can be raised when a file upload is rejected from the web hook antivirus service.

This event contains the following fields:
 - error_reason
 - file_name

**Comment by Max-7** [comment]
Done with https://github.com/Scille/resana-secure/commit/4b6c6313281312342cc83810e1fcc0b986d5052e
