### ISSUE TITLE
Should we build a 32 bits version of parsec?

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#317]
![image](https://user-images.githubusercontent.com/13103240/54517618-821be680-4962-11e9-9871-0ab4fe2010df.png)

**Comment by frossigneux** [comment]
Effectivement, nous fournissons uniquement des builds 32 bits.
À voir si on délivre aussi une version 32 bits...

**Comment by touilleMan** [comment]
version windows 32 dispo [depuis la version 1.0.1](https://github.com/Scille/parsec-build/releases/tag/v1.0.1)
