### ISSUE TITLE
Cargo build ignore changes in json schema

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#3174]
doing `cargo build` (or `maturin develop`) after having changed the json schemas.

Instead `cargo clean -p libparsec_protocol` must be done by hand to force a rebuild from scratch.

This is obviously due to the fact Cargo is not aware of those json files, however this is incredibly error prone (I let you guess how much time I lose before writing this issue 😄 )

I'm not sure how to fix this however given there is no obvious "also watch this random file" option that could be set in `Cargo.toml`

I guess a solution would be to have move the json to rust genaration into a `build.py`. This way this step would always be called and cargo would handle the rest with the generated rust files. This might make the overall compilation slower (not sure how much, it could be negligible...) given this step would be always called even if we working on a totally different crate 

Another approach would be to do what we do with the bindings genaration: generate once the code and commit it. However this is a bit ugly given we have the generation code in rust (so we would have to compile a program just to do the translation :/)

**Comment by FirelightFlagboy** [comment]
Don't need python for a rust problem :p

**Comment by FirelightFlagboy** [comment]
https://doc.rust-lang.org/cargo/reference/build-scripts.html

**Comment by FirelightFlagboy** [comment]
tl,dr:

```rust
fn main() {
    println!("cargo:rerun-if-changed=file.json");
}
```
