### ISSUE TITLE
Crash when opening file: AssertionError _ensure_hot_file

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#319]
![image](https://user-images.githubusercontent.com/3187637/54547234-a4832380-49a5-11e9-9f15-f446b5f5531c.png)

**Comment by frossigneux** [comment]
Duplicate of https://github.com/Scille/parsec-cloud/issues/303?
Seems to be fixed, probably by https://github.com/Scille/parsec-cloud/pull/328
