### ISSUE TITLE
SQLite error at first login

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#322]
![image](https://user-images.githubusercontent.com/9845177/54587846-9246cb00-4a21-11e9-80cc-cc748dfbdef3.png)

parsec version: 0.10.4
steps:
- bootstrap organisation
- try to login

**Comment by touilleMan** [comment]
Après investigation, le soucis vient du fait que le répertoire `~/.local/share/parsec` contenait déjà une base de données pour cet utilisateur mais avec un mauvais model de données.

Ça poses plusieurs points:
- la GUI devrait logger en errors les exceptions inatendues (pour simplifier ce genre de soucis) (cc @Max-7)
- les données locales sont stockées dans `~/.local/share/parsec/<user_id>@<device_name>` mais ça devrait être `~/.local/share/parsec/<organization_id>#<user_id>@<device_name>` (cf. #323)
- le local storage doit être capable de faire des migrations lors d'un changement de son modèle de données. (cf. #324)

**Comment by Max-7** [comment]
GUI has been updated to display a simple "Can not login" and log an error when an unhandled exception occurs at login (https://github.com/Scille/parsec-cloud/commit/c1ad36ad7b49a022d38876586a04b88ff543620f).

I'll remove the "gui" tag from this issue, since it is no longer linked to the GUI.
