### ISSUE TITLE
Oxidize `InvitationEmailSentStatus`

### ISSUE THREAD

**Issue by Volham22** [Scille/parsec-cloud#3220]
Although `InvitationEmailSentStatus` has a binding, the original enum is still present in the code base. As this is confusing (and may cause problems) it needs to be completely replaced.

Note that the `InvitationEmailSentStatus` binding can be improved by exposing it as `classattr` instead of `classmethod` (see PR #3181).

**Comment by FirelightFlagboy** [comment]
If `InvitationEmailSentStatus` is already binded in `pyo3`, we would just have to remove the definition in python ?

**Comment by Volham22** [comment]
In theory yes, but we should also look if this enum has been fully replaced in the codebase.
