### ISSUE TITLE
Handle datamodel migration in local storage

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#324]
cf. #322 

Une solution pourrait être d'avoir une collection `version` contenant un seul document avec la version du datamodel.
À chaque login d'un utilisateur, cette collection peut être vérifiée (le model de donnée de la collection ne devant jamais changer bien sûr)
Dans le cas d'une version de datamodel ancienne on peut lancer un script de migration (en affichant dans la gui l'avancement)

Du coup dans un premier temps il faudrait mettre en place la collection version (l'implémentation de la logique de migration peut être implémenté par la suite sans soucis du coup)

**Comment by vxgmichel** [comment]
Related: https://github.com/Scille/parsec-cloud/pull/697/commits/b9e370b630d82affe2454a41e8928fd350061287

**Comment by vxgmichel** [comment]
b9e370b should do the job for the moment. Specific migration issues will be discussed in later issues.
