### ISSUE TITLE
Dismount an inopperant workspace after changing its name

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#325]
The bug : 
- Create  a new  workspace "Bille 4"
- The workspace is automatically mounted --> OK
- Change the name of the workspace into "Bulle 4"
- The old workspace stay mounted even if it is no more operational

The correction proposed : once a workspace is renamed, automatically dismount the old name in the mounted point.

**Comment by frossigneux** [comment]
We should also mount the renamed workspace.

**Comment by frossigneux** [comment]
https://github.com/Scille/parsec-cloud/pull/327

**Comment by Max-7** [comment]
#327 merged.
