### ISSUE TITLE
Sequester webhook doesn't check for final `/` in provided webhook url

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#3272]
https://github.com/Scille/parsec-cloud/blob/ac9e5130cff83e33278c075330488329c92d2d33/parsec/backend/vlob.py#L194

If webhook_url has been configured to `http://localhost/foo/` we endup with a POST to `http://localhost/foo//MyOrg`

**Comment by Max-7** [comment]
It checks it when creating the webhook https://github.com/Scille/parsec-cloud/blob/master/parsec/backend/cli/sequester.py#L456
