### ISSUE TITLE
Impl `os.PathLike` for `FSPath`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3326]
Implementing `os.PathLike` for `FSPath` would simplify the typing when we use the `FSPath` in `trio.Path` or `Open`

**Comment by touilleMan** [comment]
I think we should keep `FSPath` and `pathlib.Path`/`trio.Path` separated (the first one works with our internal filesystem, the second the OS filesystem which is a totally different thing)

Can you show where you found this issue, it is most likely an error ;-)

**Comment by FirelightFlagboy** [comment]
`FSPath` represent path in a mounted workspace and should be converted in a correct way to represent a path is an os context, since both context (workspace and os) don't share the same root filesystem
