### ISSUE TITLE
Connexion through a gateway or poor level network

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#335]
When the device is connected to internet through a gateway or when the quality of the connection in poor, Parsec think that he has a free access and wait for the answer of the server. The consequence is a Parsec client dysfunction with temporary freezing. This problem occurs even while opening a session.
It would be great if the client could manage the poor quality of the network without freezing the user computer.
The problem first occurred on the Documation  2019 show..

**Comment by touilleMan** [comment]
fixed by #706
