### ISSUE TITLE
Use yaml or hjson instead of json for our scheme files

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3371]
We currently use json files to define our protocols or types in rust (see the crates `libparsec_protocol` & `libparsec_types` & `libparsec_client_types`).
But for documentation purpose we choose to add comments to the json file, event tho comments aren't in the spec of json.
But it isn't in the spec, tools like `jq` or module like `serde_json` that work in json can handle those files.

for `serde_json` we had to transform the file data by removing the comment and in case of errors we loose the location information.

https://github.com/Scille/parsec-cloud/blob/1e0e36a2817333398b27106587e4a5c5a65855e8/oxidation/libparsec/crates/serialization_format/src/lib.rs#L23-L30

We better move on a format that allows comment or rework the scheme to include the comment as a part of the scheme (likely a `description` field)

If we don't want to add a `description` field (or something likewise to remove the comment from the json) we could use one of the format:

- `hjson` (human json)
  - we don't have to change the file comment are correctly handled
  - we have `deser-hjson` to replace `serde_json` (:warning: not change since 2021)
- `yaml` 
  - it's a superset of `json` we would just have to replace the `//` by `#` for the comments
  - we have `yq` to replace `jq`
  - we have `serde_yaml` to replace `serde_json`

**Comment by touilleMan** [comment]
won't happen, we've settled with json + comment which is "good enough" for our current needs
