### ISSUE TITLE
[GUI] Transparency issue for the tray icon on cinnamon destop

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#343]
![tray](https://user-images.githubusercontent.com/7490006/54826112-604a9880-4caf-11e9-984d-40bb1022c38d.png)

**Comment by Max-7** [comment]
Can not reproduce on Cinnamon 3.8.

**Comment by vxgmichel** [comment]
Weird... I'm using version 4.0.10 though.

**Comment by vxgmichel** [comment]
@Max-7 fixed, somehow :grin:
