### ISSUE TITLE
Have one file system per workspace

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#350]
This implies that:
- each workspace has its own file system
- the concepts of path only makes sense within a given workspace 

Much of the convoluted workspace logic can then be removed from the file system.

This issue can be tackled in two steps:
1. Refactor the internals: 
    Implement the workspace file system and clean up the internals of the fs module while keeping
    a global file system interface so the rest of the application can left untouched
2. Refactor the API:
    Get rid of the global file system interface and update all the calls in the tests and the GUI

**Comment by touilleMan** [comment]
implemented in #349
