### ISSUE TITLE
Rework of synchronization logic

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#351]
The synchronization logic has concurrency issues (#328) and is hard to maintain. 

It could benefits from better concepts and separation of concerns. Some possible ideas include:
- Separating the block reshaping logic from the synchronization logic, since it can never conflict with the remote (it is only about downloading, reshaping and uploading blocks)
- Representing the local changes as a consistent chain of atomic transaction (i.e. updating a single manifest). Each transaction has a list of prerequisites to validate before it can run. A failing transaction would invalidate the rest of the chain and a new chain would have to be crafted again.
- Maybe use a symmetric idea for the remote changes (a chain atomic transaction to apply on the local file system)

**Comment by touilleMan** [comment]
#461 brings progress on this
