### ISSUE TITLE
[GUI] User&Devices tab not showing anything

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#355]
parsec version: master (4db3475)
platform: linux

![image](https://user-images.githubusercontent.com/3187637/54983645-8c1a9680-4fad-11e9-907d-ef6b39615793.png)

![image](https://user-images.githubusercontent.com/3187637/54983752-bd936200-4fad-11e9-8597-447bc75c1314.png)

**Comment by frossigneux** [comment]
https://github.com/Scille/parsec-cloud/pull/369
