### ISSUE TITLE
Erreur lors de l'enrolement ( version de parsec differentes sur les 2 devices)

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#364]
![Capture d'écran 2019-03-29 12 28 33](https://user-images.githubusercontent.com/46708918/55229865-6a741600-521e-11e9-847f-96cf0ce10ac3.png)

**Comment by touilleMan** [comment]
C'est normal, le protocole de communication n'est pas encore stabilisé donc 2 versions différentes de Parsec peuvent amener à ce genre de soucis (évidemment quand on passera à la version 1.0 le protocole sera figé)
