### ISSUE TITLE
restriction de mise à jour sur un WS

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#365]
J'ai restreint Vincent en lecture seule sur un des WS partagées : ca l'a sorti direct de l'application et les maj des autorisations ne se font pas sur mo
![2019-03-29](https://user-images.githubusercontent.com/46708918/55237316-2ee34700-5232-11e9-9ff1-64aa652b146a.png)
n poste

**Comment by Max-7** [comment]
Old sharing dialog, closing the issue.
