### ISSUE TITLE
L'ancien point de montage persiste sur le systeme de fichier apres un renommage de workspace

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#376]
1/ une fois renommé le ws n'est pas partagé : il reste as is chez les autres users

2/ ca crée un nouveau lien dans le point de montage uniquement chez celui qui a fait le renommage

3/ par contre l'ancien nom reste sur les autres users

4/ le point de montage correspondant a l'ancien nom persiste chez celui qui a fait le renommage, mais il n'est plus accessible (c.f la capture d'écran ci dessous)

**Comment by Usersdub** [comment]
![Capture d'écran 2019-04-05 13 28 43](https://user-images.githubusercontent.com/46708918/55624621-d28aa500-57a6-11e9-8f6f-3f32d5278632.png)

**Comment by vxgmichel** [comment]
Pour les points 1, 2 et 3, c'est le comportement attendu: le nom du workspace est propre à a chaque device, les workspaces peuvent donc etre renommés indépendamment.

**Comment by vxgmichel** [comment]
Le point 4 est valide: je renomme l'issue en conséquence.

**Comment by Max-7** [comment]
C'est pas fixé par #327  ?

**Comment by Sithi5** [comment]
#1159 Nouveau système de point de montage
