### ISSUE TITLE
position du Parsec-Mnt dans windows 10

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#380]
Peut on avoir Parsec-Mnt au niveau de la racine de l'explorateur windows comme dropbox ou one drive ( cf la copie d'ecran)?

et au lieu de l'appeler Parsec-mnt , peut on juste avoir Parsec ou Parsec Drive , et encore mieux avec le logo parsec?
![Capture d'écran 2019-04-05 17 40 26](https://user-images.githubusercontent.com/46708918/55639660-3377a480-57ca-11e9-84e3-c49392893a90.png)

**Comment by Max-7** [comment]
Duplicate of #247. Closing this one.
