### ISSUE TITLE
Fenêtre d'erreur: AssertionError dans _ensure_hot_file

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#381]
Je pense qu'on l'a deja repertorie sur la 10.4 , mais au cas ou

![Capture d'écran 2019-04-05 12 04 09](https://user-images.githubusercontent.com/46708918/55639691-468a7480-57ca-11e9-9e98-b32ddabbdaec.png)

**Comment by vxgmichel** [comment]
Ne pourra plus se produire après la PR #370.

**Comment by Max-7** [comment]
Closing the issue.
