### ISSUE TITLE
Séparation entre nouveau partage et gestion des droits

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#382]
elle contient 2 fonctions : partgae et màj des autorisations : on pourrait envisager de les separer ou de les expliciter un peu mieux , voire de les separre des l'ecran du WS
![Capture d'écran 2019-04-05 12 16 06](https://user-images.githubusercontent.com/46708918/55639916-cd3f5180-57ca-11e9-8d2a-d717f767fbd1.png)

**Comment by vxgmichel** [comment]
J'ajoute qu'il faudrait également afficher les droits de l'utilisateur connecté.

**Comment by Max-7** [comment]
Le droit de l'utilisateur connecté c'est présent sur les versions récentes.

**Comment by Max-7** [comment]
Will be done with #1138, closing this issue.
