### ISSUE TITLE
Investigate slowdown of the oxidation of `workspace & user storage`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3838]
The Branch that fix #2898, introduce huge slowdown of parsec (between 60-90%) 

- [ ] Investigate if it's the `trio.to_thread.run_sync()` that slowdown the code
- [ ] Investigate if it's the Rust implementation that slowdown the code (pyo3 binding + struct impl)

**Comment by Volham22** [comment]
The usage of `trio.to_thread.run_sync` slows the code down. We need to use it as few as possible or find an alternative.
