### ISSUE TITLE
Update dialogs in the QT application

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#3854]
In particular, a couple of things should be verified for all dialogs:
- Bigger titles (see suggestions from the UX team)
- Consistent placement for action buttons (`cancel/do action`)
- Consistent colors for action buttons (`cancel` is grey, `do action` is blue`)

**Comment by FirelightFlagboy** [comment]
The python gui was removed, I presume those recommendation are already taken into account for the new UI.
I'm closing this issue
