### ISSUE TITLE
Rust panic provided as BaseException in Python

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#3929]
see https://pyo3.rs/main/doc/pyo3/panic/struct.panicexception

This is not great because `BaseException` go through our exception catcher and hence crash the application without logging an error :/

**Comment by mmmarcos** [comment]
So, this seem to be a PyO3 design choice. It has been discussed in https://github.com/PyO3/pyo3/discussions/2638 and https://github.com/PyO3/pyo3/issues/2783. 

Basically:

> The point is that a panic isn't a typical error condition (returning Result is). A Python user isn't expected to interact with panics, the choice to not extend from Exception is deliberate so that panics are not accidentally caught.

If we agree to treat panic as a (graceful) crash then the proper/suggested way to exit gracefully will be to either use `except (Exception, PanicException)` (or maybe `except BaseException` which will also allow error logging on `KeyboardInterrupt`, `SystemExit`, and so on).

**Comment by mmmarcos** [comment]
Ongoing discussions with PyO3 team, see: https://github.com/PyO3/pyo3/issues/2783#issuecomment-1446274591

**Comment by touilleMan** [comment]
Done https://github.com/Scille/parsec-cloud/blob/358f661fc3aa0bd89732ddb88c31261aae820230/src/lib.rs#L132-L166
