### ISSUE TITLE
UX issue when disabling a workspace

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#3969]
There's a UX issue when disabling a workspace: the default state for the "hide deactivated workspaces" tick box is ticked so when a user clicks on the slider to deactivate the workspace, the corresponding workspace disappear instantly and is replaced by the workspace after it in the list (if any). That can be very confusing, especially since it's the default behavior.

**Comment by fabienSvtr** [comment]
By default, the "Hide disabled workspaces" checkbox should not be checked. Thus, when a user deactivates a workspace, it is always displayed. If the user wants to hide the disabled workspaces, he has to make an action (so that he is aware that the disabled workspaces will not be displayed).
