### ISSUE TITLE
:bug: Wrong use of exception in `parsec/core/local_device.py`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#4046]
## Intro

In `parsec/core/local_device.py` we define `LocalDeviceError`
But in `parsec._parsec` we also define `LocalDeviceError` and use it in the rust code.
That create problem when we do the following:

```python
try:
    # ...
except LocalDeviceError:
    pass
```

or an actual code example: https://github.com/Scille/parsec-cloud/blob/0e2f2d3d780a5528e38687de399b86834e87a09e/parsec/core/local_device.py#L79-L84

Because we `except` for the wrong exception (It have the same name but still)

## Mitigation

Use `parsec._parsec.LocalDeviceExc`

## Correction

1. Rename `parsec._parsec.LocalDeviceExc` to `parsec._parsec.LocalDeviceExc`
2. Replace `LocalDeviceError` definition in `parsec.core.local_device` by the `parsec._parsec` one

**Comment by Max-7** [comment]
Also add a test in https://github.com/Scille/parsec-cloud/blob/master/tests/core/test_recovery.py to try and do a `load_recovery_device` with a valid but wrong passphrase and check that it raises a `LocalDeviceCryptoError`.

**Comment by FirelightFlagboy** [comment]
Suggestion from @Max-7:

Add a test in `tests.core.test_recovery` that test `load_recovery_device` with a wrong passphrase but correctly formatted.
