### ISSUE TITLE
Workspace file list preview not updated

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#408]
Si un utilisateur me partage un fichier, je le vois :
- Immédiatement dans le point de montage via l'explorateur
- Pas dans la fenêtre parsec (au niveau du sommaire des workspaces)

Après un bout de temps, j'ai cliqué sur le workspage :
- J'y ai vu le fichier
- En revenant au sommaire des workspaces j'ai vu le fichier dans la liste de preview

Donc : est-ce que la liste de preview des fichiers dans le workspace doit se synchroniser avec une latence ?

**Comment by frossigneux** [comment]
![a](https://user-images.githubusercontent.com/739143/56422643-d4755d80-62a8-11e9-97c4-4a1d4b7283da.png)

**Comment by Max-7** [comment]
Waiting on the sync update to correctly handle signals related to the workspaces.

**Comment by Max-7** [comment]
Fixed.
