### ISSUE TITLE
Parsec Shortcut in Windows file manager

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#409]
Il se serait que bien que Parsec soit facilement accessible (comme Dropbox ou autre).

**Comment by frossigneux** [comment]
![listing_drives](https://user-images.githubusercontent.com/739143/56422908-06d38a80-62aa-11e9-8aad-68eba04462e9.png)

**Comment by Max-7** [comment]
Duplicate of #247. Closing this one.
