### ISSUE TITLE
[🐛 | Bug]: Fail at 24% in GUI test on Linux platform due to `WorkspaceStorage` binding

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#4101]
### Version

2.15.0

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

Test fail: https://github.com/Scille/parsec-cloud/actions/runs/4283922712/jobs/7460161735
It timeouts at 24% due to `WorkspaceStorage` binding PR

**Comment by FirelightFlagboy** [comment]
Did you have any proof that it's the `WorkspaceStorage` that cause the `timeout` ?

**Comment by TimeEngineer** [comment]
It appears for the first time in your branch before the merge

**Comment by TimeEngineer** [comment]
See here: https://github.com/Scille/parsec-cloud/actions/runs/4253744584/jobs/7399021740

**Comment by FirelightFlagboy** [comment]
So it's only a correlation :p

**Comment by TimeEngineer** [comment]
I meant the Pull Request

**Comment by touilleMan** [comment]
fixed by #4103
