### ISSUE TITLE
Move Development docs to a single file in GitHub

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#4126]
Development docs are not referenced from the official documentation and therefore not displayed anywhere: 
https://github.com/Scille/parsec-cloud/tree/master/docs/development

If they contain up-to-date information, it is proposed to move contents to a single file (i.e. `HACKING.md`) that can be read directly on GitHub. Using Markdown is probably better because `.rst` files are automatically used to generate translations (`.pot`, `.po` files).

Q: There is a [Release Cheat-Sheet section](https://github.com/Scille/parsec-cloud/blob/master/docs/development/release.rst). Is it OK to leave this information here ? Otherwise, where should we move it ?

**Comment by touilleMan** [comment]
see also the [CONTRIBUTING.md](https://github.com/Scille/parsec-cloud/blob/master/CONTRIBUTING.md) that should be also moved then

**Comment by FirelightFlagboy** [comment]
@touilleMan From <https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project>

It's recommended to leave `CONTRIBUTING.md` in the root folder
