### ISSUE TITLE
Fix favicon for user docs

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#4127]
Currently the ReadTheDocs icon is displayed in the user docs, we should use a Parsec icon.

**Comment by FirelightFlagboy** [comment]
We can easily configure that by setting `html_favicon` in `docs/conf.py`

https://github.com/Scille/parsec-cloud/blob/5cc3b43ebebdcb15f7ca5d369443a30f5d3544c8/docs/conf.py#L157-L160
