### ISSUE TITLE
[🐛 | Bug]: `tests/core/test_remanence_monitor.py::test_remanence_monitor_with_core_restart` seems flacky

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#4147]
### Version

2.15.0

### What platforms you were running our software when the bug happened ?

Windows

### What happened ?

Test fail: https://github.com/Scille/parsec-cloud/actions/runs/4314279326/jobs/7527104230

**Comment by FirelightFlagboy** [comment]
It's flaky (already decorated with `pytest.mark.flaky`

**Comment by touilleMan** [comment]
@FirelightFlagboy fixed by #4199 ?

**Comment by FirelightFlagboy** [comment]
I still se `RERUN tests/core/test_remanence_monitor.py::test_remanence_monitor_with_core_restart` in https://github.com/Scille/parsec-cloud/actions/runs/4375872617/jobs/7657180352

**Comment by touilleMan** [comment]
I've re-run the CI 2 times already on https://github.com/Scille/parsec-cloud/actions/runs/4383205904/jobs/7673965298
The changes I have made are only to remove the flaky decorator on the test (and simplify `ci.yml` for faster build)

~Given how unstable the test used to be, I'd say we fixed it \o/~

That was what I was about to write, but just at that time my 3rd run failed 😭 
https://github.com/Scille/parsec-cloud/actions/runs/4383205904/jobs/7673965298#step:12:1828

**Comment by touilleMan** [comment]
This seems to be due to a concurrency issue in the remanence monitor when the connection goes offline in the middle of `RemanenceManager.enable_block_remanence()` call
see https://github.com/Scille/parsec-cloud/pull/4204/commits/bf5313c88b73c32cdea7e1284f70a284fff71d89 to reproce the bug in reliably.
