### ISSUE TITLE
[Discussion] Should we rename the Invite Process Context ?

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#4164]
Current names are based on a number that indicates which step we currently are

**Comment by FirelightFlagboy** [comment]
| Current Suffix | Suggested names |
| --- | --- |
| InitialCtx | WaitPeer / BegingProcedure / StartInvitation / InitProcedure |
| 1Ctx | PeerTrust |
| 2Ctx | SignifyTrust |
| 3Ctx | ShareToken / CommunicateToken / SendToken |
| 4Ctx | CreateUser / CreateDevice / CreateProfile / FinishInvitation |

> We could keep the number
> Instead of `1Ctx` we would have `1PeerTrust`
