### ISSUE TITLE
CodeQL Java don't build rust extension

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#4175]
Configure the gradle file to not build the rust extension.

https://github.com/Scille/parsec-cloud/blob/654ebe7c65b085eabcfce46aadcd97cf3379eb47/oxidation/bindings/android/libparsec/build.gradle#L51-L57

**Comment by touilleMan** [comment]
see https://github.com/Scille/parsec-cloud/pull/4092/commits/b67e12537dd018cd4fa9953c3dbc79269dd01e08

**Comment by FirelightFlagboy** [comment]
Resolve in #4188
