### ISSUE TITLE
[🐛 | Bug]: [RUST] `fail_reopen_database` test fails with timeout

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#4176]
### Version

2.15.0

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

Test fail: https://github.com/Scille/parsec-cloud/actions/runs/4355599502/jobs/7612437395

**Comment by TimeEngineer** [comment]
Another fail: https://github.com/Scille/parsec-cloud/actions/runs/4354487782/jobs/7609848850

**Comment by FirelightFlagboy** [comment]
https://github.com/Scille/parsec-cloud/actions/runs/4362308265/jobs/7627050345

**Comment by FirelightFlagboy** [comment]
Require #3939

**Comment by FirelightFlagboy** [comment]
https://github.com/Scille/parsec-cloud/actions/runs/4382950634/jobs/7672606483

**Comment by FirelightFlagboy** [comment]
Resolved in #4254
