### ISSUE TITLE
Implement collision-safe naming for mountpoints

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#420]
Following up on https://github.com/Scille/parsec-cloud/pull/416#discussion_r278100345.

Now that two workspaces are free to have the same name, mountpoints should be collision-safe. My proposal is to append parts of the workspace id to the workspace name if a directory with the same name already exists. For instance:
- `~/parsec-mnt/my-workspace`
- `~/parsec-mnt/my-workspace-6bd9301f`
- `~/parsec-mnt/my-workspace-6bd9301f-2ecb`
- `~/parsec-mnt/my-workspace-6bd9301f-2ecb-4113`
- `~/parsec-mnt/my-workspace-6bd9301f-2ecb-4113-8697`
- `~/parsec-mnt/my-workspace-6bd9301f-2ecb-4113-8697-9f9bce04e336`

**Comment by touilleMan** [comment]
implemented by #425
