### ISSUE TITLE
Do not ask extern users if they want to create a recovery device

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#4203]
Rational behind it is that extern users do not have any rights and are treated more as a "one time sharing" that can be revoked and onboarded easily.

That being said, technically, extern users are still users, it's probably better if they are understood as real users in the system, not as temporary thing.

**Comment by mmmarcos** [comment]
If by "extern" you mean the "Outsider" profile, I don't think this is a good idea.

Adding recovery devices allows a user to avoid loosing access to its account and it is not related to how much, or for how long, the user will contribute to the organization. For example, the Outsider profile can be given to a sub-contractor for regular and/or long-term contributions.

I am closing the issue as not planned. Please re-open if you want to add more details or if I misunderstood your proposal.
