### ISSUE TITLE
"Mountpoint has been unmounted" red notification when renaming a workspace

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#433]
When a workspace is renamed, a red notification appears: `Mountpoint has been unmounted`.

This is confusing. A yellow notification `Mountpoint has been remounted` would look ok to me.

**Comment by Max-7** [comment]
Done by https://github.com/Scille/parsec-cloud/commit/d61a89e438dad4d27d6bfdd0e260647c0ee5f23a
Ideally we should be able to hide notifications when remounting a workspace but we currently have no way of distinguishing between a rename and an abnormal unmount..
