### ISSUE TITLE
Parsec icon changed if pinned to the taskbar

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#440]

**Comment by Max-7** [comment]
https://stackoverflow.com/questions/1551605/how-to-set-applications-taskbar-icon-in-windows-7/1552105#1552105

**Comment by Max-7** [comment]
The app pinned in the taskbar is <parsec_dir>/core/parsec.exe instead of <parsec_dir>/parsec.exe. It also prevents the user from launching the app pinned in the taskbar. See https://github.com/Scille/parsec-build/issues/19.

**Comment by Max-7** [comment]
Done.
