### ISSUE TITLE
Upgrade xml2js-dependent dependencies

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#4424]
Check if it is possible to update dependencies that depend on xml2js. See:

- [x] https://github.com/Scille/parsec-cloud/security/dependabot/71 (in [oxidation/client/electron/package-lock.json](https://github.com/Scille/parsec-cloud/blob/-/oxidation/client/electron/package-lock.json))
- [x] https://github.com/Scille/parsec-cloud/security/dependabot/72 (in [oxidation/client/package-lock.json](https://github.com/Scille/parsec-cloud/blob/-/oxidation/client/package-lock.json))

**Comment by FirelightFlagboy** [comment]
This would be resolve when we update `@capacitor/cli`, see ionic-team/capacitor#6486

**Comment by FirelightFlagboy** [comment]
The vuln is still present, why did you close this @NicoTuxx

**Comment by FirelightFlagboy** [comment]
The issue are resolved now
