### ISSUE TITLE
Add a PowerShell-compatible run_testenv script

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#4436]
On Windows, the script `tests/scripts/run_testenv.bat` does not work as expected if executed/sourced from PowerShell. It must be executed in a `cmd.exe` in order for the `APPDATA` variable to be modified.

The reason is explained in [this answer](https://stackoverflow.com/a/68024909) :

> Therefore:
> - If the caller is a `cmd.exe` session, you must use a batch file: a plain-text file with filename extension `.cmd` (or, less preferably, .bat[1]) that uses `cmd.exe` syntax.
> - If the caller is a PowerShell session, you must use a PowerShell script: a plain-text file with filename extension `.ps1` that uses PowerShell syntax.
>     Note: While you can call a `.cmd` file (batch file) from PowerShell too (but not directly vice versa), this will not work as intended, because of necessity it runs in a (`cmd.exe`) child process, whose environment variables aren't seen by the PowerShell caller.

**Comment by FirelightFlagboy** [comment]
The `testenv` was removed, this issue will be closed
