### ISSUE TITLE
`Wasm-pack` don't support custom profile

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#4447]
When building the rust lib for the web (generating a wasm using `wasm-pack`), I got the following error when using the profile `ci-rust`:

```txt
error: failed reading '/home/runner/work/parsec-cloud/parsec-cloud/target/wasm32-unknown-unknown/debug/libparsec_bindings_web.wasm'

Caused by:
    No such file or directory (os error 2)
Error: Running the wasm-bindgen CLI
Caused by: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 1
  full command: "/home/runner/.cache/.wasm-pack/wasm-bindgen-1e0eb8952f04f11f/wasm-bindgen" "/home/runner/work/parsec-cloud/parsec-cloud/target/wasm32-unknown-unknown/debug/libparsec_bindings_web.wasm" "--out-dir" "/home/runner/work/parsec-cloud/parsec-cloud/oxidation/bindings/web/pkg" "--typescript" "--target" "web" "--debug"
```

The root cause seems to be that `wasm-binding` look for the generated wasm under the `target/dev` folder instead of the folder `target/ci-rust`

So the command `npm run build:ci` and `npm run build:release` are broken currently

Related to rustwasm/wasm-pack#1111

**Comment by touilleMan** [comment]
a quick fix for this is to add a symlink `dev -> ci-rust` before running the command
