### ISSUE TITLE
Potential file corruption issue

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#445]
![image](https://user-images.githubusercontent.com/18075498/57534357-25282580-7340-11e9-8ac0-addbf2746eea.png)

**Comment by Max-7** [comment]
Only seems to happen with PDF.

**Comment by Max-7** [comment]
Happens on a few files that seems to be corrupted (checksum before/after importing in Parsec differ).

**Comment by vxgmichel** [comment]
Duplicate of #878
