### ISSUE TITLE
Apply Ionic 7 upgrade changes

### ISSUE THREAD

**Issue by NicoTuxx** [Scille/parsec-cloud#4499]
https://ionicframework.com/docs/updating/7-0

**Comment by FirelightFlagboy** [comment]
This seems to be fixed by d50a80e03e, does this issue still need to exist ?

**Comment by FirelightFlagboy** [comment]
After looking around:

- Some checkbox CSS need to be updated https://ionicframework.com/docs/updating/7-0#checkbox
- Some Toggle CSS need to be updated https://ionicframework.com/docs/updating/7-0#toggle
