### ISSUE TITLE
Tune the block size

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#452]
Block size can really affect the performance of the system and should be tuned properly:
- A small block size increases the size of vlobs for large files
- A large block size causes more failure when downloading/uploading with an unreliable connection

@touilleMan proposes a block size of 1MB.

We should also make sure that changing this size doesn't break backward-compatibility, i.e the system shouldn't assume the size of the blocks that already exist.

**Comment by Max-7** [comment]
Linked to #399

**Comment by vxgmichel** [comment]
This has been implemented a while ago.
