### ISSUE TITLE
[:boxing_glove: :crab: :1st_place_medal: Final oxidation] Test `Manifest::deserialize_data`

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4540]
see https://github.com/Scille/parsec-cloud/blob/6242d270c199a59318a89d51d07bcfdb3ba6ba85/oxidation/libparsec/crates/types/src/manifest.rs#L604

Incorrect unwrap when the data cannot be deserialized, a test is missing here.

On top of that we should check that all other manifests method and types have correct tests !

**Comment by FirelightFlagboy** [comment]
Also change that `.unwrap()` with `?`
