### ISSUE TITLE
[:boxing_glove: :crab: :snake: :1st_place_medal: Final oxidation] Remove APIv2

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4546]
APIv2 should no longer be needed.
By removing APIv2, we can also remove from the json schemas the introduced in
minor version fields that are <3.0. This is good given the protocol generator
doesn't factorize commands that have this field set.
In other words a command that is `majors_versions: [2, 3, 4]` and have a field
marked `introduced_in_minor: 2.1` will produce three separate structures, while
a single structure shared between v3 and v4 will be produced if v2 is removed.

**Comment by mmmarcos** [comment]
@touilleMan Just to be sure of what exactly is required in order to drop support for V2:
- [ ] Remove the `2` in `"major_versions"` field, from all protocol schemas
- [ ] Remove all the fields where `"introduced_in"` is `<3.0`
  - Currently there are 44 fields introduced in `2.x`, **none** of these fields are still required?
- [ ] Remove all the code related to the removed fields ? 

Btw, some schemas are identical between v2 and v3/v4 (i.e. [libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5)). I suppose is OK to completely remove the v2 schema in this case, isn't it?

Anything else that I might be missing?

**Comment by FirelightFlagboy** [comment]
> Remove the 2 in "major_versions" field, from all protocol schemas

Yes, you need to remove `2` in the `major_versions` array value.

> Remove all the fields where "introduced_in" is <3.0
> Currently there are 44 fields introduced in 2.x, none of these fields are still required?

You need to remove the field `introduced_in` not an entire field that contain a field `introduced_in`.

When we have `introduced_in` in a field it's to indicate that this field was added during a major version (`2.x` where $x > 0$), when we bump the major version (from `2.x` to `3.x`) the field is considered stabilized (the value is always present).

> Remove all the code related to the removed fields ?

From the answer above => no

**Comment by FirelightFlagboy** [comment]
> Btw, some schemas are identical between v2 and v3/v4 (i.e. [libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5)). I suppose is OK to completely remove the v2 schema in this case, isn't it?

They're not quite indentical :sweat_smile:, look for the `introduced_in` ;), the schema you've linked was introduced in 2 major version (2.8 and 3.2)

**Comment by mmmarcos** [comment]
>> Btw, some schemas are identical between v2 and v3/v4 (i.e. [libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5)). I suppose is OK to completely remove the v2 schema in this case, isn't it?

> They're not quite indentical sweat_smile, look for the introduced_in ;), the schema you've linked was introduced in 2 major versions (2.8 and 3.2)

So, is this an exception to the rule of removing `2` in the `"major_versions"` array value? Since the v3/v4 one was introduced in 3.2 we cannot fully remove the v2 version, otherwise the schema will not be supported between >2.8 and <3.2 :thinking:

**Comment by mmmarcos** [comment]
> We can consider that the release of the api version `2.8` & `3.2` is old enough for all users to have updated their client thinking

Then I guess it is OK to remove v2, these schemas will be supported from version 3.2 onwards.

Only the following are concerned (v2 marked as introduced in `2.8` and v3/4 as introduced in `3.2`):
- [anonymous_cmds/pki_enrollment_info.json5](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_info.json5)
- [anonymous_cmds/pki_enrollment_submit](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/anonymous_cmds/pki_enrollment_submit.json5)
- [authenticated_cmds/pki_enrollment_accept.json5](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_accept.json5)
- [authenticated_cmds/pki_enrollment_list.json5](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_list.json5)
- [authenticated_cmds/pki_enrollment_reject.json5](https://github.com/Scille/parsec-cloud/blob/47ec153599710372a3baeb5ffb1572326378c27c/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_reject.json5)

@touilleMan any thoughts on this?
