### ISSUE TITLE
Additional tests for SSE (server side)

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4551]
Related to #4550

Additional tests needed:

- [x] #6960
- [x] #6961
- connect
- receive an event
- then connection disconnect
- more events.
- Finally on connection reconnect the missed events should be provided before continuing with the news events.

Multiple tests can be done (too many events for the server cache, new events while the client hasn't finished
consuming the missed ones, invalid last-event-id parameter)

- [x] #7033
- [x] #7039
- [x] #7041
- [x] #7029

**Comment by FirelightFlagboy** [comment]
All tasks are fixed, closing
