### ISSUE TITLE
[:boxing_glove: :1st_place_medal: Final oxidation] Improve document for testbed server docker build for CI

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4572]
Testbed server is a Python app (hence requiring the parsec Python bindings), but is used in the Rust tests.

This is not cool given it means we must compile the Python bindings when testing the Rust code :(
To fix this we instead pre-compile and package the testbed server and store it [in the project package pages](https://github.com/orgs/Scille/packages?repo_name=parsec-cloud).

This is great... until the testbed server must be updated in which case it is currently hard to understand what should be done...

So what we should do:

- [ ] Improve the [error message when the testbed env crc between client and server doesn't match](https://github.com/Scille/parsec-cloud/blob/76f06a1ec77fd794f50fc140a1f5fa594727a0fa/oxidation/libparsec/crates/testbed/src/env.rs#L136). The idea is to explain this is most likely due to version incompatibility (typically this testbed env has been updated or is a newly introduced one) and that if this occurs during CI run this can be fixed by building a new testbed server image, then provide the link to the documentation...
- [x] #4609

- [x] Ideally the build & upload part should be done by a manually triggered github action (this would considerably simplify the documention and the ease of use !), [this seems doable according to github documentation](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#publishing-a-package-using-an-action).
      
    The interrogation @FirelightFlagboy had about it was the action must use some authentication credential to proceed to the upload of the package. But it seems [`github.actor`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) and [`secret.GITHUB_TOKEN`](https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context) are automatically provided when running the CI, so it should work out-of-the-box \o/
  
    Done in #4587

**Comment by FirelightFlagboy** [comment]
Concerning the `secret.GITHUB_TOKEN` the important part is found here <https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token>

The token can be configured to have permission to write on packages page.

An example can be found here https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-github-packages

**Comment by FirelightFlagboy** [comment]
Concerning the part 

> Ideally the build & upload part should be done by a manually triggered github action

A new workflow has been created to do that in #4587
