### ISSUE TITLE
 [:boxing_glove: :1st_place_medal: Final oxidation] Merge `castor` :beaver: branch in `master` 

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4574]
After discussion with @FirelightFlagboy & @mmmarcos the approach is:

- [x] Create a `v2.16.0-rc1` release from the current master
  - @FirelightFlagboy should check for which PRs should be merged into master before doing such release 
  - This release is not meant to be a stable one for the moment (hence the `-rc1` suffix), it's instead a starting point if we need to release a version given the master is going to be not-release-ready for some time...
- [x] #4573 Fix `castor`'s CI 
- [x] merge `castor` into `master` \o/

@mmmarcos's ~#4538~ (superseded by #4665) is a good example of PR not yet ready but which would be merged into the old master instead of the new [castor-flavored](https://fr.wikipedia.org/wiki/Castor%C3%A9um) one. So the idea would be:
- finish the PR
- merge it on `2.16` branch (which is created from `v2.16.0-rc1`)
- create an issue tagged oxidation to indicate this feature is missing in the rust rewrite of the mountpoint
- release an actual `v2.16.0` when the feature is needed in production

**Comment by FirelightFlagboy** [comment]
Castor have created a dam on `master`, I'll close this issue
