### ISSUE TITLE
[:boxing_glove: :1st_place_medal: Final oxidation] Improve debug for protocol Req/Rep

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4577]
Example of error we currently have:

```
thread 'base' panicked at 'Hook got an unexpected request type: Req { created_after: None }'
```

This is bad given we don't know to what command this req corresponds to.

So we should modify `libparsec_serialization_format` code to put a custom `Debug` implementation that would also provide the name of the command, for instance: `Req { cmd: "certificate_get", created_after: None }`

Another solution is to change the name of the Req: `CertificateGetReq { created_after: None }` this had the added benefit
of allowing consistent debug for the reps (e.g. `CertificateGetRepOk {}`).

**Comment by mmmarcos** [comment]
This appears to have been done in https://github.com/Scille/parsec-cloud/pull/4733

To be more precise, here: https://github.com/Scille/parsec-cloud/commit/9e12f20e3ea19945d14fd16e9da0a19d4a60ca9b

@touilleMan do you confirm it?

**Comment by touilleMan** [comment]
yes !
