### ISSUE TITLE
Detect if parsec is already running

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#458]
Deux options :
- Soit inviter l'utilisateur à rouvrir Parsec via l'icone dans la zone de notification (dialog de warning).
- Soit envoyer un signal à l'instance déjà en cours pour remettre au premier plan la fenêtre (pas de warning et illusion de pouvoir ré-ouvrir parsec en recliquant sur l'exécutable de lancement).

**Comment by Max-7** [comment]
J'ajoute juste qu'il faut que ce soit uniquement dans un cas de "production". J'ai souvent besoin d'ouvrir deux Parsec pour les tests.

**Comment by Max-7** [comment]
Merged.
