### ISSUE TITLE
[:boxing_glove: :1st_place_medal: Final oxidation] Fix SSE support for Wasm32

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4677]
Currently SSE relies on [Reqwest-Eventsource](https://github.com/jpopesculian/reqwest-eventsource) which is not compatible with wasm32.

There [is a PR to add support](https://github.com/jpopesculian/reqwest-eventsource/pull/10), but I suspect it might not properly work in on a web target:
- SSE relies on the fact the response is sent bit by bit (i.e. the server send a new line on the tcp socket each time it needs to push an event to the client)
- It's the web browser job to handle SSE in order to trigger the javascript callback each time an event arrived
- So if the SSE support is build on top of reqwest (which is going to be excuted in the browser sandbox), the browser migh consider the request as a regular non-SSE one, and the client code only receive all the event at once when the connection is closed by the server (so basically never) instead of as soon as the event is received...

**Comment by FirelightFlagboy** [comment]
Not sure about the goal of this issue.

The crate currently used that provide support for SSE cannot be compile to wasm32.
But it exist a PR to fix that.

Even tho that PR (opened last year) is merged we're not sure if it's going to work in a web navigator.

- Do we need to investigate if indeed the PR would make it compatible to `wasm32` and if it's functional in a web browser environment ?
- Do we need to find a replacement for that crate ?
- Do we need to fork that crate and fix it ?

@touilleMan can you clairify that ?
