### ISSUE TITLE
Add a `finished` field to `invite_4_claimer/greeter_communicate` command

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#4821]
This field would let the server know that the invitation is now complete.

This is useful for atomically cleaning up the invitation after the last command has been performed.

It also make the last `communicate` step more robust as there are currently no state after `ConduitState.STATE_4_COMMUNICATE` (i.e the conduit just stays in the "communicate" state until the invitation is deleted).

**Comment by touilleMan** [comment]
Done in APIv4 https://github.com/Scille/parsec-cloud/blob/6c269ad64208b2a7615e74b37bcdd75408243042/libparsec/crates/protocol/schema/authenticated_cmds/invite_4_greeter_communicate.json5#L17-L20
