### ISSUE TITLE
Semi-created organisation login failure

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#488]
Après une erreur lors de la création de l'organisation (en l'occurrence mauvaise heure de l'ordi, puis erreur "not found"), il est pourtant possible de tenter de se loguer avec la config crée en local mais pas dans le backend.
Du coup lors du login on a cette erreur :

> {"event": "Unhandled error", "logger": "parsec.core.gui.main_window", "level": "error", "exception": "Traceback (most recent call last):\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\transport.py\", line 140, in _do_handshade\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\protocole\\handshake.py\", line 214, in process_result_req\nparsec.api.protocole.handshake.HandshakeBadIdentity: Unknown Organization or Device\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\fs\\userfs\\userfs.py\", line 523, in process_last_messages\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\porcelain.py\", line 39, in wrapper\n  File \"C:\\Python36-x64\\lib\\site-packages\\async_generator\\_util.py\", line 34, in __aenter__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\transport.py\", line 231, in acquire\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\transport.py\", line 105, in _connect\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\transport.py\", line 156, in _do_handshade\nparsec.core.backend_connection.exceptions.BackendHandshakeError: Unknown Organization or Device\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\gui\\trio_thread.py\", line 65, in _run_fn\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\gui\\main_window.py\", line 39, in _do_run_core\n  File \"C:\\Python36-x64\\lib\\site-packages\\async_generator\\_util.py\", line 34, in __aenter__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\logged_core.py\", line 106, in logged_core_factory\n  File \"C:\\Python36-x64\\lib\\site-packages\\trio\\_core\\_run.py\", line 506, in __aexit__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\messages_monitor.py\", line 42, in monitor_messages\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\fs\\userfs\\userfs.py\", line 530, in process_last_messages\nparsec.core.fs.exceptions.FSError: Cannot retrieve user messages: Unknown Organization or Device", "timestamp": "2019-06-12 08:08:00"}

**Comment by Max-7** [comment]
Linked to #1038, closing this issue.
