### ISSUE TITLE
Assertion error at login

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#490]
Lors d'un login réussi, cette erreur apparaît :

> Traceback (most recent call last):
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\gui\main_window.py", line 184, in login_with_password
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\gui\main_window.py", line 122, in start_core
> AssertionError

**Comment by c4ffein** [comment]
This code has been modified multiple times since then and this error seems to not happen anymore, closing
