### ISSUE TITLE
 Web support for UserStorage

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4904]
Currently [UserStorage is only available on native](https://github.com/Scille/parsec-cloud/blob/935946da974689c3c2b195ee6213de595d54e112/libparsec/crates/platform_storage/src/native/user.rs)

We need it to be available on web for testing the GUI

I guess [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) is the best choice for storing data: this store basically only store a single binary blob, but it it should be the groundwork for the WorkspaceStorage (that will store much more binary data so `IndexedDB` is definitely the way to got there)

Depends on https://github.com/Scille/parsec-cloud/issues/4902 for tests support

**Comment by mmmarcos** [comment]
Close as completed by #6617
