### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-cloud#491]
Sans rien faire de particulier, mais en étant logué et en ayant déjà créé un workspace:

> {"conn_id": "78aec5d310174765807618764fdd29e3", "device_id": "francois@windows", "cmd": "vlob_group_get_roles", "event": "Request", "logger": "parsec.api.transport", "level": "info", "timestamp": "2019-06-12 08:23:18"}
> {"event": "Uncatched error", "logger": "parsec.core.gui.trio_thread", "level": "exception", "exception": "Traceback (most recent call last):\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\transport.py\", line 51, in _next_ws_event\nStopIteration\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\gui\\trio_thread.py\", line 65, in _run_fn\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\gui\\main_window.py\", line 47, in _do_run_core\n  File \"C:\\Python36-x64\\lib\\site-packages\\async_generator\\_util.py\", line 53, in __aexit__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\logged_core.py\", line 106, in logged_core_factory\n  File \"C:\\Python36-x64\\lib\\site-packages\\trio\\_core\\_run.py\", line 506, in __aexit__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 209, in backend_listen_events\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 91, in run\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 117, in _event_listener_manager\n  File \"C:\\Python36-x64\\lib\\site-packages\\trio\\_core\\_run.py\", line 506, in __aexit__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 181, in _event_pump\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 185, in _event_pump_do\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\porcelain.py\", line 40, in wrapper\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\cmds.py\", line 126, in events_listen\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\cmds.py\", line 76, in _send_cmd\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\transport.py\", line 142, in recv\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\transport.py\", line 55, in _next_ws_event\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\transport.py\", line 68, in _net_recv\n  File \"C:\\Python36-x64\\lib\\site-packages\\wsproto\\connection.py\", line 231, in receive_bytes\nValueError: Connection already closed.", "timestamp": "2019-06-12 08:28:13"}
> Traceback (most recent call last):
>   File "C:\projects\parsec-build\parsec-cloud\parsec\api\transport.py", line 51, in _next_ws_event
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\gui\trio_thread.py", line 65, in _run_fn
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\gui\main_window.py", line 47, in _do_run_core
>   File "C:\Python36-x64\lib\site-packages\async_generator\_util.py", line 53, in __aexit__
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\logged_core.py", line 106, in logged_core_factory
>   File "C:\Python36-x64\lib\site-packages\trio\_core\_run.py", line 506, in __aexit__
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\event_listener.py", line 209, in backend_listen_events
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\event_listener.py", line 91, in run
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\event_listener.py", line 117, in _event_listener_manager
>   File "C:\Python36-x64\lib\site-packages\trio\_core\_run.py", line 506, in __aexit__
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\event_listener.py", line 181, in _event_pump
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\event_listener.py", line 185, in _event_pump_do
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\porcelain.py", line 40, in wrapper
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\cmds.py", line 126, in events_listen
>   File "C:\projects\parsec-build\parsec-cloud\parsec\core\backend_connection\cmds.py", line 76, in _send_cmd
>   File "C:\projects\parsec-build\parsec-cloud\parsec\api\transport.py", line 142, in recv
>   File "C:\projects\parsec-build\parsec-cloud\parsec\api\transport.py", line 55, in _next_ws_event
>   File "C:\projects\parsec-build\parsec-cloud\parsec\api\transport.py", line 68, in _net_recv
>   File "C:\Python36-x64\lib\site-packages\wsproto\connection.py", line 231, in receive_bytes
> ValueError: Connection already closed.
> {"event": "Unhandled error", "logger": "parsec.core.gui.main_window", "level": "error", "exception": "Traceback (most recent call last):\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\gui\\trio_thread.py\", line 65, in _run_fn\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\gui\\main_window.py\", line 47, in _do_run_core\n  File \"C:\\Python36-x64\\lib\\site-packages\\async_generator\\_util.py\", line 53, in __aexit__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\logged_core.py\", line 106, in logged_core_factory\n  File \"C:\\Python36-x64\\lib\\site-packages\\trio\\_core\\_run.py\", line 506, in __aexit__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 209, in backend_listen_events\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 91, in run\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 117, in _event_listener_manager\n  File \"C:\\Python36-x64\\lib\\site-packages\\trio\\_core\\_run.py\", line 506, in __aexit__\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 181, in _event_pump\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\event_listener.py\", line 185, in _event_pump_do\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\porcelain.py\", line 40, in wrapper\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\cmds.py\", line 126, in events_listen\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\core\\backend_connection\\cmds.py\", line 76, in _send_cmd\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\transport.py\", line 142, in recv\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\transport.py\", line 55, in _next_ws_event\n  File \"C:\\projects\\parsec-build\\parsec-cloud\\parsec\\api\\transport.py\", line 68, in _net_recv\n  File \"C:\\Python36-x64\\lib\\site-packages\\wsproto\\connection.py\", line 231, in receive_bytes\nparsec.core.gui.trio_thread.JobResultError: crashed", "timestamp": "2019-06-12 08:28:13"}
>

**Comment by Max-7** [comment]
Deprecated.
