### ISSUE TITLE
Backport certifi update to releases/2.16

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#5027]
We should backport #5045 to `releases/2.16`.

See: 
- https://github.com/Scille/resana-secure/security/dependabot/22
- https://github.com/Scille/resana-secure/security/dependabot/23

**Comment by FirelightFlagboy** [comment]
Pin the certifi version in pyproject.toml (don't use a range)

**Comment by mmmarcos** [comment]
Done in https://github.com/Scille/parsec-cloud/commit/62bd59781cc238b7a661c7285b5f4d92fa12194e
