### ISSUE TITLE
Add a parsec:// protocol

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#513]
Instead of having a huge URL (currently using ws:// protocol) to bootstrap an organization or add a user/device, we could implement or own parsec:// protocol and register this protocol to the operating system so that it opens Parsec automatically if such a link is clicked.
URL should give some information about the associated operation, so that the GUI can display the right window and autofill the URL form field.

**Comment by Max-7** [comment]
https://docs.microsoft.com/fr-fr/windows/uwp/launch-resume/handle-uri-activation

**Comment by vxgmichel** [comment]
On ubuntu (and maybe more distros) this can be done using the `x-scheme-handler`:
1. add support for an URI argument to the parsec command (e.g. `parsec parsec://foo`)
2. change the `Exec` entry of the `.desktop` file to `parsec %u` to pass the argument
2. add `MimeType=x-scheme-handler/parsec;` to the `.desktop` file
3. run `xdg-mime default parsec.desktop x-scheme-handler/parsec` to set up the scheme handler
4. test with `xdg-open parsec://foo`

[More info](https://askubuntu.com/a/1023143/400096).

**Comment by touilleMan** [comment]
last step here https://github.com/Scille/parsec-cloud/pull/684

**Comment by Max-7** [comment]
Done.
