### ISSUE TITLE
Add `web` to the list of OS in `libparsec/src/os.rs`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5166]
From @touilleman [comment](https://github.com/Scille/parsec-cloud/pull/5141#pullrequestreview-1617718313)

**Comment by TimeEngineer** [comment]
`web` is not an `OS`

**Comment by FirelightFlagboy** [comment]
Discuss it with @touilleMan

**Comment by touilleMan** [comment]
@TimeEngineer see https://github.com/Scille/parsec-cloud/pull/5141#pullrequestreview-1617718313

> And if you're picky and don't consider web an OS, you can rename this os -> platform :trollface:
