### ISSUE TITLE
[MS] Export all type defined in `plugings/libparsec/definition.d.ts`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5167]
From @touilleMan [comment](https://github.com/Scille/parsec-cloud/pull/5141#pullrequestreview-1617718313)

**Comment by touilleMan** [comment]
regarding https://github.com/Scille/parsec-cloud/pull/5141#issuecomment-1713355238

> I can't do import * from ..., but I can do import * as foo from ..., nevertheless It's not related to this PR, I've created the issue https://github.com/Scille/parsec-cloud/issues/5168

I guess want we want to do is `import { * } from ...`

**Comment by FirelightFlagboy** [comment]
Fixed in #5141
