### ISSUE TITLE
Make Handle starts at 1 instead of 0

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#5170]
`if` would avoid special behavior when doing `if handle` in the javascript code

```js
if (handle) {
  // ...
}
```

the change is pretty simple, should change the initial value:
https://github.com/Scille/parsec-cloud/blob/8e20f1c7fbf47f1c1ed62bc1b6dd0f3dbefd5d1b/libparsec/src/handle.rs#L42

**Comment by FirelightFlagboy** [comment]
@touilleMan from looking at the code it seems we would need to start with a `Vec` that isn't empty.

**Comment by touilleMan** [comment]
done (cf. https://github.com/Scille/parsec-cloud/blob/2695d4116cdd440cf26133062ae3f44dda717ece/libparsec/src/handle.rs#L65-L67)
