### ISSUE TITLE
Use int instead of string to pass datetime in the GUI

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#5171]
Should modify this:
https://github.com/Scille/parsec-cloud/blob/8e20f1c7fbf47f1c1ed62bc1b6dd0f3dbefd5d1b/bindings/generator/api/common.py#L126-L130

To return the number of milliseconds since epoch (1970), as this is what Javascript use to deal with dates (cf. https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)

**Comment by FirelightFlagboy** [comment]
Superseded by #5375
