### ISSUE TITLE
Investigate concurrency handling in postgresql when adding a certificate

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#5203]
Especially for queries such as `query_update_roles` and `query_update_archiving`

More info in [this commit](https://github.com/Scille/parsec-cloud/pull/5061/commits/f972b816214f3820cba2a9ce3bab42af2e98dbb5):
>     # TODO: Concurrency is not managed here.
>     # It would be pointless to use a `FOR UPDATE` when getting the current roles
>     # since it would lock a row that remains unchanged during the transaction, since updating
>     # the a role merely inserts a new row. Plus, we also rely on information from other
>     # tables such as `realm_archiving`, so it's even more complicated to properly lock
>     # information. For instance, having `query_update_archiving` and `query_update_roles`
>     # both locking rows in different tables might end up in a deadlock if the `FOR UPDATE`
>     # locks are not applied with care. A simpler solution might be to use a dedicated lock
>     # for all transactions involving certificates for a given realm (or, for a given
>     # organization).

**Comment by mmmarcos** [comment]
Moving this out of the v3.0 release back to the backlog.

**Comment by touilleMan** [comment]
done in #8210
