### ISSUE TITLE
Migrate `libparsec_protocol` tests: `invite.rs`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5296]
- [x] #5298
- [x] #5311
- [x] #5306
- [x] #5316
- [x] #5320
- [x] #5324
- [x] #5328
- [x] #5332
- [x] #5334
- [x] #5308
- [x] #5310
- [x] #5314
- [x] #5317
- [x] #5321
- [x] #5325
- [x] #5329

**Comment by TimeEngineer** [comment]
`invited_cmds` are missing

**Comment by FirelightFlagboy** [comment]
`invite.rs` did seems to test `invited_cmds` :thinking:

**Comment by TimeEngineer** [comment]
I found `invite_info`

**Comment by FirelightFlagboy** [comment]
You can edit the body of the issue to add the one that are missing

**Comment by FirelightFlagboy** [comment]
All the items are resolved, so closing this issue
