### ISSUE TITLE
[🐛 | Bug]: Parsec backend docker image don't support S3 object storage

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5367]
### Version

2.16

### What platforms you were running our software when the bug happened ?

Linux

### What happened ?

The docker image of the parsec-backend don't support connecting to an S3 object storage.

The reason is that we remove the `boto3` dependency in the image

https://github.com/Scille/parsec-cloud/blob/9cdaec0075dea51108c648dc86dc843a4163a5fa/packaging/server/res/build-backend.sh#L20

**Comment by mohanadft** [comment]
HI @FirelightFlagboy 
I would like to take it, all the thing is removing `boto3` ?

**Comment by FirelightFlagboy** [comment]
Hello @mohanadft 

yes, also `botocore`

**Comment by FirelightFlagboy** [comment]
Resolved in #5418
