### ISSUE TITLE
Fix modal dismissing

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#5429]
Modal dismissing is controlled by the parent of the opening modal

```typescript
await modalController.createModal({
  ...
  canDismiss: async (data, role) => {
    if (modalRole === MsModalResult.Confirm) {
      return true;
    }

    const alert = await createAlert(
      t('MsAlertConfirmation.areYouSure'),
      t('MsAlertConfirmation.infoNotSaved'),
      t('MsAlertConfirmation.cancel'),
      t('MsAlertConfirmation.ok'),
    );
    await alert.present();
    const { role } = await alert.onDidDismiss();
    return role === MsModalResult.Confirm;
  } 
  ...
});
```

The goal is to ask the user if they really want to close the modal before closing it. But the question happens when the modal already has called `modalController.dismiss(MsModalResult.Cancel)` and done some cleanup. 
`canDismiss` should probably always be put to `false` here in case of big modals, and the modal should have a `closeRequest` when the `X` button is clicked to ask the question before dismissing.

**Comment by nguyenluan2001** [comment]
Hi sir, can i work on this issue?
