### ISSUE TITLE
Remove `@electron/rebuild` from `client/electron/package.json`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5476]
When doing `npm run electron:release`, the following message is displayed:

```
@electron/rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies
```

**Comment by luansmartr** [comment]
Can i work on this issue?

**Comment by FirelightFlagboy** [comment]
Sure @luansmartr 

If you haven't done it already, read [How to contribute code](https://github.com/Scille/parsec-cloud/blob/master/CONTRIBUTING.md#contributing-code)

**Comment by luansmartr** [comment]
Sure dude, assign this to me

**Comment by FirelightFlagboy** [comment]
Did you send the [Contributor Assignment Agreement (CAA)](https://github.com/Scille/parsec-cloud/blob/master/CONTRIBUTING.md#send-us-a-contributor-assignment-agreement) ?

**Comment by luansmartr** [comment]
I will send now

**Comment by luansmartr** [comment]
thank man

**Comment by FirelightFlagboy** [comment]
Hello @luansmartr, 

Can you confirm that you've sent the email with the CAA ? 
The people that manage the email contact@scille.fr couldn't find your email.

**Comment by luansmartr** [comment]
![Screenshot_20231014-143119_Outlook](https://github.com/Scille/parsec-cloud/assets/111273077/2ccb1296-88c8-48b4-9ff2-11074b514971)
I already send it

**Comment by FirelightFlagboy** [comment]
Thanks for you for this new confirmation, I'll ask them again

**Comment by FirelightFlagboy** [comment]
I've sent you an email to luan.nguyen@smartr.co can you reply to it, thanks in advance
