### ISSUE TITLE
Add server log on handlers notify and listen

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#5478]
Add this logs on debug level on Parsec V2:

- all request payload
- notify event on handles

Add this logs on info level:

- listen event on handles

**Comment by vxgmichel** [comment]
After investigation, debug logs already exist for request payloads:
https://github.com/Scille/parsec-cloud/blob/3c65dd012b2a645c3d2afc5f85bec26db4961f34/server/parsec/asgi/rpc.py#L601-L614

I'll check the server configuration.

**Comment by vxgmichel** [comment]
Done here: https://github.com/Scille/parsec-cloud/pull/7427
