### ISSUE TITLE
Confusing icon for ms-informative-text

### ISSUE THREAD

**Issue by NicoTuxx** [Scille/parsec-cloud#5593]
Confusing icon:
 - "You can access to your new organization" the arrow before the phrase is bizarre, seems like something that will deploy content

**Comment by fabienSvtr** [comment]
![Image](https://github.com/Scille/parsec-cloud/assets/81075511/6e78c458-faf6-4430-a1a4-2989f661e3eb)

Need to be updated with filled caret icon
