### ISSUE TITLE
`validate_manifest` `test` of `CertificatesOps` is difficult to implement for `revoked` `user` 

### ISSUE THREAD

**Issue by TimeEngineer** [Scille/parsec-cloud#5628]
It needs the `with_server`
Should we add manually all certificates without `TestbedEnv` ?

**Comment by touilleMan** [comment]
`with_server` should be avoided as much as possible (only use it with transport-related tests such as ones in libparsec_client_connection)

**Comment by TimeEngineer** [comment]
An example when you avoid `with_server`:
In this example:
If you mock the server with custom hook, if you changes later the users or devices
The certificates would not be the same as the server, but the number of certificates should be valid, hence the test is valid, but corrupted.

```Rust
#[parsec_test(testbed = "minimal", with_server)]
async fn minimal(env: &TestbedEnv) {
    let alice = env.local_device("alice@dev1");

    let ops = certificates_ops_factory(env, &alice).await;

    let index = ops.poll_server_for_new_certificates(None).await.unwrap();

    p_assert_eq!(index, env.template.certificates().count() as IndexInt);

    ops.stop().await;
}
```
