### ISSUE TITLE
Add documentation for "Recovery Device" feature

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#5630]
The "recovery device" feature is not documented in the [User Docs](https://docs.parsec.cloud/).

**Comment by FirelightFlagboy** [comment]
If we plan to do the french version alongside, that would be blocked by #5637

**Comment by mmmarcos** [comment]
> If we plan to do the french version alongside, that would be blocked by #5637

I wouldn't say "blocked" as this issue will only add more lines to translate in the `.po` file
