### ISSUE TITLE
Update french translation for documentation

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5637]
By running:

```shell
sphinx-intl update -p _build/locale/ -l fr
```

We could see that some translation need to be updated:

```git-status
 M docs/locale/fr/LC_MESSAGES/adminguide.po
 M docs/locale/fr/LC_MESSAGES/cryptography.po
 M docs/locale/fr/LC_MESSAGES/history.po
 M docs/locale/fr/LC_MESSAGES/userguide.po
```

**Comment by FirelightFlagboy** [comment]
`powrap` is archived cf the repo: https://github.com/AFPy/powrap

**Comment by mmmarcos** [comment]
> `powrap` is archived cf the repo: https://github.com/AFPy/powrap

The AFPy decided to move all its repos from GitHub to their Gitea instance, this is the case of [powrap](https://git.afpy.org/AFPy/powrap) which is part of [poutils](https://git.afpy.org/AFPy/poutils).

**Comment by FirelightFlagboy** [comment]
I've create a PR (#5642) that add `poutils`, that way we would know for certain which translation need to be updated.

**Comment by FirelightFlagboy** [comment]
With `powrap` added in #5642, the translation didn't need to be updated
