### ISSUE TITLE
Docs: refere to the new HOSTING documentation

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5649]
In `docs/userguide/new_organization.rst` we refer to the file `HOSTING.md` that was removed.

We need to update the link to reference the document `_doc_adminguide_hosting` (`docs/adminguide/hosting/index.rst`)

**Comment by gurjot03** [comment]
please assign me

**Comment by FirelightFlagboy** [comment]
Hello @gurjot03, thank you for your interest.

I've assigned you to this issue.
I will ask you to read [How to contribute](https://github.com/Scille/parsec-cloud/blob/master/CONTRIBUTING.md#contributing-code) as we would need a `Contributor agreement` from you.

If you have further questions regarding this issue, don't hesitate to ask them.

Regards

**Comment by gurjot03** [comment]
@FirelightFlagboy I have sent the contributor agreement mail. Please Check the PR. I have made the changes needed

**Comment by FirelightFlagboy** [comment]
I will take a look next monday ;)
