### ISSUE TITLE
[🚀 | Feature request]: How to include changelog in v3 client apps ?

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5761]
### What you would like to accomplish

The previous v2 client app provide a changelog modal that displayed the file `HISTORY.rst` (formatted in HTML).

With the v3 client app, we only display a mocked changelog. 

### How the feature should work

We should find a process to list the change that append during development that affect the user.
We currently use `rst` files but should we keep it that way ?

List the change is only half of the work since we need to display it to the user when required.

**Comment by touilleMan** [comment]
Implemented by https://github.com/Scille/parsec-cloud/issues/5765
