### ISSUE TITLE
Document PostgreSQL supported version

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#5766]
Context:
* A problem was identified during database migration in an environment with PostreSQL v11. 
* The Parsec Server installation guide suggests using v16 in the [docker compose file](https://docs.parsec.cloud/en/latest/adminguide/hosting/index.html#the-docker-compose-file). 
* There is also this (legacy?) open issue: https://github.com/Scille/parsec-cloud/issues/2850

We should check which PostgreSQL versions are use in known Parsec deployments and fix a version to be used in our tests/docs. 

Maybe we can also add notes/instructions/checklist for upgrading PostgreSQL version (i.e. update docs, update tests, etc.). This could be added to `parsec-cloud-saas-deploy`.

See: https://en.wikipedia.org/wiki/PostgreSQL#Release_history

## TODOs

- [x] #5837
- [x] #5839
- [x] Update deployement documentation to state to use postgreSQL v14

**Comment by FirelightFlagboy** [comment]
We plan to use the v14
