### ISSUE TITLE
[rfc-1005] Provide CLI to remove realm vlobs

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#5782]
The goal of this issue is to provide a CLI to prevent the migration from v2 to v3 to being blocked by a workspace forever in maintenance.

A workspace could be forever in maintenance if it was owned by a single user that was revoked during its re-encryption.

The CLI should provide a way to remove `realm vlobs`.

**Comment by touilleMan** [comment]
v2-to-v3 migration has been dropped, closing.
