### ISSUE TITLE
GUI: Copy an entry

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#5821]
Copy an entry to another location withing the same workspace.

Something like `(clientHandle: Handle, workspaceHandle: Handle, source: FsPath, destination: FsPath) -> ??`

**Comment by touilleMan** [comment]
@Max-7 can we implement this in pure javascript for the moment ? (considering this as a short term solution, and have the proper Rust copy API for Parsec 3.1+)

**Comment by Max-7** [comment]
Done in typescript in #7429
