### ISSUE TITLE
[🎨 Style] • Correct style issues

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#5860]
- [x] #5866 
- [x] #5864 
- [x] #5862 
- [x] #5868
- [x] #5875 
- [x] #5883
- [x] #5874 
- [x] #5770 
- [x] #5951
- [x] #5961 
- [x] #5953 
- [x] #5992 
- [x] #5999
- [x] #6019 
- [x] #5998

**Comment by FirelightFlagboy** [comment]
Closing, all sub-task are fixed
