### ISSUE TITLE
Add documentation for "Offline mode"

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#5871]
The "offline mode" was introduced in https://github.com/Scille/parsec-cloud/pull/3895 and released in [2.16.0](https://github.com/Scille/parsec-cloud/blob/releases/2.16/HISTORY.rst#parsec-v2160-2023-10-31) but it is not documented in the [User Docs](https://docs.parsec.cloud/).

Keep in mind that we want this feature to be named "offline mode" (instead of the "remanence mode" which is sometimes used internally to refer to this feature).

**Comment by mmmarcos** [comment]
BTW there is this dialog which is a bit confusing: 

![image](https://github.com/Scille/parsec-cloud/assets/786907/100095da-d567-45cc-bf53-c7695fa41fb8)

**Comment by FirelightFlagboy** [comment]
To access, you need to right click a workspace
