### ISSUE TITLE
`ExportRecoveryDevicePage` "downloaded file" label and the success toast appears before we really download the file

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#5912]
Now, when the user clicks on "Download", they are almost instantly given the information about their file. If the user stops downloading, they can no longer repeat the download action.

**Comment by Max-7** [comment]
I don't think there's a way to know if the user actually downloaded the file. All you can do is hope they didn't cancel the download.

We may need some UI improvements (a button `Re-download` for example).
