### ISSUE TITLE
[🐛 Bug] The Recovery files page appears briefly when the user click on `Back to my devices`

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#5926]
When the user creates Recovery files (_Devices_/_Recovery files_) and goes back to these devices, using the `Back to my devices` button, the first step of `Recovery Device` page appears. 

https://github.com/Scille/parsec-cloud/assets/81075511/f25bb231-bd8b-4dc0-b594-42f7d2bb24ce

-- 

Same bug in this issue [#5900](https://github.com/Scille/parsec-cloud/pull/5900)

**Comment by Max-7** [comment]
Thought it would just be a simple calling order problem here https://github.com/Scille/parsec-cloud/blob/b44316a4c44aeecbdbba365f4aaf85da4913efd3/client/src/views/devices/ExportRecoveryDevicePage.vue#L235 but it's a bit more complicated.

I tried with
```typescript
// Make routerNavigateTo async 
export async function routerNavigateTo(routeName: string, params: any | null = null, query: any | null = null): Promise<void> {
  params = params || {};
  params.handle = router.currentRoute.value.params.handle;

  await router.push({
    name: routeName,
    params: params,
    query: query,
  });
}

// Change order is which the variables are re-assigned
async function onBackToDevicesClick(): Promise<void> {
  await routerNavigateTo('devices');
  recoveryFileDownloaded.value = false;
  recoveryKeyDownloaded.value = false;
  state.value = ExportDevicePageState.Start;
}
```
but I still get some flickering.
