### ISSUE TITLE
[🚀 | Feature request]: Bulk re-encryption of workspaces

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#5939]
### What you would like to accomplish

When a user is revoked, the workspaces in which it was participating must be re-encrypted by users having an `Owner` role on those workspaces.

Currently, re-encryption is performed on each workspace by clicking, one by one, on the red padlock.

This is a relatively frequent operation in a high turnover context so the request is to add a function enabling bulk re-encryption of all workspaces for which the `user` performing the action has the `Owner` role.

### How the feature should work

It is proposed to add a global action to re-encrypt all workspaces owned by a user.

This action will be displayed in the workspace list via a button or similar (e.g. next to "Create a new workspace" ). The user will be asked to confirm before re-encryption.

**Comment by FirelightFlagboy** [comment]
Fixed in #5950
