### ISSUE TITLE
[🚀 | Feature request]: Display message if workspace has a single owner

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#5940]
### What you would like to accomplish

A common best practice is to define at least two users with an `Owner` role for shared workspaces. This reduces the risk of someone leaving the organization and leaving "orphan" workspaces (no user has the `Owner` role).

### How the feature should work

When a user creates a workspace, it is automatically assigned the `Owner` role. It is not possible (nor desirable) to _force_ the user to give this role to another user.

It is proposed to display a message (information or warning) in the workspace sharing dialog, suggesting to add another user with the Owner role if the workspace is meant to be shared. The message will be displayed only if:
* the user has the `Owner` role for that workspace
* there is no other user having the `Owner` role

**Comment by FirelightFlagboy** [comment]
Fixed in #5944
