### ISSUE TITLE
[🚀 | Feature request]: Customize project logo on invitation e-mails

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#6113]
### What you would like to accomplish

The project logo used in the invitation e-mails sent by the Parsec server should be configurable. This is specifically useful for on-premise deployments.

Currently invitation mails are sent in the following cases:
- join an organization
- add a new device
- shamir recovery

### How the feature should work

During the Parsec server deployment, there should be a way (config file? env variable?) to specify the path to an image file that will be used as project logo  in invitation e-mails.

The required format and recommended size of the image should be documented in the deployment guide.

If the image is loaded dynamically (on runtime): there should be a default fallback image (or a placeholder image) in case the file is not found.

---
## TODOs

- [ ] Verify on Linux that template can be overwritten directly

**Comment by Landeers** [comment]
Template can be overwritten directly on install folder.
