### ISSUE TITLE
[🐛 Bug] Visual stutter during transitions `HomePage`

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#6129]
To reproduce the bug:

https://github.com/Scille/parsec-cloud/assets/81075511/0601bedf-fa9b-43b7-a9e7-8e5dc5100ced

**Comment by Max-7** [comment]
It seems to be linked to `flex-direction: column` in https://github.com/Scille/parsec-cloud/blob/0b67a1b319748b5c7013fdd11a3c0e181543aad2/client/src/views/home/HomePage.vue#L278. When I remove it, the transition seems a little bit smoother (still has some issues though).

I was also wondering why the `header` was defined after the content on this page https://github.com/Scille/parsec-cloud/blob/0b67a1b319748b5c7013fdd11a3c0e181543aad2/client/src/views/home/HomePage.vue#L43 and wether it could collerate to the animation playing weirdly.
