### ISSUE TITLE
[🐛 | Bug]: missing registry key

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#6142]
### Parsec version tested on:

2.16.3

### Platforms tested on:

Windows

### Bug description:

`add_parsec_mountpoint_directory_to_quick_access` function writes registry entry but keys can be missing which results in an error that makes it impossible to launch the client.
<https://github.com/Scille/parsec-cloud/blob/v2.16.3/parsec/core/win_registry.py#L276>

`winreg_write_user_dword` function should create registry key before insert value.

### Relevant output:

![image](https://github.com/Scille/parsec-cloud/assets/10208225/e09a9f2f-ff32-42c0-8e11-d139aa4a05c6)

**Comment by mmmarcos** [comment]
> `winreg_write_user_dword` function should create registry key before insert value.

This should probably be done for any key before insert.

**Comment by vxgmichel** [comment]
Fixed in #6177
