### ISSUE TITLE
[🐛 | Bug]: Toasts display incorrectly when a modal is opened

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#6162]
### Parsec version tested on:

3.0.0

### Platforms tested on:

Linux

### Bug description:

![Screenshot 2024-01-15 073138](https://github.com/Scille/parsec-cloud/assets/18075498/e1722b03-a0c1-4717-b0df-2554c99caf67)

**Comment by Ironicbay** [comment]
Easily reproduced on the login page 
![Uploading Screenshot 2024-01-15 at 13.48.28.png…]()
