### ISSUE TITLE
Add documentation for PARSEC_SPONTANEOUS_ORGANIZATION_BOOTSTRAP 

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#6173]
The ability for regular users to create organizations within a Parsec Server instance is configured via the `PARSEC_SPONTANEOUS_ORGANIZATION_BOOTSTRAP` variable during deployment. 

This is not well documented in [Parsec Server configuration](https://docs.parsec.cloud/en/latest/adminguide/hosting/index.html#parsec-server-configuration) and it is particularly important for self-hosted deployments.

```
# Allow bootstrapping organizations without prior creation.
PARSEC_SPONTANEOUS_ORGANIZATION_BOOTSTRAP=false
```
We should add some more detail to the variable description: briefly explain what does it means to bootstrap an organization (link to the relevant section in the docs?), which users/profiles are allowed to do it, what is the default behavior (if variable is not defined), etc..

Also, maybe add a Warning notice suggesting to set the value to `false` for on-premise deployments.

**Comment by FirelightFlagboy** [comment]
The flag is disable by default so this option could be removed from the documentation.

We could also add the info that the user could use `parsec backend --help`

**Comment by mmmarcos** [comment]
> The flag is disable by default so this option could be removed from the documentation.

Can you provide a link to the source code confirming this behavior? 

> We could also add the info that the user could use `parsec backend --help`

:+1:

**Comment by mmmarcos** [comment]
> > The flag is disable by default so this option could be removed from the documentation.
> 
> Can you provide a link to the source code confirming this behavior?

I'll answer myself: this is the default behavior in `click` when `is_flag` is enabled (envvar will be `False` if omitted): 
https://github.com/Scille/parsec-cloud/blob/f675d901eb0d5b8e730b1d5778f999a12e8ad869/server/parsec/backend/cli/run.py#L132-L136

> > We could also add the info that the user could use `parsec backend --help`
> 
> 👍

It seems that `envvar`s are not displayed in the help by default. There is a `show_envvar` option but it [cannot be set globally](https://github.com/pallets/click/issues/2313), so we would need to manually set it for each option.
