### ISSUE TITLE
Add a "open mountpoint folder" button in the GUI

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#618]
Would be cool to have the part showing mountpoint path to evolve according to the view (i.e. showing `C:\Users\gbleu\parsec_mnt\w1`, then `C:\Users\gbleu\parsec_mnt\w1\subfolder` when entering a subfolder in the GUI

On top of that this path could be clickable to easily open the file explorer at this location
![image](https://user-images.githubusercontent.com/3187637/62773376-4c5ad400-baa2-11e9-8c7b-ebce8b802045.png)

A menu button to do the same from the workspace list view would be great too:
![image](https://user-images.githubusercontent.com/3187637/62773485-8cba5200-baa2-11e9-82d7-25ef26a0f3de.png)

**Comment by Max-7** [comment]
@touilleMan second part is already implemented. You can click on the big blue folder to open the workspace in the explorer. Maybe not the most obvious way to do it but it's there :p

**Comment by Max-7** [comment]
Clickable mountpoint implemented in https://github.com/Scille/parsec-cloud/commit/0276d0de470efa8fbf6787bc82929c7176e7f0cc.
