### ISSUE TITLE
Ensure Shamir & Realm archiving related certificates are supported in parsec v3 client & server

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#6257]
The full feature doesn't need to be implemented right away, however organization with those certifcates already present must handle the correctly: the server should pass those certificates among with the others, and the client should validate & integrate them correctly in it storage

**Comment by mmmarcos** [comment]
> ...organization with those certifcates already present must handle the correctly:

@touilleMan since we are no longer considering v2 compatibility, this seems no longer relevant. Please add more info if this is still needed.

**Comment by touilleMan** [comment]
as you say, this is no longer needed
