### ISSUE TITLE
Server test API command

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#6339]
List of APIv4 commands that are missing some or all tests on the server:

- Anonymous
  - [x] #6803
- Invited:
  - [x] #6707
  - [x] #6711
  - [x] #6746
  - [x] #6764
  - [x] #6769
  - [x] #6775
- Authenticated:
  - [x] #6462
  - [x] #6834
  - [x] #6689
  - [x] #6732
  - [x] #6741
  - [x] #6751
  - [x] #6767
  - [x] #6771
  - [x] #6749
  - [x] #6684
  - [x] #6480
  - [x] #6685
  - [x] #6687
  - [x] #6686
  - [x] #6616
  - [x] #6619
  - [x] #6629
  - [x] #6630
  - [x] #6631
  - [x] #6632
  - [x] #6633

**Comment by mmmarcos** [comment]
@touilleMan is there a way to know which tests are missing? (e.g. listing the response status that are missing a test)

**Comment by mmmarcos** [comment]
I moved `pki_enrollment` tests to #6974

**Comment by FirelightFlagboy** [comment]
All issues are complete, closing
