### ISSUE TITLE
Consider replacing terminal-spinner crate in CLI

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#6385]
The `terminal-spinner` crate used in CLI, depends on the `atty` crate which triggers a [dependabot alert](https://github.com/Scille/parsec-cloud/security/dependabot/130).

https://github.com/Scille/parsec-cloud/blob/3d2099109d57e85b0f004f3b0ea41a0290972788/cli/src/utils.rs#L11

There doesn't appear to be any fix in `atty` or `terminal-spinner` at this time.

Maybe consider using [spinner](https://github.com/fgribreau/spinners)?

**Comment by FirelightFlagboy** [comment]
We could also consider `teriminal-spinner` unmaintained since the last pushed commit is from 3years https://github.com/mainrs/terminal-spinners-rs/commit/d384d10a993f3a50dff4ca9e2f862346fb240554
