### ISSUE TITLE
[🚀 | Feature request]: Request T&Cs acceptance during onboarding

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#6439]
### What you would like to accomplish

Feature for Parsec V3

For on-premise development, it should be possible to ensure users have accepted specific Terms and Conditions (T&Cs). Acceptance is a prerequisite for using Parsec: users must not be allowed to use the software until these conditions have been accepted. It should be possible to list (extract) the users who have accepted the conditions and the date of acceptance.

### How the feature should work

- When a user clicks the e-mail invitation link, Parsec should open and display:
  - a link enabling the user to open the T&Cs and consult them on his or her web browser;
  - a checkbox indicating acceptance of the T&Cs;
  - a "Next" button to continue the procedure, clickable only if the checkbox is checked;
  - a "Cancel" button.
- At the end of the registration procedure, the date of acceptance will be saved in the database for the user.
- The list of users who have accepted the T&Cs with their date can be exported in CSV format by server administrators via an API call (identical to statistics export).
- The T&Cs will be configured via a link to a PDF file in the server configuration (backend). If no configuration is present, the T&Cs will not be displayed, and the user will be able to register without any prerequisites.
- The T&C will remain available for consultation via the application menu once logged-in.

### Checklist

- [x] #7633
  - On the enrollment screen, a checkbox should be added, indicating "I accept the CGU". => UI 0.5h.j
  - The enrollment process is blocked as long as the checkbox is unchecked (i.e. "Next" button is disabled).
  - On this same screen, a link must be added to the CGU (e.g. a static file added to the Parsec server). => UI 0.5h.j
    - CGU are server configured, not organization
  - Parsec client retrieves link configuration from backend. => 2h.j
  - Displays the checkbox only if a link to the CGU is present (backend link configuration). => UI 1h.j
  - Information of date of acceptance should be sent to the server
  - Add link on Menu for CGU to be able to read it at anytime. => UI 1h.j
- [x] #7632
  - Information about acceptance of the CGU must be stored in the database (enrollment route will need to be updated + storage : acceptance date + DB schema migration). => 4h.j
  - Export via backend API+CLI (csv). => 2h.j

For later:
- #8664

Not to do :
- Optional: Display the CGU when a user enrolled before the implementation of the functionality logs in, so that he/she also accepts them. => 10h.j

**Comment by mmmarcos** [comment]
Closing this as it has been implemented in #7632 & #7633

Only #8664 remains to be done later.
