### ISSUE TITLE
Add Sentry support

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#6458]
This needs further investigation.

## Context

The following alternatives were considered to implement Sentry support:
- **JS-side**, then error reports from Rust should be sent to JS code in order to upload them to Sentry. This raises some questions: how would Rust error reports be displayed? would they be sufficiently readable? 
- **Rust-side**, specific bindings should allow JS code to sent error reports to Rust in order to upload them to Sentry. Same questions apply as for the previous case.
- **Both JS & Rust** then two dedicated Sentry projects will run (one for JS, one for Rust) and error reports would be uploaded separately from JS and Rust code. 

The approach recommended by Sentry is to set up multiple projects for finer granularity:

> [How Many Projects Should I Create?](https://docs.sentry.io/organization/getting-started/#how-many-projects-should-i-create)
> 
> You could theoretically put all your errors into a single project, as this isn't limited in [sentry.io](https://sentry.io/)
> 
> However, setting up multiple projects to reflect your application with finer granularity helps makes errors more visible and actionable, which can have a big impact on your team's productivity.
> 
> Here are some points to consider:
> - If your application's source code is managed in multiple repositories, create a separate project for each repo.
> - If your app is made up of several micro-services, split them into projects accordingly.
> - If you have a monolithic codebase, set up separate projects for the backend and frontend.
> - Give each language its own project. For example, if your backend code contains NodeJS and Java components, separate those into two different projects.

## Initial POCs

Some tests were made in the following PRs: 
- Attempt to add Sentry JS-side: #5629
- Attempt to add Sentry Rust-side (bindings) #5566

## Current status

- [x] Create Sentry dedicated projects & teams
  - Project `parsec3-frontend` --notifies--> `scille-frontend`
  - Project `parsec3-libparsec` --notifies--> `scille-rust`
- [x] Setup Sentry in JavaScript code (Electron) & Rust bindings
- [ ] https://github.com/Scille/parsec-cloud/issues/7831
- [ ] Set Sentry DSN environment variables
- [ ] Fix Sentry issue with missing debug information

**Comment by FirelightFlagboy** [comment]
@mmmarcos I would suggest to not try sharing 1 sentry configuration between rust & js/electron.

I would recommend to have first 2 sentry's client:

- One on the rust side
- One on the js side
