### ISSUE TITLE
Support confinement point in workspace ops

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#6489]
Confinement point (to skip synchronization of a subset of a workspace depending on it path) is not implemented now

Reference PR in parsec v2: https://github.com/Scille/parsec-cloud/pull/1359

TODO list, taken for the v2 PR:

<details>

<summary>Already done:</summary>

- [x] Add confined entry set to local manifest
   https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/types/schema/local_manifest/local_folder_manifest.json5#L26-L33
- [x] Add filtered entry set to local manifest (filtering entries from other clients)
  https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/types/schema/local_manifest/local_folder_manifest.json5#L34-L41
- [x] Define a confinement pattern list
  https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/client/src/workspace/default_pattern.ignore#L1-L94

</details>

To be done:
- [x] #7705
- [x] #7706
- [x] #7828

The simplest way would be to include the `libparsec/crates/client/src/workspace/default_pattern.ignore` using `include_str` and use that value as fallback in case no file is set to read the pattern from

To be done later:
- #7707
- #7704

**Comment by vxgmichel** [comment]
Reference PR in parsec v2: https://github.com/Scille/parsec-cloud/pull/1359

TODO list, taken for the v2 PR:
- [x] Add confined entry set to local manifest
   https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/types/schema/local_manifest/local_folder_manifest.json5#L26-L33
- [x] Add filtered entry set to local manifest (filtering entries from other clients)
  https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/types/schema/local_manifest/local_folder_manifest.json5#L34-L41
- [x] Define a confinement pattern list
  https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/client/src/workspace/default_pattern.ignore#L1-L94
- [ ] Add dedicated icons in the GUI for confined files
  - The `confinement_point` field is exposed through the bindings (not null if confined):
  https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/bindings/electron/src/index.d.ts#L974
  - TODO: create a dedicated issue for megashark
- [ ] Update sync monitor to manage the syncing of no-longer-confined entries
  - Plenty of TODOs in `merge.rs`
    https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/client/src/workspace/merge.rs#L212-L215
  - But the manifest methods are implemented already:
    https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/types/src/local_manifest.rs#L799-L810
- [ ] Implement the procedure for changing filter pattern
- [ ] Make the pattern list configurable
  - TODO: add the `prevent_sync_pattern` path to `config.rs`:
    https://github.com/Scille/parsec-cloud/blob/fc76ec52b7ac92370d3ed24cce3cbd14c50b5e9b/libparsec/crates/client/src/config.rs#L45

**Comment by FirelightFlagboy** [comment]
All tasks are done, closing
