### ISSUE TITLE
Remove `unreferenced_chunks` table from client storage

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#6498]
https://github.com/Scille/parsec-cloud/blob/c40ad7d297aa05b6b0e2d1171b1c0ce70c9e01ff/libparsec/crates/platform_storage/src/native/sql/create-temp-unreferenced-chunks-table.sql#L1-L5

It seems to be never used, and given it is a `TEMP TABLE`, it is only accessible by the connection that created it (and hence we shouldn't have backward compatibility issue)

**Comment by FirelightFlagboy** [comment]
https://github.com/Scille/parsec-cloud/blob/4caca972b97246e0460bc89cba1d352aa62c05fe/oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs#L581-L623

**Comment by FirelightFlagboy** [comment]
https://github.com/Scille/parsec-cloud/blob/4caca972b97246e0460bc89cba1d352aa62c05fe/oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs#L542-L550

**Comment by FirelightFlagboy** [comment]
https://github.com/Scille/parsec-cloud/blob/4caca972b97246e0460bc89cba1d352aa62c05fe/parsec/core/fs/storage/workspace_storage.py#L261-L265

**Comment by touilleMan** [comment]
After more digging, this table is used in the remanence system, so we will decide what to do with it in #6490
