### ISSUE TITLE
Implement initial key rotation with legacy workspace

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#6500]
see 
https://github.com/Scille/parsec-cloud/blob/c40ad7d297aa05b6b0e2d1171b1c0ce70c9e01ff/libparsec/crates/client/src/certif/realm_key_rotation.rs#L116-L124

**Comment by mmmarcos** [comment]
this one is no longer necessary since we've dropped compat with v2. The strategy would be to use a script that runs on sequester data if ever required for migration.
