### ISSUE TITLE
Show mountpoint in Wirdows Explorer left panel not working

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#674]
option enabled:
![image](https://user-images.githubusercontent.com/3187637/64703314-7a21a700-d4ac-11e9-97fb-639877a4e16f.png)

But nothing in the explorer:
![image](https://user-images.githubusercontent.com/3187637/64703361-8c034a00-d4ac-11e9-9680-2088efeab99f.png)

I've tried to restart the client (and disable the option, restart, then reenable&restart) with no change.
No error logs.

**Comment by touilleMan** [comment]
Could it be because because Parsec is not installed (I working with the repo version) ?
If so, is there something we could do ?

**Comment by Max-7** [comment]
Duplicate of #839, closing this one.
