### ISSUE TITLE
Package `parsec-cli` on a release

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#6765]
Proposed solution:

- Standalone binary
- Included in the base snap
- Another snap
- In docker
- AppImage

**Comment by mmmarcos** [comment]
For the moment this is not a priority:
- Most of the commands are also accessible via Admin HTTP API 
- CLI is not mandatory for our SaaS deployment  
- CLI is required for the sequester, but this feature is not yet implemented
 
Regarding the proposed solutions, it might be interesting to package separately --> to be discussed later.

**Comment by FirelightFlagboy** [comment]
First, we're gonna provide a standalone binary and see how it's goes
