### ISSUE TITLE
Workspaces does not display on both sidebar and page after login

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#6781]
Switching to homepage and back to workspacespage fixes it

![image](https://github.com/Scille/parsec-cloud/assets/41511029/c828c277-55f0-4d1a-ba3f-4b7b24caa75a)
![image](https://github.com/Scille/parsec-cloud/assets/41511029/29a7d5fb-7f44-4bf5-a01b-3ff2265c94fb)

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/88acab3b2d8ef7e96d175adeda1d6502996820b8
