### ISSUE TITLE
[MS] Shortcuts don't work on macOS

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#6859]
Shortcuts:
- show/hide password
- switch grid/list view
- Delete text with `Cmd` + `Backspace`

**Comment by Ironicbay** [comment]
The grid/list view is a priority issue with the hotkey management https://github.com/Scille/parsec-cloud/issues/6790
The other shortcuts work fine on my end. Can you explain the steps on how to replicate ?

**Comment by fabienSvtr** [comment]
> The grid/list view is a priority issue with the hotkey management [#6790](https://github.com/Scille/parsec-cloud/issues/6790) The other shortcuts work fine on my end. Can you explain the steps on how to replicate ?

**Show/hide password**
Open Parsec / Choose an organization / `Cmd + /` 


**Delete text**
Select a file / Rename / `Cmd + Backspace` 

In both cases, nothing happens.
