### ISSUE TITLE
Handle dispatch between multiple track in snapcraft

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#6942]
Update the workflow `publish` to be able to push a snap to multiple track (`latest`, `nightly`, `v{MAJOR}`)

**Comment by mmmarcos** [comment]
For the moment, we do not want to force existing users to upgrade from v2 to the v3.0 (public) release. 

This means that the **default version in snap should remain the 2.x**, possibly until all organisations have been migrated to v3.x.

So, instead of adding new snap tracks (at least right now), we could update docs to recommend installing V3 via AppImage.

**Comment by FirelightFlagboy** [comment]
Fixed by #7722
