### ISSUE TITLE
Add option menu (popover) on workspaces in Sidebar

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#6966]
![Image](https://github.com/Scille/parsec-cloud/assets/81075511/83664517-8fb0-4ed1-ac48-7fe65e3f7384)

**Comment by mmmarcos** [comment]
This was suggested by Thierry specifically to be able to share a workspace from the workspace page itself.

Currently, the user has to go back to `My Workspaces` and then click on the `...` of the workspace they want to share to get the option.
