### ISSUE TITLE
[MS] Migrate `MyContactDetailsPage` and `DevicesPage` in profile dropdown menu

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#6978]
### Changes
- 1️⃣ The profile dropdown menu will have only `My profile` and `Settings` (in french translate into `Préférences`)
- 2️⃣ `MyContactDetailsPage` and `DevicesPage` will be merge into `My profile` page (like `Settings` page) with 2 tabs:
  - the devices list
  - the authentification (change password)

🌟 You can use the [mockups](https://www.figma.com/file/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?type=design&node-id=29797-33689&mode=design&t=B1th5FnZTupfCjca-11) and/or the [prototype](https://www.figma.com/proto/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?page-id=21196%3A36534&type=design&node-id=21444-38685&viewport=-572%2C-103307%2C1.6&t=t120M1YeKY2RxOHx-1&scaling=min-zoom&starting-point-node-id=27822%3A55245&mode=design) to preview.

![Image](https://github.com/Scille/parsec-cloud/assets/81075511/e74dd33b-d2e3-4506-a006-25e6f5a1893c)

**Comment by Max-7** [comment]
A modal for that is inconvenient, since the `Add` button opens a modal itself. Which may open another modal in case of errors.
