### ISSUE TITLE
Should we remove the field `is_admin` in `UserCertificate` ?

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#7009]
https://github.com/Scille/parsec-cloud/blob/3e94b927422c593412d31cd9265c140cb298816c/libparsec/crates/types/schema/certif/user_certificate.json5#L27-L32

**Comment by TimeEngineer** [comment]
I think yes if we can break the compatibility

**Comment by FirelightFlagboy** [comment]
We are gonna wait before doing anything until we see what we would do about migrating client from v2 to v3.

**Comment by mmmarcos** [comment]
The field was removed in #7107
