### ISSUE TITLE
Functions to create and import recovery devices in the bindings

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#7044]
Should not be a priority since:
1. we're not compatible with v2 recovery devices anyway so we're not expecting any user to import recovery devices created with v2 into v3
2. the keyring should be the most used way to authenticate, and in case a user prefers to use a password, there's less chance of them forgetting it

Also check if this feature could be completly replaced by the shamir.

**Comment by mmmarcos** [comment]
See also #5589

**Comment by mmmarcos** [comment]
Functions for load and save recovery devices already exists in libparsec. See for example:
https://github.com/Scille/parsec-cloud/blob/master/libparsec/crates/platform_device_loader/src/lib.rs#L218-L223

We should check if they work and expose them on the bindings.
