### ISSUE TITLE
[🦋 Final Touch] Workspace name in `WorkspaceSharingModal`

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#7066]
Preview:
![image (1)](https://github.com/Scille/parsec-cloud/assets/18075498/a9bc6b1b-237b-4b79-bfb1-6eb7d2dba728)

Figma:
https://www.figma.com/file/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?type=design&node-id=25763-142399&mode=design&t=pdhSyQjPtaobiBA5-11

**Comment by Max-7** [comment]
Partially done for context menu in #7087
