### ISSUE TITLE
Enlever le bouton POUBELLE dans le wokspace

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#708]
L'icone poubelle renvoie un message "Etes-vous sûr de vouloir supprimer l'espeace de travail ? et si on répond OUI, on reçoit un avertissement "Non Implémenté"
![Capture du 2019-10-05 14-25-02](https://user-images.githubusercontent.com/9845177/66254823-078aab00-e77c-11e9-9d7e-6033655b2556.png)

Tant que la fonction de purge n'est pas implémentée,  il vaut mieux supprimer de l'affichage le bouton de la poubelle

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/44828f4d2a2fd76f449a6d2f9abcfdaaeb6b456e
