### ISSUE TITLE
[🚀 | Feature request]: Port: Bulk re-assignment of workspace rights

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7083]
#5938 should be ported to V3. In principle, this can be fully implemented in the client side.

**Comment by fabienSvtr** [comment]
I created the mockups here: https://www.figma.com/file/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?type=design&node-id=30161-85608&mode=design&t=osMCLS8le0XcIlRB-11
