### ISSUE TITLE
Port: Display message if workspace has a single owner

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7084]
#5940 should be ported to V3. In principle, this can be fully implemented in the client side.

Note that there was a bug report regarding this message : 
> When changing the rights of a user with the owner role, the info message is not present.

**Comment by fabienSvtr** [comment]
We could have a "recommandation" section to encourage the user to carry out important tasks.
![image](https://github.com/Scille/parsec-cloud/assets/81075511/fb5f4c25-313d-4dae-9383-a23644719c03)

**Comment by mmmarcos** [comment]
> We could have a "recommandation" section to encourage the user to carry out important tasks.

@fabienSvtr This seems like a good idea, can you create a separate issue for that feature? BTW Instead of "Recommendations" maybe we can add the notion of security, like "Security checklist" or similar.

**Comment by fabienSvtr** [comment]
> > We could have a "recommandation" section to encourage the user to carry out important tasks.
> 
> @fabienSvtr This seems like a good idea, can you create a separate issue for that feature? BTW Instead of "Recommendations" maybe we can add the notion of security, like "Security checklist" or similar.

Yes, absolutely! We can think about the features we would like to add to this checklist.

**Comment by fabienSvtr** [comment]
I also added an informative message on the sharing workspace modal.

![Image](https://github.com/Scille/parsec-cloud/assets/81075511/00b62ce6-5bdb-481e-be55-232cb987c895

**Comment by mmmarcos** [comment]
Done in #7257
