### ISSUE TITLE
Crash de la connexion lorsque le raccourci existe déjà mais ne fonctionne plus

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#709]
Sous Windows, lorsque pour une raison divers liée par exemple à un arrêt intempestif lors d'une précédente session, on essaie de se loguer de nouveau, Parsec ne peut pas faire le point de montage sur le raccourci cassé existant.
Il faut alors supprimer à la main tous les raccorucis sur le répertoire parsec_mnt pour pouvoir se loguer de nouveau.
Il faudrait systématiquement au moment de la phase de connexion, supprimer prélablement tous les points de montage existants précédents.

**Comment by vxgmichel** [comment]
Too old.
