### ISSUE TITLE
Deux devices tournant sur un même machine virtuelle Windows 10 n'ont pas le même contenu

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#710]
Un permier device `Windows10` est créé sur un environnement virtuel Windows10. Il se synchronise sans problème avec le device Linux du même user.
Pour une raison inconnue, quelques jours plus trad, le contenu en workspace disparaît alors que l'environnement Linux, rien ne change.
On recréer un autre device `Win10bis` dans l'environnement virtuel Windows10. Le contenu des WS est identique à la celui du device Linux.
On se retrouve avec deux devices d'un même utilisateur, tournant sur le même environnement virtuel Windows10, qui n'ont pas le même contenu car l'un est vide.

Liens complémentaires (Manu) : 
- Erreur = https://sentry.io/organizations/scille/issues/1257565263/?project=1212848&query=is%3Aunresolved&statsPeriod=14d
- Erreur qui a l'air d'entrainer ça https://sentry.io/organizations/scille/issues/1257587344/?project=1212848&query=is%3Aunresolved&statsPeriod=14d

Manu : "Pépère sur sa machine virtuelle a créé un device qui n'affiche aucun workspaces
après ça il a créé un nouveau device et là pas de soucis les workspaces apparaissent bien"

**Comment by stefan-contiu** [comment]
dup of #722
