### ISSUE TITLE
A clean install of snap requires including "--dangerous" in cmd line

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#711]
We should not be asked for "--dangerous" in snap install cmd line. 

Command that I had to use to clean install `snap install --classic --dangerous parsec_v1.0.1_amd64.snap`

**Comment by touilleMan** [comment]
`--dangerous` is required to install snap that have been downloaded outside of snapcraft website.

Using snapcraft website should be the only way, so we should stop showing the snap package from the release page to avoid this kind of misunderstanding
