### ISSUE TITLE
[Server v3] Check whether `retry_on_unique_violation` is still necessary for `vlob_update/vlob_create`

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#7116]
The parsec v2 server implementation used a decorator called `retry_on_unique_violation`  for `vlob_create` and `vlob_update`. 

We should check whether those are still necessary for the v3 implementation.

**Comment by mmmarcos** [comment]
A priori, this is no longer required because new API returns RequireGreaterTimestamp for these cases.

**Comment by touilleMan** [comment]
related to #7121

**Comment by touilleMan** [comment]
This is still needed ;-)
https://github.com/Scille/parsec-cloud/blob/6be4d0ce092627ac1929fdd7cd9f1f6d1806286f/server/parsec/components/postgresql/vlob.py#L77-L79

https://github.com/Scille/parsec-cloud/blob/6be4d0ce092627ac1929fdd7cd9f1f6d1806286f/server/parsec/components/postgresql/vlob.py#L116-L118
