### ISSUE TITLE
[Server v3] What to do when unsharing with a revoked user?

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#7118]
There is no status `RealmUnshareStoreBadOutcome.RECIPIENT_REVOKED`, is that on purpose?

https://github.com/Scille/parsec-cloud/blob/f1ccaa55bbe8a8294c6584c47a3afa682dabb48f/server/parsec/components/postgresql/realm.py#L838-L844

The memory does not check for this case:

https://github.com/Scille/parsec-cloud/blob/f1ccaa55bbe8a8294c6584c47a3afa682dabb48f/server/parsec/components/memory/realm.py#L327-L328

**Comment by touilleMan** [comment]
> There is no status RealmUnshareStoreBadOutcome.RECIPIENT_REVOKED, is that on purpose?

No, we should add a `RECIPIENT_REVOKED` status, good catch :+1:
