### ISSUE TITLE
'Register new user' and 'Register new devices' have almost identical UI - one can not know which screen is currently on

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#712]
As the two mentioned interfaces are nearly identical it is hard from UX perspective for a user to differentiate the two. Can we re-design these screens to emphasis to user the selected functionality?

**Comment by Max-7** [comment]
Will be solved by introducing multi-instance : a tab will have a title.

**Comment by Max-7** [comment]
Done.
