### ISSUE TITLE
[Server v3] Check concurrency model for PostgreSQL implementation

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#7121]
A new concurrency model has been introduced in the postgre implementation of the parsec v3 server.

More specifically, requests that depends on a topic (for performing checks) but that do not update said topic should lock it for reading by using a `FOR SHARE` select query on the topic timestamp. On the other hand, the requests that plan to update a given topic should lock it using a `FOR UPDATE` select query on the topic timestamp.

This way, many read requests can run concurrently for a given topic but write requests have to run sequentially while no read request is performed.

This mechanism is already implemented here for the common topic:
https://github.com/Scille/parsec-cloud/blob/f1ccaa55bbe8a8294c6584c47a3afa682dabb48f/server/parsec/components/postgresql/user.py#L163-L176

https://github.com/Scille/parsec-cloud/blob/f1ccaa55bbe8a8294c6584c47a3afa682dabb48f/server/parsec/components/postgresql/user.py#L589-L615

And here for the `realm` topic:
https://github.com/Scille/parsec-cloud/blob/f1ccaa55bbe8a8294c6584c47a3afa682dabb48f/server/parsec/components/postgresql/realm.py#L85-L108

https://github.com/Scille/parsec-cloud/blob/f1ccaa55bbe8a8294c6584c47a3afa682dabb48f/server/parsec/components/postgresql/realm.py#L392-L432

However, this is does not take the last vlob update for a given realm into account.

More generally, this approach should be carefully analyzed and implemented systematically since race conditions could potentially cause non-compliant write operations to be accepted.

**Comment by touilleMan** [comment]
done in #8210
