### ISSUE TITLE
Quit modal can be opened twice

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#7131]
To reproduce the bug:
- `Cmd + Q` or `Ctrl + F4`
- Click on `Quit` on the tray
- Result -> The animation appears twice.

**Comment by Max-7** [comment]
Probably specific to MacOS, can't seem to reproduce on Linux.

Ctrl+Q or Alt+F4 should just trigger the close:
- either we have the tray and it hides the window
- or we don't have the tray and it prompt for the exit question dialog
