### ISSUE TITLE
'Connected' and 'Log Out' labels are not horizontally aligned

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#714]
Once the user logs in, in the left bottom corner, the two labels 'Connected' and 'Log Out' are not aligned (using Ubuntu 18.04.2 LTS bionic).

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/4c1db8d8d0b453ffe5e23d8497f8e4c021e2dc73
