### ISSUE TITLE
Mount/unmount workspaces from the GUI

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#720]
It'd be nice for users to decide which workspaces get mounted in their filesystem.

Those choices needs to be stored somewhere in the configuration.

This is especially useful when a user has a lot of workspaces.

Reported by @tleblond.

**Comment by Max-7** [comment]
I'm not a big fan of letting user chose which workspaces to mount. I would rather add a filtering option on the workspace page. It solves the problem of displaying to many workspaces but still hides the underlying complexity of what a mountpoint is.

**Comment by c4ffein** [comment]
For me, both options are good, I will still implement hided mountpoints in the mountpoint manager as they are useful for one of the functionalities I am developing right now (opening a file at a past timestamp without necessarily seeing a new mountpoint)

**Comment by touilleMan** [comment]
stalled, closing
