### ISSUE TITLE
Prevent double click on login button

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#729]
Login takes some time due to mountpoint mounting.
Given this is done in a job, the gui stays responsive and the user can double click on the login button, resulting in an error.

The simplest way to solve this would be to disable the login button (e.g. replace it by a spinner) once clicked.

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/8203ad1f0dc06797d7303d618a58066f49295bdc
