### ISSUE TITLE
Prevent double login with the same device

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#730]
Right now nothing prevent a user from starting two Parsec client on the same machine and login them both with the same device.
This creates concurrency between the two instances which would use outdated data (given they have both an in-memory cache relying on the assumption they are the only one accessing the underlying sqlite database)

Once https://github.com/Scille/parsec-cloud/pull/684 is merged, only a single instance of Parsec can run at a time and we should be able to implement a cheap check to ensure no double login occurs

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/6065eeaa6ada5c7db3243f6a625d2010480f981d
