### ISSUE TITLE
Mount point crashes when it contains characters forbidden in Windows 

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#762]
Windows (compared to Linux) does not accept certain characters like '<', '>', etc.

To reproduce :
1. Create a workspace using the linux parsec client, having "<><>" in the name. Add files in the workspace.
2. Share the workspace with a windows device.
3. On the windows device, the client shows folder structure well, but the mount point is stale (crashed).

**Comment by touilleMan** [comment]
It seems invalid windows characters are already handled by WinFSP: https://github.com/billziss-gh/winfsp/issues/80#issuecomment-292806035
(WinFSP encode the invalid character into the Unicode Private Area to allow it to go through the kernel, then decode it back before givin it to our code)

I guess the trouble is I this is not done for the name of the mountpoint...

**Comment by touilleMan** [comment]
implemented by #799
