### ISSUE TITLE
Implement T&Cs acceptance server-side

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7632]
- Information about acceptance of the CGU must be stored in the database (enrollment route will need to be updated + storage : acceptance date + DB schema migration). => 4h.j
- Export (users+acceptance date) via backend API+CLI(csv) => 2h.j

referenced into [#6439](https://github.com/Scille/parsec-cloud/issues/6439)

**Comment by FirelightFlagboy** [comment]
I've the following questions:

- Where do we scope that an user have accepted the CGU ?

  At the organization level or the server level ?

- What is used to identify an user ?

  - Do we use its USER_ID
   
    That mean that an user can only accepte the CGU after it's user certificate is upload to the server. 
    That raise the questions what happen if the to the certificate if the user refuse the CGU.

  - Do we use its email
    
    Using it's email mean that we could force the acceptance before the creation of the DEVICE.
    That could also be used to not ask an user to accept the CGU again if it create a new user for a new orgaization with the same device.

- The export is server wide or per organization ?

**Comment by FirelightFlagboy** [comment]
> In theory, you shouldn't be able to refuse the T&C and still get a user certificate : the GUI would not allow the user to continue if T&C are not accepted
> So I would say USER_ID

The problem is that the USER_ID is created during the invitation process when we generate the user certificates by the greeter which is then upload to the server with the command `user_create`.

If we go the USER_ID way that mean change to the invitation process (likely by adding another step that wait the claimer for a message indicating CGU acceptance), is that OK ?

**Comment by mmmarcos** [comment]
> The problem is that the USER_ID is created during the invitation process when we generate the user certificates by the greeter which is then upload to the server with the command `user_create`.
> 
> If we go the USER_ID way that mean change to the invitation process (likely by adding another step that wait the claimer for a message indicating CGU acceptance), is that OK ?

I don't think is worth it to change the invitation process. In that case I would go email. 
@Landeers @touilleMan what do you think ?

**Comment by FirelightFlagboy** [comment]
@touilleMan suggest something clean:

- Have a dedicated API for CGU acceptance.
- The server check if the authenticated user has accepted the CGU else return a HTTP code.
- Have an endpoint that display the configured CGU file.
- The user accept the CGU by generating an certificate (or simple signature ?)
