### ISSUE TITLE
Implement T&Cs acceptance client-side

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7633]
- On the enrollment screen, a checkbox should be added, indicating "I accept the CGU". => UI 0.5h.j
- The enrollment process is blocked as long as the checkbox is unchecked (i.e. "Next" button is disabled).
- On this same screen, a link must be added to the CGU (e.g. a static file added to the Parsec server). => UI 0.5h.j
  - CGU are server configured, not organization
- Parsec client retrieves link configuration from backend. => 2h.j
- Displays the checkbox only if a link to the CGU is present (backend link configuration). => UI 1h.j
- Information of date of acceptance should be sent to the server
- Add link on Menu for CGU to be able to read it at anytime. => UI 1h.j

**Comment by Max-7** [comment]
Depends on #7632
