### ISSUE TITLE
[🐛 | Bug]: Windows error when copying data from V2 to V3 via the File Explorer

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7640]
### Parsec version tested on:

3.0.0-b.11

### Platforms tested on:

Windows

### Bug description:

Context: 
- `Scille-SIRH` organization migration from V2 to V3.
- Parsec V3 installed together with Parsec V2 on Windows (Kelly's PC) 

Steps to reproduce:
1. Login into `Scille-SIRH` for V2 and V3 for some organization.
2. Open a workspace from V2 and another one from V3 (both on Windows File Explorer)
3. Select all directories from V2 workspace and drag-and-drop to V3 workspace (both on Windows File Explorer)
    - Windows displays an error (screenshot needed)
4. Select all directories from V2 workspace and copy to V3 workspace via Ctrl+C, Ctrl+V (both on Windows File Explorer)
    - Windows displays an error (screenshot needed)
5. Open Parsec V2 GUI, enable offline availability for the workspace and wait until 100%.
6. Re-attempt 3 or 4
    - Windows displays an error (screenshot needed)

Eventually, files could be copied, so I'm not sure if it was a synchronization issue. 

We should try to reproduce to have more information.

**Comment by Max-7** [comment]
![Screenshot 2024-06-26 161025](https://github.com/Scille/parsec-cloud/assets/18075498/62be3b95-f4ed-40f9-9377-3d95a636c2d2)

Error is `Invalid MS-DOS function`

**Comment by FirelightFlagboy** [comment]
To enable debug log for the mountpoint, you need to run the executable with the environment `RUST_LOG=libparsec_platform_mountpoint=debug` set

**Comment by mmmarcos** [comment]
I could not reproduce this issue on Linux. Tested with `v3.0.0-b.12.dev.19932+0ef95e2` installed from snap channel `v3/beta`. 

I copied 500+ files ~400MB from a V2 workspace to a V3 workspace with no error or lag. Tested on WS with available offline enabled and on another WS with available offline disabled.
