### ISSUE TITLE
Parsec Backend : Fix token return by POST /organizations API

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#7646]
# Description
When using parsec backend api `POST https://<parsec_domain>/oganizations`, it returns a response with `{ bootstrap_token: 142ea71521946c6adce7364275e27940 }`

This token format is not supported by lib_parsec, exemple : 
`parsec3://192.168.1.25:6777/Organization_test?a=bootstrap_organization&p=142ea71521946c6adce7364275e27940`

When creating an organization with 
`cargo run create-organization --addr parsec3://<domain> --token s3cr3t --organization-id MyOrg`, command returns full bootstrap link with another token format, exemple : 
`parsec3://127.0.0.1:6770/MyOrg?no_ssl=true&a=bootstrap_organization&p=xBCwH_gz-PKRkE_-FsGc8FAy`

# Fix
Parsec backend API should returns complet link as the CLI with good token format.

**Comment by FirelightFlagboy** [comment]
Quick observation:

- `parsec_cli` use `ParsecOrganizationBootstrapAddr.to_url`
- The binding of `ParsecOrganizationBootstrapAddr` directly use `to_url` from the wrapped struct: 
  
   https://github.com/Scille/parsec-cloud/blob/4e761d80123207e49d53e03c6eeb88eea90383b2/server/src/addrs.rs#L355-L357

**Comment by FirelightFlagboy** [comment]
The problem seems to come from

https://github.com/Scille/parsec-cloud/blob/4e761d80123207e49d53e03c6eeb88eea90383b2/server/parsec/asgi/administration.py#L120

here we directly use the bootstrap token without using the same process form `to_url` (`msgpack` + `b64`)
