### ISSUE TITLE
Fix tests involving payload dump in parsec_cli

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7670]
For example: https://github.com/Scille/parsec-cloud/blob/189060b8af1d568cab9901b82422a57c783cf43c/cli/src/tests.rs#L573

See #7510 for context and #7684 for a script that may be helpful.

**Comment by mmmarcos** [comment]
Depends on #7689

**Comment by FirelightFlagboy** [comment]
Fixed by #7961
