### ISSUE TITLE
[🐛 | Bug]: MacOS temp files starting with `._` are not hidden

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#7697]
### Parsec version tested on:

v3.0.0-b.6.dev.19911+76211ba

### Platforms tested on:

MacOS

### Bug description:

Opening a file `filename.ext` on MacOS can create a tmp file `._filename.ext`. They should be filtered on the GUI.

**Comment by Max-7** [comment]
This is because confinment is not yet implemented on V3. This will be fixed by #7487, therefore I'm closing this issue.
