### ISSUE TITLE
[🐛 | Bug]: Workspace contextual menu in sidebar is not always accessible with a large number of workspaces

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#7711]
### Parsec version tested on:

3.0.0

### Platforms tested on:

Any

### Bug description:

In the sidebar, context menus of workspaces can be accessed by hovering over a workspace, which makes `...` appear. With a large number of workspaces taking up the whole height (up to the point where a scrollbar appears), the last few workspaces don't show the `...` when hovering them.

**Comment by Ironicbay** [comment]
Done in #7744
