### ISSUE TITLE
Use system user account for authentication

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#781]

**Comment by Max-7** [comment]
https://www.meziantou.net/how-to-store-a-password-on-windows.htm

**Comment by Max-7** [comment]
Should use [CredUIPromptForWindowsCredentials](https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-creduipromptforwindowscredentialsa) to check for the user's password. See [Chrome implementation ](https://github.com/chromium/chromium/blob/master/chrome/browser/password_manager/password_manager_util_win.cc#L462).

Before Windows Vista it was done with [CredUIPromptForCredentials](https://docs.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-creduipromptforcredentialsa) (chrome has both implementations).

Problem is, CredUIPromptForWindowsCredentials is not available in pywin32 and, to my knowledge, in no Python module at all. CredUIPromptForCredentials does work in Python but uses the Windows Credentials Manager which does not seem to be used on Windows 10 (except by one or two weird apps like Twitch).

To be honest, I can't even make the damn function to work in a C++ app without throwing weird exceptions.

**Comment by touilleMan** [comment]
see Windows Hello api:

- https://bitwarden.com/blog/introducing-desktop-biometrics/
- https://support.1password.com/windows-hello/

**Comment by mmmarcos** [comment]
System authentication has been implemented for `3.0.0`. Won't implement for v2.
