### ISSUE TITLE
Add `SENTRY_AUTH_TOKEN` to CI when building the release

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#7831]
For Sentry to be able to use the sourceMaps, a sentry auth token should be created (sentry > Settings > Developer settings > Auth token) and set to the variable `VITE_SENTRY_AUTH_TOKEN` on the CI so it is used when building a release.

**Comment by mmmarcos** [comment]
Needed to be able to upload [Source Maps](https://docs.sentry.io/platforms/javascript/guides/electron/sourcemaps/)
