### ISSUE TITLE
[🐛 | Bug]: Trial organization is bugged until logout/login after checking out `Subscribe now` and back

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#7869]
### Parsec version tested on:

3.0.0-b.12.dev

### Platforms tested on:

MacOS

### Bug description:

https://github.com/user-attachments/assets/595c1f67-070d-4547-a71d-b7042a96a3d3

**Comment by Max-7** [comment]
This was caused by the link being opened inside Electron because of a missing `_blank` attribute. It has been fixed since.
