### ISSUE TITLE
Invalid URL when inviting a new device

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#789]
When creating a new device and starting Parsec with the resulting URL, a "Invalid url" message is displayed.

**Comment by touilleMan** [comment]
Cannot reproduce with current master (e71cc516d710c0b86fedb9bfdeb673f0863c0a8f) on linux

Isn't it related to https://github.com/Scille/parsec-build/commit/9cb3ea53a9c1d5d4170a61907dd37ad281160303 ?

**Comment by Max-7** [comment]
It's linked to the IPC server.

When starting with the URL argument I get:
```bash
❨✘❩ max@parsec ~/work/parsec-cloud [Jobs: 1] [gui-invitation] [10 change(s)] <VEnv parsec-cloud>
> parsec core gui parsec://saas-demo.parsec.cloud/Test_test01?action=bootstrap_organization&no_ssl=true&token=2eead2c011e4ad9878ffc5854a38b395ecd22279b86994f804bdfc7cad81ed66
[1] 6460
[2] 6461
[2]+  Done                    no_ssl=true
# I printed the URL when the MainWindow is trying to parse it, and it's missing some info.
> parsec://saas-demo.parsec.cloud/Test_test01?action=bootstrap_organization
# From then on, even if I close Parsec, I still have to Ctrl-C.
```

**Comment by Max-7** [comment]
I'm a moron.

**Comment by touilleMan** [comment]
You have to escape URL  to avoid `&` and `?` being interpreted by bash ;-)
