### ISSUE TITLE
CLI operations for customer workflow

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#7891]
The following operations must be available via the CLI (or via be able automated via script)
- ~invitation greeting~ (guest part)
  - according to @Landeers this should not be necessary, as the device can be generated on another workstation and then drop it on the PC that will call the CLI.
- [x] #7919
- [x] #7920
- [x] #7936
  > No need of using mount point if command options include the file path and workspace/parent folder
- [x] #7940
- [x] #7938
- ~#8231~
  - this depends on #6092 
  - according to @Landeers this can be done later

**Comment by FirelightFlagboy** [comment]
@mmmarcos Can we extract `CLI command to delete a workspace` so that we can close this issue ?

**Comment by mmmarcos** [comment]
> @mmmarcos Can we extract `CLI command to delete a workspace` so that we can close this issue ?

Done
