### ISSUE TITLE
Implement a 'Send Feedback' feature in the client for the Beta phase

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#808]
There should be an easy way for users to Send Feedback during the beta phase, straight from the client. We could have a Send Feedback link in one of the corners.

**Comment by stefan-contiu** [comment]
Suggested Implementation 
1. Add a link on the client app. The link should be always on. The link is pointing to a form on Site Marchand.
2.  The site marchand saves the info. Visualizing the feedback has less priority, we can query it by hand. Possible items to be on the form :
* Email/Name (should be optional)
* Type of feedback (Suggestion/Problem)
* Issue description

**Comment by vxgmichel** [comment]
Done a while ago.
