### ISSUE TITLE
Several coverage issues

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#810]

**Comment by vxgmichel** [comment]
I noticed several issues with the coverage system:
- Some jobs take into account the coverage for both `parsec-cloud/parsec` and `site-packages/parsec` (see [this build](https://travis-ci.org/Scille/parsec-cloud/jobs/599595657#L4796) for instance)
- The `parsec-cloud/parsec/core/gui` directory is ignored from coverage but `site-packages/parsec/core/gui` is not.
- The gui tests in app veyor yield a coverage of 0% (in `site-packages`, see [this build](https://ci.appveyor.com/project/touilleMan/parsec-cloud/builds/28206917#L4164).

**Comment by vxgmichel** [comment]
Too old
