### ISSUE TITLE
[🐛 | Bug]: Sort workspace by size not working

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#8108]
### Parsec version tested on:

3.0.0-rc.4

### Platforms tested on:

Linux

### Bug description:

Repro:

1. Create 3 workspaces `wk1`, `wk2`, `wk3`
2. Upload a big file in `wk1`
3. Upload a small file in `wk3`
4. Sort the workspace by size

The observed order is `wk1`, `wk2`, `wk3`.

Since `wk2` is empty I would expect the order to be `wk1`, `wk3`, `wk2`

**Comment by NicoTuxx** [comment]
Remove the order by size (we don't have this data)
