### ISSUE TITLE
[🐛 | Bug]: Non-trial organization takes a while to load content

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#8113]
### Parsec version tested on:

3.0.0-rc4
On `mighty-fairy` & `dev-saas` servers

### Platforms tested on:

MacOS

### Bug description:

Happened after creating a few workspaces and importing a bunch of files in some of them. After that, when logging or switching to a non-trial organization, its content take a good minute to load.

Loading:
![Screenshot 2024-08-22 at 14 40 19](https://github.com/user-attachments/assets/067e353b-4222-410c-8e1a-922c0ce45209)

After loading:
![Screenshot 2024-08-22 at 15 14 47](https://github.com/user-attachments/assets/08d83e26-47d5-428a-981c-159771d9239f)

**Comment by Landeers** [comment]
https://github.com/Scille/parsec-cloud/issues/5478 to add logs on parsec server.

**Comment by NicoTuxx** [comment]
https://github.com/Scille/parsec-cloud/pull/8253
