### ISSUE TITLE
[🐛 | Bug]: App doesn't close on the first try when logged in

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#8115]
### Parsec version tested on:

3.0.0-rc4

### Platforms tested on:

MacOS

### Bug description:

Seems to be related to https://github.com/Scille/parsec-cloud/issues/8113 as it doesn't apply to trial organizations.

When trying to close the app from a organization that took a lot of time to load, the app doesn't close and it takes a few tries for it to finally close. During that time after trying once, most features are disabled (workspace creation/management, file operations, etc.)

**Comment by NicoTuxx** [comment]
Linked to #5478 ?

**Comment by NicoTuxx** [comment]
https://github.com/Scille/parsec-cloud/pull/8253
