### ISSUE TITLE
[🐛 | Bug]: When an organization is frozen, we cannot log out

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#8122]
![Image](https://github.com/user-attachments/assets/2c2bee6d-080e-4ecd-855a-e4089c266535)

**Comment by NicoTuxx** [comment]
Check if still relevant

**Comment by fabienSvtr** [comment]
> [@fabienSvtr](https://github.com/fabienSvtr) Check if still relevant

No it's not but we have another issue that occurs when the organization is frozen, the user can still import documents on workspaces.
