### ISSUE TITLE
Capitalize Parsec name on Windows installer

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8128]
Should be `Parsec` everywhere instead of `parsec`.
 
![image](https://github.com/user-attachments/assets/cdb6226c-eb44-42b3-8812-a6e7f236ee6f)

**Comment by Ironicbay** [comment]
This change should be done on MacOS app as well.
![Image](https://github.com/user-attachments/assets/0fe8fbbc-6ae3-451b-bae0-ec5a0961f127)

**Comment by FirelightFlagboy** [comment]
To fix that, either we change the name in `client/electron/package.json` to `Parsec` or we set `productName` to `Parsec` in `client/electron/package.js::options`

https://www.electron.build/configuration/configuration#configuration

**Comment by Max-7** [comment]
`name` in `package.json` cannot contain uppercase characters (https://docs.npmjs.com/cli/v10/configuring-npm/package-json#name).
