### ISSUE TITLE
Use enum for invitation delete reason

### ISSUE THREAD

**Issue by AureliaDolo** [Scille/parsec-cloud#8224]
See https://github.com/search?q=repo%3AScille%2Fparsec-cloud++%22%23+TODO%3A+use+an+enum%22&type=code

_Originally posted by @FirelightFlagboy in https://github.com/Scille/parsec-cloud/pull/8080#discussion_r1740588941_

**Comment by vxgmichel** [comment]
Fixed [2381875](https://github.com/Scille/parsec-cloud/pull/8080/commits/2381875c23a51d6429bc44df2d29d1559b50f9cf)
