### ISSUE TITLE
[🚀 | Feature request]: Display external users on workspace sharing

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8245]
### What you would like to accomplish

When sharing a workspace with another user, I would like to be able to easily identify external users. 

This would allow me to quickly detect if an external user has an unwanted role (e.g. I want external users to only have Read access).

In the screenshot below, only Mallory is an external user but there is no quick way to know it (besides clicking "Not shared" and see that it cannot become Manager or Owner since this roles are restricted for external users).
![image](https://github.com/user-attachments/assets/c0ea2d27-b642-455f-8983-11d7caa5d9b1)

#### Idea 1: Display profile badge for externals

External users can have their Profile badge displayed (similar to what it is displayed in the users page)
![image](https://github.com/user-attachments/assets/60a33474-d312-4e27-8986-7f767271e102)

In this case, I would not display the badge for admin and standard profiles, only for external. Otherwise there may be too much information.

#### Idea 2: Separate external users

Maybe externals can be displayed in a separate list, right next or below the admin/standard user list.

**Comment by fabienSvtr** [comment]
I think the first option is the best, external user should be labelled next to their name. I've added a mock up to get a proper idea of what needs to be done.
![image](https://github.com/user-attachments/assets/f257c55e-dcc0-4323-89b3-7436fa0ab486)
