### ISSUE TITLE
[🚀 | Feature request]: Batch workspace sharing

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#8326]
### What you would like to accomplish

Allow an user to share a workspace to multiple users in 1 go

### How the feature should work

On the workspace sharing model, display a "selectable" list (like the one for files) where the user can select one or more users to assign them to a specific role

Figma link: https://www.figma.com/design/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?node-id=25763-142489&node-type=section&t=gb5llDfZsvTDGJTC-11

### Setup

TODO: If applicable, describe how to local setup for testing this feature (testbed ? local server ? mocked data...)

### Tests

TODO: List some test cases to be performed when reviewing the feature.

**Comment by mmmarcos** [comment]
@Ironicbay please complete the "Test protocol" section. We'll use it to test the feature before closing the issue.
