### ISSUE TITLE
[🐛 | Bug]: Workspace last edition date

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#8336]
### Parsec version tested on:

 v3.0.0-rc.5

### Platforms tested on:

Windows

### Bug description:

For workspace, last edition date is alwayd "à l'instant".

### Relevant output:

![image](https://github.com/user-attachments/assets/d2e87d42-a129-4f34-9dbc-c649943f2825)

**Comment by NicoTuxx** [comment]
If the information is not available from the bindings, hide this for now
