### ISSUE TITLE
An error can prevent the user for logging out

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#8366]
I got this error while logging out (note that I logged in while the server was offline)

![image](https://github.com/user-attachments/assets/0fe2f960-a0b4-4514-ba65-b830141adbd5)

Log:
```
[2024-09-13 12:51:06.268] [debug] Error when calling clientStop: ClientStopErrorInternal (Invalid Handle)
```

**Comment by touilleMan** [comment]
This error `ClientStopErrorInternal (Invalid Handle)` should come from the fact the handle has already been closed

My guess is there is multiple concurrent `client_stop(handle)` calls, the first one succeeding and the subsequent ones getting this error.

I would say the fix should be to only have a single stop occurring :/
