### ISSUE TITLE
[🐛 | Bug]: App does not use default browser to open links

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8382]
### Parsec version tested on:

3.0.0-rc.7

### Platforms tested on:

Linux

### Bug description:

On Debian GNU/Linux trixie/sid / with Gnome 46

Installed browsers:
- Firefox Developer Edition (default)
- Firefox ESR
- Chromium 

When I click on a link (e.g. `Documentation` or `Contact Us`), it gets opened with Firefox ESR.

**Comment by FirelightFlagboy** [comment]
```
snap run --shell parsec
$SNAP/bin/desktop-launch-wrapper xdg-open foo
```

**Comment by mmmarcos** [comment]
```shell
snap run --shell parsec
$SNAP/bin/desktop-launch-wrapper xdg-open 'https://parsec.cloud'

# ... still opens Chromium instead of Firefox ;(
```

`xdg-mime` differ too:
```shell
$ xdg-mime query default x-scheme-handler/https
firefox-devedition.desktop

$SNAP/bin/desktop-launch-wrapper xdg-mime query default x-scheme-handler/https
chromium.desktop
```

**Comment by mmmarcos** [comment]
I've checked some of the mime dirs [mentioned here](https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list):
```shell
$ cat ~/.config/mimeapps.list | grep 'x-scheme-handler/https'
x-scheme-handler/https=firefox-devedition.desktop

$ cat ~/.local/share/applications/mimeinfo.cache | grep 'x-scheme-handler/https'
x-scheme-handler/https=firefox-devedition.desktop;

$ cat /usr/share/applications/mimeinfo.cache | grep 'x-scheme-handler/https'
x-scheme-handler/https=chromium.desktop;firefox-devedition.desktop;
```
Aha! there is a cache file that points to Chromium, even if Firefox is default everywhere else. 

So, editing the last one did the trick. 
```shell
$SNAP/bin/desktop-launch-wrapper xdg-mime query default x-scheme-handler/https
firefox-devedition.desktop
```

The problem is that this file seems to be re-generated at startup by `update-desktop-database` (or `sudo dpkg-reconfigure desktop-file-utils`). When re-generated, Chromium is still added before firefox :-/

**Comment by mmmarcos** [comment]
So, as suggested [here](https://unix.stackexchange.com/a/316731), instead of editing 
```
/usr/share/applications/mimeinfo.cache
``` 

I've created to set system-wide default values:
```
/usr/share/applications/mimeapps.list
```
That seems to work, now Parsec opens links in Firefox :)
