### ISSUE TITLE
Newly installed Parsec sometime doesn't show up in explorer

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#839]
Steps:
- On a fresh Windows (Parsec&winFSP have never been installed)
- Install Parsec from a build .exe installer (e.g. v1.3.0)
- Start Parsec & login
- Parsec shortcut doesn't appear in the file explorer
- After a restart, Parsec shorcut may or may not appear...

**Comment by Max-7** [comment]
May have been fixed by https://github.com/Scille/parsec-build/commit/e5796cfaaef23f1d0c6cb9641d57ed670edf9fd8, waiting for next release to confirm.

**Comment by vxgmichel** [comment]
Outdated with #1159
