### ISSUE TITLE
[🚀 | Feature request]: Filter on workspace name 

### ISSUE THREAD

**Issue by AureliaDolo** [Scille/parsec-cloud#8394]
### What you would like to accomplish

Find a workspace by its name.

### How the feature should work

![Screenshot from 2024-09-16 15-28-26_with_search_bar](https://github.com/user-attachments/assets/428b6a18-5f0a-4cb6-ab3b-903febdf3aa5)

Add a search bar, and filter just on workspace names.

### Describe alternatives you have considered

In the future, we could add a more complex search engine behind that bar.

**Comment by Max-7** [comment]
Make sure the user understand that it's only a filter on a workspace name, not a search.
