### ISSUE TITLE
Adobe reader cannot see files from WinFSP mountpoint

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#840]
Not only related to Adobe Reader (but it's the more common usecase where the error shows up)

see https://github.com/billziss-gh/winfsp/blob/master/doc/WinFsp-Tutorial.asciidoc#running-the-file-system-as-a-service
Our current way of running winfsp means the mountpoint is not accessible to every process on the system, this may be the cause why some software (typically one which rely on a service process) cannot see the files.

**Comment by vxgmichel** [comment]
Fixed with #924
