### ISSUE TITLE
[🐛 | Bug]: CLI - only 3 codes are proposed on CLI ?

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#8430]
### Parsec version tested on:

v3.0.0-rc.8

### Platforms tested on:

Linux

### Bug description:

Only 3 codes are proposed, is it deliberate ?

### Relevant output:

![Capture d’écran 2024-09-18 102648](https://github.com/user-attachments/assets/a86f379e-ed4b-4c61-a3b3-96138224841c)

**Comment by FirelightFlagboy** [comment]
Yes, it is :) we can increase it, but it's not a bug
