### ISSUE TITLE
Click on unmount while doing a "save as" lead to a crash

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#844]
1) Open a document for instance ODT in a enclave
2) Modifiy the document
3) While doing a "Save as", click on "unmount" an enclave.
![image](https://user-images.githubusercontent.com/9845177/69914144-f808a500-1440-11ea-9351-27aa6ead702b.png)
4) Libre Office crashes

**Comment by vxgmichel** [comment]
Not much we can do about this, let's wait for fuse support in nautilus and nemo
