### ISSUE TITLE
Graphic bug when adding new members

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#8442]
### Actual
On the Step 3/3:
![Image](https://github.com/user-attachments/assets/a016bf81-59ea-4406-a386-d7e1fa85c12b)

### Mockup
![Image](https://github.com/user-attachments/assets/10d4c01c-a86b-40a8-bb26-4207f8537338)

**Comment by NicoTuxx** [comment]
still relevant?

**Comment by fabienSvtr** [comment]
With the way the code is done, we cannot do it like the mockup.
`<user-information />`
`<ms-dropdown  />`

Nonetheless, the input are now with the right size.
