### ISSUE TITLE
Removing someone from an enclave causes the revocation icon to blink

### ISSUE THREAD

**Issue by tleblond** [Scille/parsec-cloud#845]
1) Create an enclave
2) Invite "Manu" in the enclave as "reader"
3) Suppress "Manu" as guest of this enclave without suppressing Manu from le legitimate users

--> The icon "revocation" is blinking appears as disappears with a period of roughly 1 second

**Comment by tleblond** [comment]
C'est l'icône orange qui indique qu'il faut procéder à un rechiffrement des méta-données du WS (alors que l'utilisateur na pas été supprimé de l'organisation mais simplement retiré à la maindu WS). Si on rajoute à nouveau le même utilisateur, l’icône disparaît et tout redevient normale.

**Comment by Max-7** [comment]
This behavior is exactly what is expected. When a user is removed from a workspace, this workspace has to be reencrypted. If the same user is then re-added to the workspace, it no longer has to be.

Closing this issue, as it just spawns from a misunderstanding on when workspace reencryption should take place.
