### ISSUE TITLE
[🐛 | Bug]: `FileOperationMenu` has a huge impact on CPU usage

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#8468]
### Parsec version tested on:

3.0.0-rc8

### Platforms tested on:

MacOS

### Bug description:

On my computer:
- Parsec renderer takes approximately 2% of my CPU at idle in a workspace on `FoldersPage`
- With 1 item in `FileOperationMenu` this jumps to 6%
- With the current 'fix' limiting to 10 items, CPU usage is at ~12%
- Up to 80% with ~100 items

**Comment by FirelightFlagboy** [comment]
Need to investigate is it's not already fixed on master
