### ISSUE TITLE
Suggestion ergonomie: faciliter l'accès au point de montage PARSEC dans l'explorateur Windows

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#848]
actuellement : 
- soit on clique en haut à droite du clietn parsec
- soit on doit aller manuellement dans C:\users\phil\parsec_mnt

Pourquoi ne pas mettre un lien sur le montage parsec dans l'explorateur Windows directement,
très ergonomique ?
(ie au même niveau que le lien dropbox, onedrive, Ce PC,.....)

**Comment by touilleMan** [comment]
Le lien dont tu parles existe déjà, si il ne s'affiche pas c'est un bug, cf ##839
