### ISSUE TITLE
[🐛 | Bug]: Invalid app state after a logout error 

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8489]
### Parsec version tested on:

3.0.0

### Platforms tested on:

Linux

### Bug description:

This is a follow-up to issue #8488 : everything related to the organization remains in an invalid state if an error occurs during a logout:

4. Click "Go to home"
5. Organization displays "Logged in"
6. Click on organization, opens the organization in an invalid state (no workspace, no items)
7. Button "Go to home" is no longer displayed
8. Need to close and restart app to return to a valid state.

**Comment by mmmarcos** [comment]
It should be rather easy to reproduce by simulating errors during logout.

**Comment by mmmarcos** [comment]
The logout function does not do anything strange:
https://github.com/Scille/parsec-cloud/blob/b44568f5b272e731e4fb874cca632c1589af26fe/client/src/parsec/login.ts#L234-L241

However, calls to logout seem to "ignore" error cases (only displays message):  
https://github.com/Scille/parsec-cloud/blob/b44568f5b272e731e4fb874cca632c1589af26fe/client/src/views/header/ProfileHeader.vue#L146-L151

https://github.com/Scille/parsec-cloud/blob/b44568f5b272e731e4fb874cca632c1589af26fe/client/src/main.ts#L330-L336

**Comment by FirelightFlagboy** [comment]
I have a step to reproduce a logout error using a local server: https://github.com/Scille/parsec-cloud/issues/8381#issuecomment-2371035866

**Comment by NicoTuxx** [comment]
What do we do with that?

**Comment by NicoTuxx** [comment]
no more relevant according to @Max-7
