### ISSUE TITLE
Investigate how to visualize common files directly in app

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#8514]
The app needs to be able to display some more common files directly, without relying on the apps installed on the computer (typically for web mode).
We don't want to download the file, as:
1. this would mean extracting the file from a secure location
2. the user could try and update the file, mistakenly believing that it would update it in Parsec

Common file types include:
- images (jpeg, png, webp, ...)
- Office formats (docx, xlsx) or Libreoffice formats (odt, ...)
- common text files (md, txt, json, code, ...)
- PDF
- Archives (zip, ...)
- Audio (mp3, wav, ...)
- Video (mp4, webm, ...)

This only concern file visualization, not editing.

Questions to investigate:
- OnlyOffice:
  - Would it be viable for some of those files?
  - Can we easily implement it without document edition?
  - How much time would be needed?
- Would we use another JS library to visualize common files?
  - Which one(s)?
  - How much time would be needed?
  - What are the cons in the future since we are gonna use OnlyOffice for doc edition anyway? Will if conflict? Will we still use it or not?

**Comment by mmmarcos** [comment]
Building quick viewers for common files (specially `docx` and `xlsx`) seems the right choice for the moment as this can be implemented in the frontend, with little or no change to Parsec server. We'll open another issue to track implementation.
