### ISSUE TITLE
Provide a "Reset device local data" option

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#852]
This would be helpful when the system end up in an inconsistent state (typically in case of a software bug)
Of course this option should be available before login (given data inconsistency could lead to impossible login !)

This option should destroy both the local not-yet-synced data and the local cache (of course we could divide the option between remove cache and remove not-yet-synced data, but it makes things more complicated...). This means the user could lost some data so the option should be well explained and put in a place the user doesn't click too much ;-)

**Comment by vxgmichel** [comment]
Meh.
