### ISSUE TITLE
Upwards navigation in the folder tree (Repertoire parent) can be confused with the backwards icon to the workspaces

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#857]
The "arrow" icon in the right lower corner (for going back to workspaces) can be easily confused with navigate backward in the folder tree.

Some (possible) ideas that could fix the confusion :
1. Change the icon for going back to workspaces (something like a list?)
2. Include a short label next to each button? (so it is explicit what they mean)
3. Implement Folder navigation (go to parent directory) in the same style as Dropbox UI.

![image](https://user-images.githubusercontent.com/8625772/70152423-7bc6c980-16ad-11ea-9e23-8054c7299912.png)

**Comment by Max-7** [comment]
Different on new design.
