### ISSUE TITLE
Add parsec icon to the root mountpoint folder

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#859]
`%APPDATA%/Parsec` (see #858 ) shouldd have a parsec icon on the folder (just like what does Dropbox)

**Comment by Max-7** [comment]
This can be done by adding a hidden desktop.ini file inside the folder :
```
[.ShellClassInfo]
IconFile=C:\Program Files (x86)\Parsec\parsec.exe
IconIndex=0
InfoTip=Secure cloud framework
```
and switching the folder to a system folder
> attrib +s folder

This can also be used to disable sharing of the folder by adding `NoSharing=1`.

More info https://docs.microsoft.com/en-us/windows/win32/shell/how-to-customize-folders-with-desktop-ini

All's left is checking how it works out with Fuse and how to perform those operations with NSIS.

**Comment by Max-7** [comment]
https://github.com/Scille/parsec-build/pull/36
