### ISSUE TITLE
[🚀 | Feature request]: Add warning message when a workspace has a single OWNER

### ISSUE THREAD

**Issue by Landeers** [Scille/parsec-cloud#8592]
### How the feature should work

A message should appear when an OWNER :
- accesses a workspace where he/she is the sole owner
- withdraws an owner's rights and becomes the only remaining owner

**Comment by Max-7** [comment]
Currently displayed in the workspace sharing dialog.

![Screenshot 2024-10-03 111818](https://github.com/user-attachments/assets/f903bfbe-6005-4152-9310-353c447f7cd4)

**Comment by FirelightFlagboy** [comment]
Wait feedback from one of our client

**Comment by mmmarcos** [comment]
This has already been implemented. Reopen if needed.
