### ISSUE TITLE
pas de Parsec dans l'arborescence ( V 1.3.0 )

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#861]
je ne trouve pas le logo parsec dans l'arborescence explorer windows

![Capture d'écran 2019-12-05 19 39 21](https://user-images.githubusercontent.com/46708918/70263912-a7be7980-1797-11ea-9bf7-de1701c15814.png)

**Comment by Max-7** [comment]
Duplicate of #839, closing this one.
