### ISSUE TITLE
shell mv cause "Read-only file system" warning

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#864]
```shell
$ mv ~/xxx.pdf ~/parsec_mnt/wksp1/subfolder42/
mv: preserving permissions for ‘/home/emmanuel/parsec_mnt/wksp1/subfolder42/xxx.pdf’: Read-only file system
```
However the operation worked fine (source has been removed, target exists and is readable), I guess it's just a warning due to the lack of the support of extended attributes in the mountpoint

**Comment by mmmarcos** [comment]
This no longer appears to be the case with Parsec `v2.16.1` (tested on Debian 13 / zsh 5.9).
