### ISSUE TITLE
Workspace History: GUI

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8663]
See user stories in #6147.

**Comment by NicoTuxx** [comment]
Multiple points to take in consideration here:

the old feature was an UX nightmare (not understandable and not easily usable)
what is the API able to do atm?
the feature is required by customers, but need to be improved in UX terms (maybe something like "Restore to an old version" function in Windows)
long term we want / need the most known feature of this type: an history of file versions, with the possibility of restore a specific one => Is it possible today? If not, create issues (bindings / GUI) to trace it.

**Comment by mmmarcos** [comment]
> *  What is the API able to do atm?

According to @touilleMan: _For the GUI, it's just an `at` parameter [...] I'm thinking of adding a method for listing the versions of a particular file (but that's for later, right now the most important thing is that the GUI can mount a workspace at a given date). [...] You can perform all the read operations of the classic API (read files, list directories, stat files, etc.)._

> * The feature is required by customers, but need to be improved in UX terms (maybe something like "Restore to an old version" function in Windows)

It is not necessary a _single_ feature. 

I will complete the issue description with some use cases to be addressed. From there, maybe multiple features can be proposed with the same API (restore file to a specific version, restore ws to a specific date, etc.).  

> * Long term we want / need the most known feature of this type: an history of file versions, with the possibility of restore a specific one => Is it possible today? If not, create issues (bindings / GUI) to trace it.

Currently, the API seems to propose restore of a file to a specific date, but listing the file versions also seems interesting. I will add use cases so we can prioritize.

**Comment by Max-7** [comment]
https://www.figma.com/design/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?node-id=31197-75432&node-type=frame&t=BlZwmEnelh6J5nmf-11
