### ISSUE TITLE
V3 Migration Guide

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8668]

**Comment by NicoTuxx** [comment]
- [ ] Improve _"Customer registration"_ section: (improve content, add screenshots, make specific use cases for `monthly subscription vs custom order`)
- [ ] Improve _"Parsec v3 installation"_ section (improve content, add screenshots)
- [ ] Improve _"Create first organization"_ section for `monthly subscription use case` (improve content, add screenshots)
- [ ] Create the equivalent section for the `custom order use case`
- [ ] Improve _"Migrate data"_ section (improve content, add screenshots)
- [ ] Improve _"Unsubscribe"_ section for `monthly subscription use case` (improve content, add screenshots)
- [ ] Create the equivalent section (_"What to do on old version now?"_) for the `custom order use case`
- [ ] Create an english version of this document

**Comment by mmmarcos** [comment]
Migration Guide is finished.
