### ISSUE TITLE
enrolement d'un deuxieme device

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#868]
l'ecran a change : il faut faire quoi?
<img width="900" alt="2019-12-09" src="https://user-images.githubusercontent.com/46708918/70459168-e57f1300-1ab3-11ea-9cac-6282f5827caf.png">

**Comment by vxgmichel** [comment]
La procédure d'invitation a été largement simplifiée: il suffit de cliquer sur le lien d'invitation (par exemple depuis la messagerie instantanée de ton navigateur) et parsec devrait s'ouvrir automatiquement avec la fenêtre d'invitation de device pré-remplie. Si pour une raison ou une autre parsec ne s'ouvre pas quand tu cliques sur le lien, tu peux simplement le copier puis le coller dans la fenetre "Fournir une adresse".
