### ISSUE TITLE
Cannot change workpsace role of owner

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#870]
![image](https://user-images.githubusercontent.com/3187637/70474070-343ba580-1ad2-11ea-9fa7-b35cad57e00f.png)

An owner should be able to change the role of another owner.
(Only forbidden thing is for a owner to change it own role)

**Comment by Max-7** [comment]
Fixed by https://github.com/Scille/parsec-cloud/commit/67a885b4c6986bb31ff0ac16972f5d338ecf55a3

**Comment by touilleMan** [comment]
Reappeared in 1.11.4 :'(

![image](https://user-images.githubusercontent.com/3187637/80192311-43e9ff80-8617-11ea-9807-a3c02bbb6875.png)

**Comment by Max-7** [comment]
Re-fixed by https://github.com/Scille/parsec-cloud/commit/819eef69c5daf9a0e19831b1bf4ee5b9d7804e6a
