### ISSUE TITLE
Parsec auto-updater causes warning message on Windows when process is already running

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#872]
To repro (on windows) :
* run parsec
* update to newer version
* dialog box message is displayed requiring to manually close Parsec
![image](https://user-images.githubusercontent.com/8625772/70536378-d99c5b00-1b5e-11ea-92d8-3d4273e0c72e.png)

**Comment by Max-7** [comment]
Installer should loop while Parsec is not closed instead of exiting when OK is clicked.

**Comment by c4ffein** [comment]
Closed as we have a new installer
