### ISSUE TITLE
Where is home?

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8724]
As a user, I find it a quite upsetting not to have a clear notion of "home" page or how to come back to it. 

For me, the "home" page is the one listing the workspaces (because it is the first page shown on login), but:
- there is no clear way to come back to this page
- AND the app uses "home" for other pages too!

For example, take the following screen:
![image](https://github.com/user-attachments/assets/a2756122-8e5a-4985-a2e7-9554600a9e16)

A user may ask itself, how do I return to the "home" page? 

- Maybe if I click `Go to home`? --> WRONG this button takes back to the (Welcome?) organization page :dizzy_face: 
- Maybe is `Go back`? --> WRONG this depends on where I was before opening My Profile
- Maybe is the `Workspaces` in the left panel --> NOPE, not clickable
- Maybe there is a home button in the main menu? --> NIET

Moreover, it's also disturbing to having different notions of "Home" in the same page. Here, the same icon is used for different pages:
![image](https://github.com/user-attachments/assets/6dddb376-9ecc-4aff-b0cc-1941d949d7df)

----

The home page usually acts as an anchor for the user to feel it is back to a "known" place.

So my suggestions:
- Use "Welcome" or "Login" page for the page listing the organizations/devices. 
- Use "Home" for the page listing the workspaces
- Use different icons for these two pages.
- Ensure that at least the "Home" page is always available (and if possible in the same place) no matter where the user is.

**Comment by NicoTuxx** [comment]
@fabienSvtr we need to talk

**Comment by fabienSvtr** [comment]
After a talk with @NicoTuxx, we decided:
- To updated the button `Back to home` to `Go to workspaces`
- In the switch organization menu popover the user can with a specific button:
• Go directly to their customer account (login page)
• Return to the organisation page 

![image](https://github.com/user-attachments/assets/a570797f-cde3-49ec-925b-c61a33f09666)
![image](https://github.com/user-attachments/assets/95c11cb6-a52d-46b0-97dc-348c5b94346d)

You can see component in [Figma here](https://www.figma.com/design/XW3SNWHV8BhPsPJpsOCV2h/Parsec-App?node-id=22411-71315&node-type=section&t=5QzgAxNRp1EurL3N-11).
