### ISSUE TITLE
[🐛 | Bug]: Lose file selection when using workspace link

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#8728]
### Parsec version tested on:

3.1.0-rc.1

### Platforms tested on:

Linux

### Bug description:

1. Copy a workspace link
2. Go to that workspace
3. Select some files
4. Use the save workspace link
5. Observe that you will loose the selection at step 3

**Comment by FirelightFlagboy** [comment]
Ok, we just need to clairify that on the manual tests list

**Comment by Max-7** [comment]
Added a note to the test protocol file, closing this issue.
