### ISSUE TITLE
[🐛 | Bug]: Cannot use workspace link if a "Invite a user" modal open

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#8729]
### Parsec version tested on:

3.1.0-rc.1

### Platforms tested on:

Linux

### Bug description:

1. Copy the link to a workspace
2. Go to user list as admin
3. Click "invite a user"

   > That would open a modal

4. Try to use the save link
5. Observe that the link is not working

   > Parsec has a notification indicating it's busy :thinking:

**Comment by NicoTuxx** [comment]
Update test protocol to explain what is expected
