### ISSUE TITLE
We should be able to share a link to a file stored in Parsec

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#873]
Consider the following scenario :
Two users have Parsec installed and are members of the same enclave. There should be a feature allowing one of the users to point the other user to a file (or directory). For example, the first user could export a "parsec://" link to the file and hand it over to the other user by mail or im. The second user can click the link and be pointed to the file in parsec.

**Comment by Max-7** [comment]
Split into two issues #937 and #938. Closing this one.
