### ISSUE TITLE
Fix recovery device in CLI

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#8747]
`parsec-cli` appear to use the recovery device mechanism the intended way.

Currently way creating a recovery device, it use the current device without creating a new device.
And when importing the recovery device, we import the device as is without using it to create a new device.

The shamir (wip) system behave like intended and we could reuse some part to fix the issues:

- When creating a shamir device: 
  
  https://github.com/Scille/parsec-cloud/blob/96eb831587aa68f860ea7452b4b423876c1679c0/libparsec/crates/client/src/certif/shamir_recovery_setup.rs#L241-L258

- When importing a shamir device: 

  https://github.com/Scille/parsec-cloud/blob/96eb831587aa68f860ea7452b4b423876c1679c0/libparsec/crates/client/src/certif/shamir_recovery_setup.rs#L310-L318

## TODOs

- [ ] [CLI] Create a dedicated device when creating a recovery device
- [ ] [CLI] Create a dedicated device when importing a recovery device

**Comment by NicoTuxx** [comment]
related to #8585
