### ISSUE TITLE
[🐛 | Bug]: Error when trying to open a file on MacOS

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#8764]
### Parsec version tested on:

3.1.0

### Platforms tested on:

MacOS

### Bug description:

Trying to open a file fails on MacOS (with macFUSE correctly installed).
The error can be shown **once** as an error modal but is shown as a toast every other time.'
File opening was working on 3.0.3.

### Relevant output:

![image](https://github.com/user-attachments/assets/04521441-2f4b-472a-aa76-219c43b9030c)
![image](https://github.com/user-attachments/assets/25fce7d9-3fe4-43f9-94b7-0347d493a7b9)

**Comment by FirelightFlagboy** [comment]
Related to #8735
