### ISSUE TITLE
We should investigate how to branch to LDAP to fetch groups and users

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#877]
An advanced feature of Parsec is to replace the Users management screen (Add, Remove users) with LDAP, thus targeting larger organizations. 

We should investigate how we can integrate LDAP, notably :
1. What is the effect on the enrollment procedure in Parsec (the mapping between user devices and client account on LDAP)
2. can we replicate an entire LDAP hieracrhy? (e.g., groups inside groups)
3. how do the LDAP callbacks for join/revoke events integrate with Parsec core, and how can we be sure that our system (through manifests, key versions) maintain the identical state of LDAP?

**Comment by touilleMan** [comment]
too old, closing
