### ISSUE TITLE
Define a new device creation process

### ISSUE THREAD

**Issue by AureliaDolo** [Scille/parsec-cloud#8810]
We create devices in the following places:
- bootstrap
- user invitation
- device invitation
- recovery device export 
- recovery device import
- shamir setup creation

In some cases (bootstrap and recovery) we save the device and then we send the certificate to the server and other (invitation) we do the opposite. 

We should choose one way to do that. It can lead to incoherence.  

> What is the tradeof here ? I guess it's something similar to what we have when we create a device during enrollment (i.e. if our machine goes down at the wrong time we have the choice between losing the new device, or having in our client a device the server doesn't know about [^1])

> In the end I think we should follow the same strategy in both places  (so saving the device *after* we have uploaded it to the server)

> [^1]: Of course we can have the best of both world with a more complex approach based on saving a temporary type that represent the fact the device might or might have been uploaded on the server... but it's too much complexity for a corner case, at least for the moment ;-)

_Originally posted by @touilleMan in https://github.com/Scille/parsec-cloud/pull/8585#discussion_r1819299513_

**Comment by touilleMan** [comment]
> In some cases (bootstrap and recovery) we save the device and then we send the certificate

Are you sure about the bootstrap, I would say it does the opposite, cf:
https://github.com/Scille/parsec-cloud/blob/32cc7003196bac97b9bf4d2e9c398fd4087ea70f/libparsec/src/invite.rs#L123-L146

> We should choose one way to do that. It can lead to incoherence.

I think we should stick with what the invitation does (i.e. first create the device on the server, then save it on the client), as it save us from having to deal with device on disk that are not on the server (and dealing with device on the server that is not on disk is much easier to deal with: just ignore the device and retry your operation)

**Comment by touilleMan** [comment]
done with https://github.com/Scille/parsec-cloud/pull/8585/commits/e751b3cdfc99d6154815ec55ae67eb1b1e6f6e36
