### ISSUE TITLE
`PrivateKey.encode` returns a `list[int]` instead of `bytes` in Python bindings

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#8865]
@vxgmichel PyO3 has bitten us again ! :trollface: 

```python
>>> from parsec._parsec import PrivateKey
>>> PrivateKey.generate().encode()
[220, 39, 111, 82, 33, 93, 107, 31, 31, 217, 70, 228, 115, 161, 50, 79, 0, 110, 251, 62, 34, 98, 184, 102, 70, 122, 162, 4, 28, 247, 33, 125]
```

https://github.com/Scille/parsec-cloud/blob/557fec107dfafa968f8d84158a30fd98c0594877/server/parsec/_parsec_pyi/crypto.pyi#L59

It's possible some other key types have the same issue, so we should check also check them...

**Comment by FirelightFlagboy** [comment]
- https://github.com/Scille/parsec-cloud/blob/10fa41442b21d17289797ebf5f1a652f630b6ecd/server/src/crypto.rs#L109-L111
- https://github.com/Scille/parsec-cloud/blob/10fa41442b21d17289797ebf5f1a652f630b6ecd/server/src/crypto.rs#L300-L302
- https://github.com/Scille/parsec-cloud/blob/10fa41442b21d17289797ebf5f1a652f630b6ecd/server/src/crypto.rs#L342-L344
