### ISSUE TITLE
[🐛 | Bug]: Workspace history datepicker is not translated in french

### ISSUE THREAD

**Issue by NicoTuxx** [Scille/parsec-cloud#8901]
### Parsec version tested on:

3.2.0-rc1

### Platforms tested on:

Windows

### Bug description:

![image](https://github.com/user-attachments/assets/2932cb1d-c287-4a93-8b5b-f19fedc40251)

**Comment by Max-7** [comment]
While this one is easy to fixed, I've opened #8902 for a slightly different problem.
