### ISSUE TITLE
[🐛 | Bug]: Workspace link redirecting randomly if several devices have access to it

### ISSUE THREAD

**Issue by Ironicbay** [Scille/parsec-cloud#8916]
### Parsec version tested on:

3.0.2-rc1

### Platforms tested on:

MacOS

### Bug description:

If several devices have access to the same workspace, opening a link to it will open it from one of these devices without a clear logic.

In my case, I have devices A, B and C having access to a workspace. C is revoked.

When opening the link from with A and B logged in, the workspace opens in B.
When opening the link from with A and B and C logged in, the workspace opens in C, and an error shows since this device is revoked.
When opening the link from a closed app, the workspace opens in C, and the same error shows.

**Comment by Max-7** [comment]
It's not random, but it's complicated.

A workspace link contains the serveur and the organization. We match it against the devices'. If multiple devices match, we can't know which one is the better one, so we just pick up the first.
Then we log in, and we check if the workspace is present, and then if the file is present in the case of a file link.

- We can't know if a device is revoked or if it has the workspace unless we're logged in and by this time it's too late anyway
- We can't force a log in of the matching devices
- Technically if some matching devices are already logged in we could find the best matching one but that would mean listing all the workspace from the home page just to try to find a device that matches. It adds a lot of complicated logic in something that's already quite complicated.

Ultimately, it shouldn't happen. A user having multiple devices to the same organisation with different email is something that should only happen during tests.

**Comment by FirelightFlagboy** [comment]
Replaced by #8922
