### ISSUE TITLE
[🐛 | Bug]:  Duplicate import files (drag&drop)

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#8918]
### Parsec version tested on:

3.2.0-rc.1

### Platforms tested on:

MacOS

### Bug description:

Drag and drop file shows two identical files on the background tasks panels and in the files/folder interface.

### Relevant output:

![Image](https://github.com/user-attachments/assets/ea27f9cb-e155-4bda-b14d-f96511a7cde2)
https://github.com/user-attachments/assets/eb48b450-73ff-42ca-a8cb-ec0bb15c946b

**Comment by Ironicbay** [comment]
Could not reproduce.

**Comment by fabienSvtr** [comment]
I still got the problem when importing a file:

https://github.com/user-attachments/assets/e5a3b304-dc3e-4870-811e-c2b0adafdf94
