### ISSUE TITLE
Winfsp is not installed when the parsec installer does not have admin priviledges

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#8934]
This is due to the quiet installation of winfsp that doesn't prompt the user for privilege escalation when `msiexec` run with `/qn`.

Note: this only happens for user install (installation in `AppData`) as opposed as "machine" install which will elevate to admin rights to install in `C:\Programs`

**Comment by FirelightFlagboy** [comment]
Fixed by #8934
