### ISSUE TITLE
[🐛 | Bug]: The action Make a copy hides the original file

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8970]
### Parsec version tested on:

3.2.0-rc.3

### Platforms tested on:

Linux

### Bug description:

Steps to reproduce:

0. Create a folder named `test` and import an empty file `test.txt` 
1. Right-click on `test.txt`
2. From context menu, select `Make a copy`
3. In the `Copy one item` dialog, click `Copy here` without changing folder
  - The file `test (2).txt` appears (OK)
  - The file `test.txt` dissappears (**NOK**)
  - The file `test.txt` re-appears when refreshing the page

Note: this behavior does not seem to occur when working on the workspace root (`/`), only when working on a Folder inside the workspace.

https://github.com/user-attachments/assets/9eaa2938-a194-4f61-8e35-d2d54014da9a

**Comment by Max-7** [comment]
May be linked to #8921 (just mentionning it because both can probably be solved at the same time).
