### ISSUE TITLE
[🐛 | Bug]: Customer Area shows no stat when selecting all organizations

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8971]
### Parsec version tested on:

3.1.0

### Platforms tested on:

Any

### Bug description:

In the Customer Area, it is possible to select multiple organizations from the top-left menu. When that's the case, the statistics page does not show any statistics at all. 

It is not obvious to the user that it needs to select a single organization in order to see the statistics.

Some suggestions:
- Improve the default message: e.g. `You have multiple organizations. Please select one from the top-left button in order to see its statistics.`
- Add links allowing to change the organization from the page itself: 
```
You have multiple organizations. Please select one to see its statistics:
- Org1
- Org2  <-- clicking here would be the same as if the user selected Org2 from the top-left button.
- ...
```

**Comment by Max-7** [comment]
Or simply hide the statistics link when an org is not selected.
