### ISSUE TITLE
Alert user about mountpoint bug on macOS

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#8977]
3 solutions, only 2 kept (to do):
- ✅ Specify a "beta" badge on the download page to make it clear that there are bugs on macOS version.
- ✅ Add an alert to the mountpoint problem upstream (i.e. on download), so as to warn that the version is not yet complete at this level.
- ❌ When opening a finder, display a modal to warn that certain functionalities are not yet available. On this modal, have precisely one checkbox for "don't remind me again" (so as not to spam the user).

**Comment by NicoTuxx** [comment]
Is it done?

**Comment by NicoTuxx** [comment]
done in other issues
