### ISSUE TITLE
Access denied when trying to open pdf file using Foxit Phantom pdf

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#911]
General problem with several pdf reader.

**Comment by vxgmichel** [comment]
I cannot reproduce this issue on my windows virtual machine. Could you share a screenshot of the issue? Thanks :)

**Comment by PhClermontScille** [comment]
Here it is ::
- en double clic dans l'explorateur Windows
![image](https://user-images.githubusercontent.com/13103240/72245257-6a4bd800-35f0-11ea-9052-089286e116a6.png)
- en ouverture directe depuis Foxit Phantom pdf, ca marche.

**Comment by vxgmichel** [comment]
Fixed since v0.1.5 (#924)
