### ISSUE TITLE
Logo PARSEC en partie gauche de l'explorateur Windows : n'apparait pas *en général*

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#912]
1. Dans la fenêtre explorateur windows, partie gauche (à proximité des logos Dropbox et OneDrive, le logo PARSEC n'apparait pas.
2. Par exemple sous Word, /Parcourir pour ouvrir un fichier, le logo apparait dans l'explorateur,
mais n'est pas cliquable (fenetre d'erreur ):
![image](https://user-images.githubusercontent.com/13103240/72137849-dbd71c80-338b-11ea-86d8-8ca4c16a144d.png)

**Comment by vxgmichel** [comment]
Outdated with #1159
