### ISSUE TITLE
Transfer via le gestionnaire de fichier windows quand Parsec est ferme

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#913]
Lorsque je me deconnecte de Parsec , les workspaces n'apparassent plus ds le point de montage
Le point de montage lui subsiste : il est alors possible de transfere des fichiers via copier coller 
Pb : ces fichiers ne vont dans aucun workspace( car non ouverts ) et ne sont donc pas accessibles lors du redemarrage de Parsec

**Comment by vxgmichel** [comment]
Outdated with #1159
