### ISSUE TITLE
affichage logo Parsec sur point de montage

### ISSUE THREAD

**Issue by Usersdub** [Scille/parsec-cloud#914]
je le vois quand j'utilise l'utilitaire de sauvegarde des fichiers ( ci-joint )
mais pas quand j'utilise le gestionnaire de fichier windows
![Capture d'écran 2020-01-07 16 58 40](https://user-images.githubusercontent.com/46708918/72138723-b814d600-338d-11ea-83db-a69a2a63f136.png)

**Comment by vxgmichel** [comment]
Outdated with #1159
