### ISSUE TITLE
GUI should not allow manager to give manager right to other users

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#916]
As a manager of a workspace:

![image](https://user-images.githubusercontent.com/3187637/72165702-3ee6a480-33c8-11ea-9ae5-13983b75edcf.png)

This lead to cryptic errors due to the fact only owner has the right to give manager access !

![image](https://user-images.githubusercontent.com/3187637/72165773-63428100-33c8-11ea-869e-11680361bc5e.png)

This behavior exists when both sharing for the first time or updating share rights

**Comment by Max-7** [comment]
Fixed.
