### ISSUE TITLE
Impossible d'ouvrir un fichier Excel dans une enclave (ni en double clic dans l'explorateur windows, ni depuis excel). Nom trop long ?

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#917]
Fichier : C:\Users\phil\parsec_mnt\Scille-Parsec (shared by Thierry)\RAPID DGA\20191108 - Cloture PARSEC (demande paiement)\Certificat frais PARSEC (20180201-20190531) 16 mois\FRAIS MISSIONS (Détail)\Relevé de frais congrès DGA PARSEC.xlsx

![image](https://user-images.githubusercontent.com/13103240/72244902-8c912600-35ef-11ea-9f3f-e0673dfeb562.png)

![image](https://user-images.githubusercontent.com/13103240/72244734-302e0680-35ef-11ea-8a0f-8d174c29a788.png)

**Comment by Max-7** [comment]
> This error message occurs when you save or open a file if the path to the file (including the file name) exceeds 218 characters. This limitation includes three characters representing the drive, the characters in folder names, the backslash character between folders, and the characters in the file name.

https://support.microsoft.com/en-us/help/213983/error-message-when-you-open-or-save-a-file-in-microsoft-excel-filename

This applies to Excel 2007 and Excel 2010, can't seem to find any information on more recent versions of the software but I wouldn't be surprised that they have the same kind of limitations.

In your case, I count 233 characters, which exceeds the Excel limit of 218. Excel's fault, nothing on our side we can do :/
