### ISSUE TITLE
Log in button not instantly available for clicking on windows

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#921]
On windows, the log button is not instantly available for clicking after the password has been typed.
One has to either wait 1 second before clicking, or use the `Enter` key to validate the password.

**Comment by c4ffein** [comment]
@Max-7 I can confirm this problem do happen, but you effectively need to be really fast, as I only managed to reproduce it by having the password field selected and my mouse on the Log-in button, pasting my password and then trying to click multiple times : it did take nearly one second for my click to be taken into account.

**Comment by touilleMan** [comment]
Can't reproduce now
