### ISSUE TITLE
[🐛 | Bug]: Save a file inside a mountpoint after editing it

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#9221]
### Parsec version tested on:

3.2.3-rc.1

### Platforms tested on:

MacOS

### Bug description:

1. Open a text file 
2. Add some modification
3. Save it -> ERROR

### Relevant output:

![Image](https://github.com/user-attachments/assets/d88c40ee-285d-4270-9726-39e750577381)

**Comment by FirelightFlagboy** [comment]
Duplicate of #8976
