### ISSUE TITLE
Copie incorrecte massive de fichiers sous windows - Fichers indiqués inexistants à tort

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#925]
Sous l'explorateur Windwos, je copie, au sien d'une même enclave, un dossier vers un autre.
J'ai le message d'erreur ci-dessous, alors que le fichier existe.
Précisions: 
-les fichiers en erreur sont des pdf, typiquement avec l'erreur d'être non cliquable
- copie relativement massive
![image](https://user-images.githubusercontent.com/13103240/72727275-ca132780-3b8a-11ea-8474-cb139be8c69f.png)

**Comment by PhClermontScille** [comment]
Nouvel incident ce jour. Difficilement reproductible. Il s'agit d'un déplacement d'un sous-dossier dans PARSEC dans un autre sous-dossier dans la même enclave PARSEC, par drag and drop.
"Beaucoup de fichiers", quelques dizaines de MB au total.
![image](https://user-images.githubusercontent.com/13103240/73752948-19984c80-4762-11ea-8cad-0e0df782e80c.png)

**Comment by PhClermontScille** [comment]
Est-ce le problème connu de longueur de paths fichiers?

**Comment by vxgmichel** [comment]
Potentially fixed by #1159

**Comment by c4ffein** [comment]
Closed as we switched to a completly new workspace system.
