### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#965]

**Comment by touilleMan** [comment]
# Overview

There is two main issues with porting Parsec to Android:
- Exposing a mountpoint to other application
- Building a working apk

# The mountpoint

Unlike a regular Linux system, Android doesn't expose fuse to applications.
However the Android API comes with [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider)

The idea is to declare a document provider into the application, then make the java callbacks call native code (well native code which will endup calling Python code) to do the actual heavy lifting.

Pretty useful example of document provider: https://github.com/android/storage-samples/tree/master/StorageProvider

# The packaging

Parsec is a Python application with multiple native modules, especially Qt for the user interface.

To make it run on Android we need:
1 - to embed Python interpreter, Python code and Python native modules
2 - to make the application entry point jump into Python code which in turn should start Qt that would take control of the GUI
3 - to declare an Android Storage Provider and plug it to Python

:/

## Approach 1: PyQtDeploy

[PyQtDeploy](https://riverbankcomputing.com/software/pyqtdeploy/intro) is designed to allow easy application packing for both desktop (linux, mac, windows) and mobile (android, ios).

It should be the perfect fit in theory, however it has a poor documentation ([this blog post](https://medium.com/@Lola_Dam/packaging-pyqt-application-using-pyqtdeploy-for-both-linux-and-android-32ac7824708b) was very helpful) and is really not user friendly.

Worst: it doesn't seem to work with recent version of Qt that have changed there folder hierarchy:
```
env ANDROID_NDK_ROOT=$HOME/Android/Sdk/ndk/21.0.6113669/ ANDROID_NDK_PLATFORM=android-21 ANDROID_SDK_ROOT=$HOME/Android/Sdk python3 build-demo.py --verbose --target android-64 --installed-qt-dir $HOME/Qt/5.14.1/ --verbose
Configuring openssl...
Looking for '/home/touilleman/Qt/5.14.1/openssl-1.0.2r.tar.gz'
Looking for '/home/touilleman/projects/pyqtdeploy-test/demo/openssl-1.0.2r.tar.gz'
Found '/home/touilleman/projects/pyqtdeploy-test/demo/openssl-1.0.2r.tar.gz'
Configuring qt5...
Looking for '/home/touilleman/Qt/5.14.1/android_arm64_v8a'
Looking for '/home/touilleman/projects/pyqtdeploy-test/demo/android_arm64_v8a'
pyqtdeploy-sysroot: nothing matching 'android_arm64_v8a' could not be found
```

On top of that, the build process should be customized to allow shipping java code to create the Android Storage Provider.

## Approach 2: Android Studio

Most obvious way to build an Android application. However we're on our own to integrate all the exotic parts (Python and Qt). So I guess there is not much to get from there.

## Approach 3: QtCreator

QtCreator works well to create & ship Qt/C++ application on Android.
This leave us with two hassles:
1 - plug the java Android Storage Provider code
2 - compile&ship a CPython interpreter (and all the native python modules !) as a shared library for the main C++ code.

Step 1 should be doable by tweaking the Android xml and graddle configuration autogenerated for the project by QtCreator when targetting Android...
[Python-for-Android](https://github.com/kivy/python-for-android) project should help on step 2 (though I didn't try it yet)

**Comment by dhanrajmahurkar** [comment]
Hi, I really like parsec for the latency and robust connection it offers.The only problem is on Android where there are lot of problems with input bindings especially with the mouse. I suggest to refer another open source project(moonlight) to fix them : https://github.com/moonlight-stream/moonlight-android/tree/master/app/src/main/java/com/limelight/binding/input
