### ISSUE TITLE
Some elements get an ugly selection rectangle

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-cloud#967]
![selection_rectangle](https://user-images.githubusercontent.com/18075498/74520566-1f3b2280-4f18-11ea-84b1-229f95434a4a.png)
See on xfce and Windows

**Comment by touilleMan** [comment]
![image](https://user-images.githubusercontent.com/3187637/116972085-cd1c2380-acba-11eb-85d3-740b2fa17e64.png)
