### ISSUE TITLE
Send an automated email with parsec link when on-boarding user

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#969]
Today, when on-boarding users, the administrators will most likely draft an email by hand with the parsec link and few explanations of the steps that will follow.

The proposition is to send an email automatically from Parsec.

The changes that would be required :
1. Request the user email address when adding an user to an organization.
2. Write the necessary steps in the email (download Parsec client, click on the link, if clicking doesn't work copy/paste the link)

**Comment by touilleMan** [comment]
Depends on #1119

**Comment by Max-7** [comment]
Done.
