### ISSUE TITLE
Ergonomie: pouvoir effacer l'historique

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#972]
Passage de 1.1.2 à 1.6: tous les nombreux essais antérieurs s'affichent.
Pourrait on avoir la possibilité d'effacer l'historique ?
![image](https://user-images.githubusercontent.com/13103240/74715691-43a34180-522d-11ea-9a6d-1dd31d9e3591.png)

**Comment by Max-7** [comment]
Après discussion, nous préférons ne pas offrir cette fonctionnalité, elle pourrait trop rapidement risquer de faire perdre des données à un utilisateur. D'autant plus que la multiplication du nombre de devices est un problème qui n'arrivait normalement que pour les alpha testeurs à une époque où on remettait la db à zéro régulièrement.

J'ai écrit un petit paragraphe sur le sujet avec la méthode pour régler le problème :  https://github.com/Scille/parsec-cloud/wiki/Common-problems

En gros, il faut aller dans %APPDATA%\parsec\config\devices et supprimer les devices anciens, en faisant évidemment très attention à supprimer les bons.
