### ISSUE TITLE
Ergonomie: message déroutant pour créer un nouveau device

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-cloud#975]
Cf screenshot (qui montre aussi un problème d'affichage sur 13" / 14".
En fait "Fournir une adresse manuellement" veut dire "Enregistrer un nouvel appareil" ?
![image (1)](https://user-images.githubusercontent.com/13103240/74731080-9f7ac400-5247-11ea-8f13-1da33fda3b27.png)

**Comment by Max-7** [comment]
Fixed by new GUI design.
