### ISSUE TITLE
Translate "Changelog" label for the French version 

### ISSUE THREAD

**Issue by stefan-contiu** [Scille/parsec-cloud#994]
Find a suitable translation. A possibility is "Journal des versions"

**Comment by Max-7** [comment]
Microsoft conseille "journal des modifications" (https://www.microsoft.com/en-us/language/Search?&searchTerm=changelog&langID=303&Source=true&productid=0)

**Comment by Max-7** [comment]
https://github.com/Scille/parsec-cloud/commit/6861c63fc0f9e4467003fd1ed456f2b1d4fbdde5
